TRUNCATE TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN";

INSERT INTO "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" (BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE,RECEIVED_COUNT,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP,ZIP_EXP)
SELECT TRY_CAST(BUDGET_YEAR AS INT), TRY_CAST(BUDGET_MONTH AS INT),
CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','TMOBILE5G-FIBER','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,TASK_NAME,INPUT_CLIENT_NAME,TRY_CAST(DATE_CREATED AS DATE),TRY_CAST(TARGET_VOLUME AS INT),PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP,ZIP_EXP FROM "SCIERA_SUBSYSTEM"."SKY_OP"."COX_BUDGET_PLAN";


INSERT INTO "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" (MSO,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,INPUT_TYPE,RECEIVED_DATE,RECEIVED_COUNT)
SELECT 'CHARTER' MSO,NEW_PUBLISH_NAME,PROJECT_NAME  INPUT_FILE_NAME ,COMPETITOR INPUT_CLIENT_NAME,
YEAR(CAST(EXTRACT_DATE AS DATE)) BUDGET_YEAR,
MONTH(CAST(EXTRACT_DATE AS DATE)) BUDGET_MONTH,
CASE WHEN UPPER(NEW_PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(NEW_PUBLISH_NAME) IN ('TMOBILE5G-HOME','TMOBILE5G-FIBER','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,
'RESI' ENGAGEMENT_TYPE,
'HOUSKEY_LEVEL' INPUT_TYPE,
CAST(EXTRACT_DATE AS DATE) RECEIVED_DATE,
COUNT(*) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI" 
GROUP BY MSO,NEW_PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,
INPUT_TYPE,RECEIVED_DATE ;

INSERT INTO "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" (MSO,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,INPUT_TYPE,RECEIVED_DATE,RECEIVED_COUNT)
SELECT 'CHARTER_BUSINESS' MSO,NEW_PUBLISH_NAME,PROJECT_NAME  INPUT_FILE_NAME ,COMPETITOR INPUT_CLIENT_NAME,
YEAR(CAST(EXTRACT_DATE AS DATE)) BUDGET_YEAR,
MONTH(CAST(EXTRACT_DATE AS DATE)) BUDGET_MONTH,
CASE WHEN UPPER(NEW_PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(NEW_PUBLISH_NAME) IN ('TMOBILE5G-HOME','TMOBILE5G-FIBER','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,
'SMB' ENGAGEMENT_TYPE,
'HOUSKEY_LEVEL' INPUT_TYPE,
CAST(EXTRACT_DATE AS DATE) RECEIVED_DATE,
COUNT(*) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_SMB" 
GROUP BY MSO,NEW_PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,
INPUT_TYPE,RECEIVED_DATE ;

INSERT INTO "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" (MSO,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,INPUT_TYPE,RECEIVED_DATE,RECEIVED_COUNT)
SELECT 'CHARTER' MSO,NEW_PUBLISH_NAME,PROJECT_NAME  INPUT_FILE_NAME ,COMPETITOR INPUT_CLIENT_NAME,
YEAR(CAST(EXTRACT_DATE AS DATE)) BUDGET_YEAR,
MONTH(CAST(EXTRACT_DATE AS DATE)) BUDGET_MONTH,
CASE WHEN UPPER(NEW_PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(NEW_PUBLISH_NAME) IN ('TMOBILE5G-HOME','TMOBILE5G-FIBER','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,
'RESI' ENGAGEMENT_TYPE,
'CB_LEVEL' INPUT_TYPE,
CAST(EXTRACT_DATE AS DATE) RECEIVED_DATE,
COUNT(*) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI_CB" 
GROUP BY MSO,NEW_PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,
INPUT_TYPE,RECEIVED_DATE;

UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" A
SET A.PROJECT_NAME = CASE WHEN A.PROJECT_NAME IS NULL THEN B.PROJECTNAME ELSE A.PROJECT_NAME END,
    A.SCHEDULE_DATE = B.SCHEDULEDATE,
    A.QUEUED = B.QUEUED,
    A.CHECKED = B.CHECKED,
    A.DELIVERED = B.DELIVERED,
    A.UNDELIVERABLE = B.UNDELIVERABLE
FROM (SELECT MSO,SERVICENAME,PROJECTNAME,MIN(SCHEDULEDATE) SCHEDULEDATE,COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE FROM "V4_CTELL"."PROC"."WIP_CURRENT" 
 GROUP BY MSO,SERVICENAME,PROJECTNAME) B    
WHERE A.MSO = B.MSO AND UPPER(A.PUBLISH_NAME) = UPPER(B.SERVICENAME)
 AND  (UPPER(A.INPUT_FILE_NAME) LIKE '%' || UPPER(B.PROJECTNAME)||'%'
 OR  UPPER(B.PROJECTNAME) LIKE '%' || UPPER(A.INPUT_FILE_NAME)||'%');

UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" A
SET A.READY_FOR_DELIVERY = CHECKED - DELIVERED - UNDELIVERABLE;

UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN"
SET PROJECT_TYPE = CASE WHEN UPPER(SUBSTR(PROJECT_NAME,1,1))='B'  THEN 'BL'
                        WHEN UPPER(SUBSTR(PROJECT_NAME,1,1))='D' OR 
                             UPPER(SUBSTR(PROJECT_NAME,1,2))='NQ'  THEN 'NQ'
                        WHEN UPPER(SUBSTR(PROJECT_NAME,1,1))='W' THEN 'WL'
                        WHEN UPPER(SUBSTR(PROJECT_NAME,1,2))='A_' THEN 'AH'
                        ELSE NULL END
WHERE PROJECT_TYPE IS NULL;

UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" A
 SET A.PROVIDER_NAME=B.STD_NAME FROM "SCIERA_SUBSYSTEM"."SKY_OP"."MASTER_STD_NAME_CTELL" B
 WHERE UPPER(A.PUBLISH_NAME)=UPPER(B.PUBLISH_NAME) AND ACTIVE='Y' AND A.PROVIDER_NAME IS NULL;
 