COPY INTO  "V4_CTELL"."DELIVERIES"."COMCAST_DELIVERY" (CORP_SYSPRIN,HOUSE_KEY,CHECK_DATE,ILEC_PROVIDER,ILEC_AVAILABILITY,MAX_DOWNLOAD,MAX_UPLOAD,ILEC_TECH_CODE,ILEC_DSL_PROVIDER,ILEC_DSL_MAX_SPEED,ILEC_FIBER_PROVIDER,ILEC_FIBER_MAX_SPEED,ILEC_INTERNET_CUSTOMER,ILEC_FIBER_TV_PROVIDER,ILEC_FIBER_PHONE_PROVIDER,OB1_GENERIC_NAME,OB1_MAX_SPEED_NUM,OB1_MAX_UPLOAD,OB1_TECH_CODE,OB1_CUSTOMER,OB1_CHECK_DATE,OB2_GENERIC_NAME,OB2_MAX_SPEED_NUM,OB2_MAX_UPLOAD,OB2_TECH_CODE,OB2_CUSTOMER,OB2_CHECK_DATE,OB3_GENERIC_NAME,OB3_MAX_DOWNLOAD,OB3_MAX_UPLOAD,OB3_TECH_CODE,OB3_CUSTOMER,OB3_CHECK_DATE,OB4_GENERIC_NAME,OB4_MAX_DOWNLOAD,OB4_MAX_UPLOAD,OB4_TECH_CODE,OB4_CUSTOMER,OB4_CHECK_DATE,OB5_GENERIC_NAME,OB5_MAX_DOWNLOAD,OB5_MAX_UPLOAD,OB5_TECH_CODE,OB5_CUSTOMER,OB5_CHECK_DATE,OB6_GENERIC_NAME,OB6_MAX_DOWNLOAD,OB6_MAX_UPLOAD,OB6_TECH_CODE,OB6_CUSTOMER,OB6_CHECK_DATE,OB7_GENERIC_NAME,OB7_MAX_DOWNLOAD,OB7_MAX_UPLOAD,OB7_TECH_CODE,OB7_CUSTOMER,OB7_CHECK_DATE,OB8_GENERIC_NAME,OB8_MAX_DOWNLOAD,OB8_MAX_UPLOAD,OB8_TECH_CODE,OB8_CUSTOMER,OB8_CHECK_DATE,OB9_GENERIC_NAME,OB9_MAX_DOWNLOAD,OB9_MAX_UPLOAD,OB9_TECH_CODE,OB9_CUSTOMER,OB9_CHECK_DATE,OB10_GENERIC_NAME,OB10_MAX_DOWNLOAD,OB10_MAX_UPLOAD,OB10_TECH_CODE,OB10_CUSTOMER,OB10_CHECK_DATE,OB11_GENERIC_NAME,OB11_MAX_DOWNLOAD,OB11_MAX_UPLOAD,OB11_TECH_CODE,OB11_CUSTOMER,OB11_CHECK_DATE,CHECK_FLAG,ADDRESS1,ADDRESS2,CITY,STATE,ZIP5,ZIP4,DWELL,DIVISION,REGION,ENTITY,DMA,NODE,RESULT_STATUS,PROJECT_NAME,GOOGLE_FIBERHOOD_STATUS,GOOGLE_CUSTOMER_STATUS,GOOGLE_LOW_COST,GOOGLE_NUM_PRODUCTS,GOOGLE_MOBILE,BLANK1,BLANK2,GOOGLE_CHECK_DATE,GOOGLE_ADDRESS_CHECK_DATE,OB1_CHECK_FLAG,OB2_CHECK_FLAG,OB3_CHECK_FLAG,OB4_CHECK_FLAG,OB5_CHECK_FLAG,OB6_CHECK_FLAG,OB7_CHECK_FLAG,OB8_CHECK_FLAG,OB9_CHECK_FLAG,OB10_CHECK_FLAG,OB11_CHECK_FLAG,OB1_PROJECT_NAME,OB2_PROJECT_NAME,OB3_PROJECT_NAME,OB4_PROJECT_NAME,OB5_PROJECT_NAME,OB6_PROJECT_NAME,OB7_PROJECT_NAME,OB8_PROJECT_NAME,OB9_PROJECT_NAME,OB10_PROJECT_NAME,OB11_PROJECT_NAME,DELIVERED_DATE) FROM (SELECT t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,t.$17,t.$18,t.$19,t.$20,t.$21,t.$22,t.$23,t.$24,t.$25,t.$26,t.$27,t.$28,t.$29,t.$30,t.$31,t.$32,t.$33,t.$34,t.$35,t.$36,t.$37,t.$38,t.$39,t.$40,t.$41,t.$42,t.$43,t.$44,t.$45,t.$46,t.$47,t.$48,t.$49,t.$50,t.$51,t.$52,t.$53,t.$54,t.$55,t.$56,t.$57,t.$58,t.$59,t.$60,t.$61,t.$62,t.$63,t.$64,t.$65,t.$66,t.$67,t.$68,t.$69,t.$70,t.$71,t.$72,t.$73,t.$74,t.$75,t.$76,t.$77,t.$78,t.$79,t.$80,t.$81,t.$82,t.$83,t.$84,t.$85,t.$86,t.$87,t.$88,t.$89,t.$90,t.$91,t.$92,t.$93,t.$94,t.$95,t.$96,t.$97,t.$98,t.$99,t.$100,t.$101,t.$102,t.$103,t.$104,t.$105,t.$106,t.$107,t.$108,t.$109,t.$110,t.$111,t.$112,t.$113,t.$114,t.$115,t.$116,t.$117,t.$118,t.$119,t.$120,t.$121,t.$122,t.$123,t.$124,t.$125,t.$126,t.$127,'<<YYYY_MM_DD>>' FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYANALYST"<<DELIVERY_FILE_PATH>>' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

DELETE FROM "V4_CTELL"."DELIVERIES"."COMCAST_DELIVERY" WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' AND HOUSE_KEY = 'HOUSE_KEY';

UPDATE  V4_CTELL.DELIVERIES.COMCAST_DELIVERY A
SET A.CB = B.SCIERA_CB
FROM (SELECT DISTINCT FP_KEY,SCIERA_CB FROM "MSO"."V3_COMCAST_RESOURCE"."FP" ) B
WHERE CONCAT_WS('_',A.CORP_SYSPRIN,A.HOUSE_KEY) = B.FP_KEY AND IFNULL(A.CB,'')='' AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,ILEC_PROVIDER AS PROVIDER,TRY_CAST(MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(ILEC_PROVIDER,'')<>'' AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB1_GENERIC_NAME AS PROVIDER,TRY_CAST(OB1_MAX_SPEED_NUM AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB1_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB1_GENERIC_NAME,'')<>'' AND OB1_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB2_GENERIC_NAME AS PROVIDER,TRY_CAST(OB2_MAX_SPEED_NUM AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB2_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB2_GENERIC_NAME,'')<>'' AND OB2_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB3_GENERIC_NAME AS PROVIDER,TRY_CAST(OB3_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB3_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB3_GENERIC_NAME,'')<>'' AND OB3_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB4_GENERIC_NAME AS PROVIDER,TRY_CAST(OB4_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB4_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB4_GENERIC_NAME,'')<>'' AND OB4_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB5_GENERIC_NAME AS PROVIDER,TRY_CAST(OB5_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB5_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB5_GENERIC_NAME,'')<>'' AND OB5_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB6_GENERIC_NAME AS PROVIDER,TRY_CAST(OB6_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB6_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB6_GENERIC_NAME,'')<>'' AND OB6_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB7_GENERIC_NAME AS PROVIDER,TRY_CAST(OB7_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB7_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB7_GENERIC_NAME,'')<>'' AND OB7_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB8_GENERIC_NAME AS PROVIDER,TRY_CAST(OB8_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB8_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB8_GENERIC_NAME,'')<>'' AND OB8_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB9_GENERIC_NAME AS PROVIDER,TRY_CAST(OB9_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB9_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB9_GENERIC_NAME,'')<>'' AND OB9_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB10_GENERIC_NAME AS PROVIDER,TRY_CAST(OB10_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB10_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB10_GENERIC_NAME,'')<>'' AND OB10_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB11_GENERIC_NAME AS PROVIDER,TRY_CAST(OB11_MAX_DOWNLOAD AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB11_CHECK_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COMCAST_DELIVERY WHERE IFNULL(OB11_GENERIC_NAME,'')<>'' AND OB11_CHECK_FLAG IN ('A','X') AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED (CB,PROVIDER,MAX_DOWNLOAD,DELIVERED_DATE)
SELECT CB,PROVIDER,MAX(MAX_DOWNLOAD) MAX_DOWNLOAD,DELIVERED_DATE FROM V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' GROUP BY CB,PROVIDER,DELIVERED_DATE ;


UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED A 
SET A.CHECK_DATE= B.CHECK_DATE
FROM  
(SELECT CB,PROVIDER,MAX_DOWNLOAD,MAX(CHECK_DATE) AS CHECK_DATE,DELIVERED_DATE FROM  V4_CTELL.PROC.COMCAST_CB_ROLLUP_STAGE WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' GROUP BY CB,PROVIDER,MAX_DOWNLOAD,DELIVERED_DATE )B
WHERE A.CB=B.CB AND A.PROVIDER=B.PROVIDER AND A.MAX_DOWNLOAD=B.MAX_DOWNLOAD AND A.DELIVERED_DATE=B.DELIVERED_DATE ;


UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(REPLACE(REPLACE(REPLACE(B.PUBLISH_NAME,'111',' '),'222',', '),'333','.')) AND B.ACTIVE='Y' AND A.STD_NAME IS NULL
AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(REPLACE(REPLACE(REPLACE(B.PUBLISH_NAME,'111',' '),'222',', '),'333','.'))  AND A.STD_NAME IS NULL
AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(B.PUBLISH_NAME,'111',' '),'222',', '),'333','.'),'  ',' '))  AND A.STD_NAME IS NULL
AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(B.STD_NAME)  AND A.STD_NAME IS NULL AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED 
SET STD_NAME=  CASE 
WHEN PROVIDER = 'BITWISE COMMUNICATIONS, INC.' THEN 'BITWISE COMMUNICATIONS, INC.' 
WHEN PROVIDER = 'TACHUS FIBER INTERNET' THEN 'TACHUS' 
WHEN PROVIDER = 'EVERYWHERE WIRELESS' THEN 'EVERYWHERE WIRELESS' 
WHEN PROVIDER = 'BREEZELINE' THEN 'ATLANTIC BROADBAND' 
WHEN PROVIDER = 'HICKORY TELEPHONE CO.' THEN 'HICKORY TELEPHONE CO.' 
WHEN PROVIDER = 'FAIRPOINT' THEN 'CONSOLIDATED COMMUNICATION' 
WHEN PROVIDER = 'LIGHTSPEED COMMUNICATIONS' THEN 'LIGHTSPEED COMMUNICATIONS' 
WHEN PROVIDER = 'US INTERNET' THEN 'US INTERNET' 
WHEN PROVIDER = 'C-SPIRE' THEN 'CSPIRE' 
WHEN PROVIDER = 'ROCKET FIBER' THEN 'ROCKET FIBER' 
WHEN PROVIDER = 'OPTIMUM' THEN 'ALTICE' 
WHEN PROVIDER = 'T-MOBILE' THEN 'T-MOBILE 5G' ELSE NULL END 
WHERE STD_NAME IS NULL AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';


UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED 
SET FIBER = IFF(MAX_DOWNLOAD>=300,'Y','N') WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' ;

UPDATE V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED
SET CB = NULL WHERE IFNULL(CB,'')=''  AND DELIVERED_DATE  = '<<YYYY_MM_DD>>' ;

INSERT INTO V4_CTELL.ROLLUPS.COMCAST_CB_FIBER
SELECT CB,STD_NAME,FIBER,CHECK_DATE,DELIVERED_DATE FROM  V4_CTELL.ROLLUPS.COMCAST_CB_MAXSPEED 
WHERE CB IS NOT NULL AND  MAX_DOWNLOAD IS NOT NULL AND  DELIVERED_DATE  = '<<YYYY_MM_DD>>';
