TRUNCATE TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" ;

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" (QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR,CHECKED_MONTH,DELIVERED_YEAR,DELIVERED_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,ZIP5,FIBER_COUNT,QUEUED,CHECKED,DELIVERED,UNDELIVERABLE,CHECKED_STATUS_AV,CHECKED_STATUS_NA,CHECKED_STATUS_ER,CHECKED_GIG_RESULT,DELIVERED_STATUS_AV,DELIVERED_STATUS_NA,DELIVERED_STATUS_ER,DELIVERED_GIG_RESULT)
SELECT BUDGET_YEAR AS QUEUE_YEAR,BUDGET_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(SERVICENAME) AS PUBLISHNAME,UPPER(STD_NAME) AS STD_NAME,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,ZIP5,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300,1,0)) AS FIBER_COUNT,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940,1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940,1,0)) AS DELIVERED_GIG_RESULT
FROM "V4_CTELL"."PROC"."WIP_CURRENT"  WHERE  MSO<>'COMCAST'
GROUP BY QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,SERVICENAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,ZIP5
ORDER BY UNDELIVERABLE DESC ;


INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" (QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR,CHECKED_MONTH,DELIVERED_YEAR,DELIVERED_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5,FIBER_COUNT,QUEUED,CHECKED,DELIVERED,UNDELIVERABLE,CHECKED_STATUS_AV,CHECKED_STATUS_NA,CHECKED_STATUS_ER,CHECKED_GIG_RESULT,DELIVERED_STATUS_AV,DELIVERED_STATUS_NA,DELIVERED_STATUS_ER,DELIVERED_GIG_RESULT)
SELECT BUDGET_YEAR AS QUEUE_YEAR,BUDGET_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(SERVICENAME) AS PUBLISHNAME,UPPER(STD_NAME) AS STD_NAME,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300,1,0)) AS FIBER_COUNT,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940,1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940,1,0)) AS DELIVERED_GIG_RESULT
FROM "V4_CTELL"."PROC"."WIP_CURRENT"  WHERE  MSO='COMCAST'
GROUP BY QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,SERVICENAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5
ORDER BY UNDELIVERABLE DESC ;


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"   A
SET A.RNK = B.RNK_VAL
FROM (SELECT *,ROW_NUMBER() OVER (PARTITION BY QUEUE_YEAR,QUEUE_MONTH,MSO,ENGAGEMENT_TYPE,PUBLISHNAME,PROJECT_TYPE,H1 ORDER BY QUEUE_YEAR,QUEUE_MONTH) AS RNK_VAL
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"  ) B
WHERE A.ID = B.ID;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET TARGET = B.MONTHLY_TARGET
FROM "SCIERA_SUBSYSTEM"."SKY_OP"."MSO_TRACKING_2024" B
WHERE UPPER(A.PUBLISHNAME) =  UPPER(B.PROVIDER_NAME) AND A.QUEUE_YEAR = B.BUDGET_YEAR  AND REPLACE(A.MSO,'_BUSINESS','') = B.MSO
AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND A.MSO <>'COMCAST'   AND A.RNK = 1 ;
             
UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET TARGET = B.MONTHLY_TARGET
FROM "SCIERA_SUBSYSTEM"."SKY_OP"."MSO_TRACKING_2024" B
WHERE A.PUBLISHNAME = B.PROVIDER_NAME AND A.QUEUE_YEAR = B.BUDGET_YEAR  AND REPLACE(A.MSO,'_BUSINESS','') = B.MSO
AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE 
AND A.H1 = B.DIVISION AND A.MSO = 'COMCAST' AND A.RNK = 1;

 
 UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET NQ = B.NQ_COUNT,
WL = B.WL_COUNT
FROM (SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PUBLISH_NAME,COUNT(*),
SUM(IFF(PROJECT_TYPE='WL',RECEIVED_COUNT,0)) AS WL_COUNT
,SUM(IFF(PROJECT_TYPE='NQ',RECEIVED_COUNT,0)) AS NQ_COUNT
FROM "SCIERA_SUBSYSTEM"."SKY_OP"."QS_DASHBOARD_BUDGET_PLAN" GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PUBLISH_NAME
) B
WHERE A.PUBLISHNAME = B.PUBLISH_NAME AND A.QUEUE_YEAR = B.BUDGET_YEAR  AND A.MSO = B.MSO
AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND A.QUEUE_MONTH = B.BUDGET_MONTH  AND A.RNK = 1;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET BAU = TARGET - (IFF(NQ IS NULL ,0,NQ) + IFF(WL IS NULL ,0,WL));

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET PROJECT_TYPE = 'OTHERS'
WHERE PROJECT_TYPE IS NULL;
 

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET READY_FOR_DELIVERY = CHECKED - DELIVERED - UNDELIVERABLE;
                        
UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET A.RECEIVED_COUNT = B.CNT FROM
(SELECT UPPER(PROJECT_NAME) PROJECT_NAME,UPPER(NEW_PUBLISH_NAME) NEW_PUBLISH_NAME,COUNT(*) AS CNT FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_SMB" GROUP BY 1,2
) B WHERE  UPPER(A.PROJECT_NAME) LIKE '%' || UPPER(B.PROJECT_NAME)||'%'
AND UPPER(A.PUBLISHNAME )= UPPER( B.NEW_PUBLISH_NAME); 

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET A.RECEIVED_COUNT = B.CNT FROM
(SELECT UPPER(PROJECT_NAME) PROJECT_NAME,UPPER(NEW_PUBLISH_NAME) NEW_PUBLISH_NAME,COUNT(*) AS CNT FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI" GROUP BY 1,2
) B WHERE  UPPER(A.PROJECT_NAME) LIKE '%' || UPPER(B.PROJECT_NAME)||'%'
AND UPPER(A.PUBLISHNAME )= UPPER( B.NEW_PUBLISH_NAME); 

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET A.RECEIVED_COUNT = B.CNT FROM
(SELECT UPPER(PROJECT_NAME) PROJECT_NAME,UPPER(NEW_PUBLISH_NAME) NEW_PUBLISH_NAME,COUNT(*) AS CNT FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI_CB" GROUP BY 1,2
) B WHERE  UPPER(A.PROJECT_NAME) LIKE '%' || UPPER(B.PROJECT_NAME)||'%'
AND UPPER(A.PUBLISHNAME) = UPPER(B.NEW_PUBLISH_NAME); 

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET PROJECT_TYPE = 'OTHERS'
WHERE PROJECT_NAME = 'D_COX_RESI_2024-03-01_WATCHLIST_20240302';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" 
SET STD_NAME = REPLACE(REPLACE(REPLACE(REPLACE(PUBLISHNAME,'111',' '),'222',', '),'333','.'),'  ',' ')  
WHERE STD_NAME IS NULL OR STD_NAME = '';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" 
SET SERVICENAME = REPLACE(REPLACE(REPLACE(RTRIM(PUBLISHNAME), '111', ' '),'222',','),'333','.')  
WHERE SERVICENAME IS NULL ;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
SET CALC_TARGET = CASE WHEN PROJECT_TYPE = 'NQ' THEN NQ 
                       WHEN PROJECT_TYPE = 'BL' THEN BAU
                       WHEN PROJECT_TYPE = 'WL' THEN WL ELSE 0 END;

