COPY INTO "V4_CTELL"."DELIVERIES"."COX_DELIVERY" (TIME_KEY,SITE_ID,HOUSE_NBR,SERVICE_NAME,STATUS,STATUS_DESC,HOUSE_KEY,COMPETITOR,COMP_DSL_PROVIDER,COMP_DSL_MAXSPEED,COMP_FIBER_PROVIDER,COMP_FIBER_MAXSPEED,COMP_INTERNET_CUSTOMER,COMP_INTERNET_CUSTOMER_SPEED,COMP_PHONE1_CUSTOMER,COMP_PHONE2_CUSTOMER,COMP_FIBER_TV_PROVIDER,COMP_FIBER_PHONE_PROVIDER,COMP_TV_CUSTOMER,COMP_FIBER_PHONE_CUSTOMER,DATE_CHECKED,CENTURYLINK_COMING_SOON,COMP_DSL_MAXSPEED_NUMBER,COMP_FIBER_MAXSPEED_NUMBER,HOME_CARRIER_LABEL,HOME_CARRIER_NAME,HOME_CARRIER_TYPE,SERVICE_CARRIER_LABEL,SERVICE_CARRIER_NAME,SERVICE_CARRIER_TYPE,HOME_PHONE_PORT_DATE,SERVICE_PHONE_PORT_DATE,FIBER_TV_IND,FIBER_VIDEO_FLAG,MATCH_FIBER_DEF,FIBER_TV_LAST6_IND,SPEED_BUCKET_KEY,SPEED_BCKT_INC_IND,CURRENT_FLG,FINAL_COMPETITOR,ILEC_NAME,ILEC_MAX_SPEED,ILEC_FIBER_TV,OB1_NAME,OB1_MAX_SPEED,OB1_FIBER_TV,OB2_NAME,OB2_MAX_SPEED,OB2_FIBER_TV,HOME_MAX_SPEED,FIBER_TV_AVAILABLE,SITE_KEY,COMPETITOR_SERVICE_KEY,ILEC_FIBER_FIRST_FOUND_DATE,OB1_FIBER_FIRST_FOUND_DATE,OB2_FIBER_FIRST_FOUND_DATE,CREATE_DT,PRE_SERV_FLAG,DELIVERED_DATE) FROM (SELECT T.$1,T.$2,T.$3,T.$4,T.$5,T.$6,T.$7,T.$8,T.$9,T.$10,T.$11,T.$12,T.$13,T.$14,T.$15,T.$16,T.$17,T.$18,T.$19,T.$20,T.$21,T.$22,T.$23,T.$24,T.$25,T.$26,T.$27,T.$28,T.$29,T.$30,T.$31,T.$32,T.$33,T.$34,T.$35,T.$36,T.$37,T.$38,T.$39,T.$40,T.$41,T.$42,T.$43,T.$44,T.$45,T.$46,T.$47,T.$48,T.$49,T.$50,T.$51,T.$52,T.$53,T.$54,T.$55,T.$56,T.$57,T.$58,'<<YYYY_MM_DD>>' FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"<<DELIVERY_FILE_PATH>>' T) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 1,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),ENCODING = 'ISO-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

UPDATE  V4_CTELL.DELIVERIES.COX_DELIVERY A
SET A.CB = B.SCIERA_CB
FROM (SELECT DISTINCT H5,SCIERA_CB FROM "MSO"."V3_COX_RESOURCE"."FP" ) B
WHERE A.HOUSE_KEY = B.H5 AND IFNULL(A.CB,'')='' AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COX_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,ILEC_NAME AS PROVIDER,TRY_CAST(ILEC_MAX_SPEED AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(ILEC_FIBER_FIRST_FOUND_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COX_DELIVERY WHERE IFNULL(ILEC_NAME,'')<>'' AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COX_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB1_NAME AS PROVIDER,TRY_CAST(OB1_MAX_SPEED AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB1_FIBER_FIRST_FOUND_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COX_DELIVERY WHERE IFNULL(OB1_NAME,'')<>'' AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.PROC.COX_CB_ROLLUP_STAGE (CB,PROVIDER,MAX_DOWNLOAD,CHECK_DATE,DELIVERED_DATE)
SELECT CB AS CB,OB2_NAME AS PROVIDER,TRY_CAST(OB2_MAX_SPEED AS DOUBLE) AS MAX_DOWNLOAD,TRY_CAST(OB2_FIBER_FIRST_FOUND_DATE AS DATE) AS CHECK_DATE,TRY_CAST(DELIVERED_DATE AS DATE) AS DELIVERED_DATE FROM V4_CTELL.DELIVERIES.COX_DELIVERY WHERE IFNULL(OB2_NAME,'')<>'' AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

INSERT INTO V4_CTELL.ROLLUPS.COX_CB_MAXSPEED (CB,PROVIDER,MAX_DOWNLOAD,DELIVERED_DATE)
SELECT CB,PROVIDER,MAX(MAX_DOWNLOAD) MAX_DOWNLOAD,DELIVERED_DATE FROM V4_CTELL.PROC.COX_CB_ROLLUP_STAGE WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' GROUP BY CB,PROVIDER,DELIVERED_DATE;


UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED A 
SET A.CHECK_DATE= B.CHECK_DATE
FROM  
(SELECT CB,PROVIDER,MAX_DOWNLOAD,MAX(CHECK_DATE) AS CHECK_DATE,DELIVERED_DATE FROM  V4_CTELL.PROC.COX_CB_ROLLUP_STAGE WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' GROUP BY CB,PROVIDER,MAX_DOWNLOAD,DELIVERED_DATE )B
WHERE A.CB=B.CB AND A.PROVIDER=B.PROVIDER AND A.MAX_DOWNLOAD=B.MAX_DOWNLOAD AND A.DELIVERED_DATE=B.DELIVERED_DATE ;

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(REPLACE(REPLACE(REPLACE(B.PUBLISH_NAME,'111',' '),'222',', '),'333','.')) AND B.ACTIVE='Y' AND A.STD_NAME IS NULL AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(REPLACE(REPLACE(REPLACE(B.PUBLISH_NAME,'111',' '),'222',', '),'333','.'))  AND A.STD_NAME IS NULL
AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(REPLACE(REPLACE(REPLACE(REPLACE(B.PUBLISH_NAME,'111',' '),'222',', '),'333','.'),'  ',' '))  AND A.STD_NAME IS NULL AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED A 
SET A.STD_NAME= B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
WHERE UPPER(A.PROVIDER)=UPPER(B.STD_NAME)  AND A.STD_NAME IS NULL AND A.DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED 
SET STD_NAME=  CASE 
WHEN PROVIDER = 'BREEZELINE' THEN 'ATLANTIC BROADBAND' 
WHEN PROVIDER = 'WYYERD' THEN 'ZONA WYYERD' 
WHEN PROVIDER = 'TDS' THEN 'TDS TELECOM' 
WHEN PROVIDER = 'REV' THEN 'REV' 
WHEN PROVIDER = 'Crawkan' THEN 'CRAWKAN' 
WHEN PROVIDER = 'HARGRAY COMMUNICATIONS' THEN 'HARGRAY'
WHEN PROVIDER = 'WAVE RURAL' THEN 'WAVE RURAL CONNECT' 
WHEN PROVIDER = 'CONEXON' THEN 'CONEXON CONNECT' 
WHEN PROVIDER = 'RightFiber' THEN 'RIGHT FIBER' 
WHEN PROVIDER = 'RITTER111COMMUNICATIONS' THEN 'RIGHT FIBER' 
WHEN PROVIDER = 'FASTWYRE' THEN 'FASTWYRE BROADBAND' 
WHEN PROVIDER = 'LUMOS111NETWORKS111INC' THEN 'LUMOS' ELSE NULL END 
WHERE STD_NAME IS NULL AND DELIVERED_DATE  = '<<YYYY_MM_DD>>';

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED 
SET FIBER = IFF(MAX_DOWNLOAD>=300,'Y','N') WHERE DELIVERED_DATE  = '<<YYYY_MM_DD>>' ;

UPDATE V4_CTELL.ROLLUPS.COX_CB_MAXSPEED
SET CB = NULL WHERE IFNULL(CB,'')=''  AND DELIVERED_DATE  = '<<YYYY_MM_DD>>' ;

INSERT INTO V4_CTELL.ROLLUPS.COX_CB_FIBER
SELECT CB,STD_NAME,FIBER,CHECK_DATE,DELIVERED_DATE FROM  V4_CTELL.ROLLUPS.COX_CB_MAXSPEED 
WHERE CB IS NOT NULL AND  MAX_DOWNLOAD IS NOT NULL AND  DELIVERED_DATE  = '<<YYYY_MM_DD>>' ;
