TRUNCATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS";

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"(QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR,CHECKED_MONTH,DELIVERED_YEAR,DELIVERED_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,SERVICE_PROVIDER,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,QUEUED,CHECKED,DELIVERED,UNDELIVERABLE,CHECKED_STATUS_AV,CHECKED_STATUS_NA,CHECKED_STATUS_ER,CHECKED_GIG_RESULT,DELIVERED_STATUS_AV,DELIVERED_STATUS_NA,DELIVERED_STATUS_ER,DELIVERED_GIG_RESULT)
SELECT BUDGET_YEAR AS QUEUE_YEAR,BUDGET_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(STD_NAME) AS SERVICE_PROVIDER,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940,1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940,1,0)) AS DELIVERED_GIG_RESULT
FROM "V4_CTELL"."PROC"."WIP_CURRENT"  WHERE STD_NAME IS NOT NULL AND MSO<>'COMCAST'
GROUP BY QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME
ORDER BY UNDELIVERABLE DESC ;


INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"(QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR,CHECKED_MONTH,DELIVERED_YEAR,DELIVERED_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,SERVICE_PROVIDER,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,QUEUED,CHECKED,DELIVERED,UNDELIVERABLE,CHECKED_STATUS_AV,CHECKED_STATUS_NA,CHECKED_STATUS_ER,CHECKED_GIG_RESULT,DELIVERED_STATUS_AV,DELIVERED_STATUS_NA,DELIVERED_STATUS_ER,DELIVERED_GIG_RESULT)
SELECT BUDGET_YEAR AS QUEUE_YEAR,BUDGET_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(STD_NAME) AS SERVICE_PROVIDER,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940,1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940,1,0)) AS DELIVERED_GIG_RESULT
FROM "V4_CTELL"."PROC"."WIP_CURRENT"  WHERE STD_NAME IS NOT NULL AND MSO='COMCAST'
GROUP BY QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1
ORDER BY UNDELIVERABLE DESC ;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET TARGET = CASE WHEN PROJECT_TYPE = 'BL' THEN CAST(B.BAU AS INT)
                   WHEN PROJECT_TYPE = 'NQ' THEN CAST(B.NQA AS INT)
                   WHEN PROJECT_TYPE = 'WL' THEN CAST(B.WL AS INT) END
FROM "SCIERA_SUBSYSTEM"."SKY_OP"."MSO_MONTHLY_PLAN_2024_TEST" B
WHERE A.SERVICE_PROVIDER = B.PUBLISH_NAME AND A.QUEUE_YEAR = B.BUDGET_YEAR  AND REPLACE(A.MSO,'_SMB','') = B.MSO
AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND A.QUEUE_MONTH = B.BUDGET_MONTH AND B.MSO <>'COMCAST';
             
UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET TARGET = CASE WHEN PROJECT_TYPE = 'BL' THEN CAST(B.BAU AS INT)
                   WHEN PROJECT_TYPE = 'NQ' THEN CAST(B.NQA AS INT)
                   WHEN PROJECT_TYPE = 'WL' THEN CAST(B.WL AS INT) END
FROM "SCIERA_SUBSYSTEM"."SKY_OP"."MSO_MONTHLY_PLAN_2024_TEST" B
WHERE A.SERVICE_PROVIDER = B.PUBLISH_NAME AND A.QUEUE_YEAR = B.BUDGET_YEAR  AND REPLACE(A.MSO,'_SMB','') = B.MSO
AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND A.QUEUE_MONTH = B.BUDGET_MONTH 
AND A.H1 = B.DIVISION AND B.MSO = 'COMCAST';
                        
UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET READY_FOR_DELIVERY = CHECKED - DELIVERED - UNDELIVERABLE;
                        
UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET A.RECEIVED_COUNT = B.CNT FROM
(SELECT UPPER(PROJECT_NAME) PROJECT_NAME,UPPER(NEW_PUBLISH_NAME) NEW_PUBLISH_NAME,COUNT(*) AS CNT FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_SMB" GROUP BY 1,2
) B WHERE A.PROJECT_NAME LIKE '%' ||B.PROJECT_NAME||'%'
AND A.SERVICE_PROVIDER = B.NEW_PUBLISH_NAME; 

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET A.RECEIVED_COUNT = B.CNT FROM
(SELECT UPPER(PROJECT_NAME) PROJECT_NAME,UPPER(NEW_PUBLISH_NAME) NEW_PUBLISH_NAME,COUNT(*) AS CNT FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI" GROUP BY 1,2
) B WHERE A.PROJECT_NAME LIKE '%' ||B.PROJECT_NAME||'%'
AND A.SERVICE_PROVIDER = B.NEW_PUBLISH_NAME; 

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET A.RECEIVED_COUNT = B.CNT FROM
(SELECT UPPER(PROJECT_NAME) PROJECT_NAME,UPPER(NEW_PUBLISH_NAME) NEW_PUBLISH_NAME,COUNT(*) AS CNT FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI_CB" GROUP BY 1,2
) B WHERE A.PROJECT_NAME LIKE '%' ||B.PROJECT_NAME||'%'
AND A.SERVICE_PROVIDER = B.NEW_PUBLISH_NAME; 