CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP" (
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
CASE WHEN UPPER(FIBER_TV_PROVIDER) IN ('UVERSE-TV', 'PRISM-TV', 'FIOS-TV', 'FIOS TV', 'VANTAGE TV', 'SIGNATURE TV') THEN 1
       ELSE 0
  END AS FIBER_TV,
CASE WHEN UPPER(FIBER_PHONE_PROVIDER) IN ('FIOS-PHONE', 'FVC', 'UVERSE-PHONE') THEN 1
       ELSE 0
  END AS FIBER_PHONE, 
CASE WHEN MAX_SPEED IS NOT NULL AND MAX_SPEED > 0 THEN 1
       ELSE 0
       END AS RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CASE
     WHEN MOST_RECENT_CHECK_DATE IS NULL 
     THEN LAST_CHECK_DATE
     ELSE MOST_RECENT_CHECK_DATE
  END AS CHECK_DATE,
  OPEN_DATE
FROM "V4_CTELL"."PUBLISH"."HKEY_CURRENT"
  WHERE MSO='COX'
  AND MAX_SPEED > 0
  AND (CLOSE_DATE IS NULL);
  
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_1"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  CHECK_DATE DATE,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_1" (
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX_SPEED,
  UPLOAD_MAX_SPEED,
  HOMESRUN,
  FIBER_TV,
  FIBER_PHONE,
  CHECK_DATE
)
SELECT
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX(MAX_SPEED) AS MAX_SPEED,
  MAX(UPLOAD_MAX_SPEED) AS UPLOAD_MAX_SPEED,
  SUM(RESULTCOUNT) AS HOMESRUN,
  SUM(FIBER_TV) AS FIBER_TV,
  SUM(FIBER_PHONE) AS FIBER_PHONE,
  MAX(CHECK_DATE) AS CHECK_DATE
FROM "V4_CTELL"."TEST"."HKEY_TEMP"
GROUP BY MSO, ZIP5, ZIP4, PROVIDER_NAME;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_2"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
);

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_2" (
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX_SPEED,
  COUNT_MAX_SPEED,
  MIN_DATE_MAXSPEED,
  MAX_DATE_MAXSPEED
)
SELECT 
  A.MSO,
  A.ZIP5,
  A.ZIP4,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  COUNT(A.ZIP4) AS COUNT_MAXSPEED,
  MIN(A.OPEN_DATE) AS MIN_DATE_MAXSPEED,
  MAX(A.CHECK_DATE) AS MAX_DATE_MAXSPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP" A
JOIN "V4_CTELL"."TEST"."HKEY_TEMP_1" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.MAX_SPEED GROUP BY A.MSO,A.ZIP5, A.ZIP4, A.PROVIDER_NAME, A.MAX_SPEED;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_3"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_3" (
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
MAX_SPEED,
UPLOAD_MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED)
  SELECT 
  A.MSO,
  A.ZIP5,
  A.ZIP4,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.UPLOAD_MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  B.COUNT_MAX_SPEED,
  B.MIN_DATE_MAXSPEED,
  B.MAX_DATE_MAXSPEED
  FROM "V4_CTELL"."TEST"."HKEY_TEMP_1" AS A
LEFT JOIN "V4_CTELL"."TEST"."HKEY_TEMP_2" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.MAX_SPEED;

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COX_ZIP9ASSIGN"
(ZIP5 VARCHAR(16777216),
ZIP4 VARCHAR(16777216),
H1 VARCHAR(16777216),
H2 VARCHAR(16777216),
H3 VARCHAR(16777216),
H4 VARCHAR(16777216),
H5 VARCHAR(16777216),
H6 VARCHAR(16777216),
SCIERA_CB VARCHAR(16777216),
SCIERA_DMA VARCHAR(16777216),
STATE VARCHAR(16777216),
COUNTY VARCHAR(16777216),
HOMES VARCHAR(16777216),
SFU VARCHAR(16777216),
MDU VARCHAR(16777216),
OTHER VARCHAR(16777216));

COPY INTO "V4_CTELL"."TEST"."COX_ZIP9ASSIGN" (ZIP5,ZIP4,H1,H2,H3,H4,H5,H6,SCIERA_CB,SCIERA_DMA,STATE,COUNTY,HOMES,SFU,MDU,OTHER) FROM (SELECT T.$1,T.$2,T.$3,T.$4,T.$5,T.$6,T.$7,T.$8,T.$9,T.$10,T.$11,T.$12,T.$13,T.$14,T.$15,T.$16, FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/cox/resource/zip9_assignment_combined.bz2/' T) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),ENCODING = 'ISO-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;  

CREATE OR REPLACE TABLE "V4_CTELL"."ROLLUPS"."ZIP9_ROLLUP"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  HOMES VARCHAR(16777216),
  SFU VARCHAR(16777216),
  MDU VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE,
  H1 VARCHAR(16777216),
  H2 VARCHAR(16777216),
  H3 VARCHAR(16777216),
  H4 VARCHAR(16777216),
  H5 VARCHAR(16777216),
  H6 VARCHAR(16777216),
  SCIERA_DMA VARCHAR(16777216),
  UPLOAD_MAX_SPEED FLOAT
);

INSERT INTO "V4_CTELL"."ROLLUPS"."ZIP9_ROLLUP" (
MSO,
ZIP5,
ZIP4,
HOMES,
SFU,
MDU,
PROVIDER_NAME,
MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED,
H1,
H2,
H3,
H4,
H5,
H6,
SCIERA_DMA,
UPLOAD_MAX_SPEED)
SELECT 
A.MSO,
  A.ZIP5,
  A.ZIP4,
  B.HOMES,
  B.SFU,
  B.MDU,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  A.COUNT_MAX_SPEED,
  A.MIN_DATE_MAXSPEED,
  A.MAX_DATE_MAXSPEED,
  B.H1,
  B.H2,
  B.H3,
  B.H4,
  B.H5,
  B.H6,
  B.SCIERA_DMA,
  A.UPLOAD_MAX_SPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP_3" A
LEFT OUTER JOIN "V4_CTELL"."TEST"."COX_ZIP9ASSIGN" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4;  

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP" (
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
CASE WHEN UPPER(FIBER_TV_PROVIDER) IN ('UVERSE-TV', 'PRISM-TV', 'FIOS-TV', 'FIOS TV', 'VANTAGE TV', 'SIGNATURE TV') THEN 1
       ELSE 0
  END AS FIBER_TV,
CASE WHEN UPPER(FIBER_PHONE_PROVIDER) IN ('FIOS-PHONE', 'FVC', 'UVERSE-PHONE') THEN 1
       ELSE 0
  END AS FIBER_PHONE, 
CASE WHEN MAX_SPEED IS NOT NULL AND MAX_SPEED > 0 THEN 1
       ELSE 0
       END AS RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CASE
     WHEN MOST_RECENT_CHECK_DATE IS NULL 
     THEN LAST_CHECK_DATE
     ELSE MOST_RECENT_CHECK_DATE
  END AS CHECK_DATE,
  OPEN_DATE
FROM "V4_CTELL"."PUBLISH"."HKEY_CURRENT"
  WHERE MSO='COMCAST'
  AND MAX_SPEED > 0
  AND (CLOSE_DATE IS NULL);
  
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_1"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  CHECK_DATE DATE,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_1" (
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX_SPEED,
  UPLOAD_MAX_SPEED,
  HOMESRUN,
  FIBER_TV,
  FIBER_PHONE,
  CHECK_DATE
)
SELECT
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX(MAX_SPEED) AS MAX_SPEED,
  MAX(UPLOAD_MAX_SPEED) AS UPLOAD_MAX_SPEED,
  SUM(RESULTCOUNT) AS HOMESRUN,
  SUM(FIBER_TV) AS FIBER_TV,
  SUM(FIBER_PHONE) AS FIBER_PHONE,
  MAX(CHECK_DATE) AS CHECK_DATE
FROM "V4_CTELL"."TEST"."HKEY_TEMP"
GROUP BY MSO, ZIP5, ZIP4, PROVIDER_NAME;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_2"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
);

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_2" (
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX_SPEED,
  COUNT_MAX_SPEED,
  MIN_DATE_MAXSPEED,
  MAX_DATE_MAXSPEED
)
SELECT 
  A.MSO,
  A.ZIP5,
  A.ZIP4,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  COUNT(A.ZIP4) AS COUNT_MAXSPEED,
  MIN(A.OPEN_DATE) AS MIN_DATE_MAXSPEED,
  MAX(A.CHECK_DATE) AS MAX_DATE_MAXSPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP" A
JOIN "V4_CTELL"."TEST"."HKEY_TEMP_1" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.MAX_SPEED GROUP BY A.MSO,A.ZIP5, A.ZIP4, A.PROVIDER_NAME, A.MAX_SPEED;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_3"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_3" (
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
MAX_SPEED,
UPLOAD_MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED)
  SELECT 
  A.MSO,
  A.ZIP5,
  A.ZIP4,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.UPLOAD_MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  B.COUNT_MAX_SPEED,
  B.MIN_DATE_MAXSPEED,
  B.MAX_DATE_MAXSPEED
  FROM "V4_CTELL"."TEST"."HKEY_TEMP_1" AS A
LEFT JOIN "V4_CTELL"."TEST"."HKEY_TEMP_2" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.MAX_SPEED;

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COMCAST_ZIP9ASSIGN"
(ZIP5 VARCHAR(16777216),
ZIP4 VARCHAR(16777216),
H1 VARCHAR(16777216),
H2 VARCHAR(16777216),
H3 VARCHAR(16777216),
H4 VARCHAR(16777216),
H5 VARCHAR(16777216),
H6 VARCHAR(16777216),
SCIERA_CB VARCHAR(16777216),
SCIERA_DMA VARCHAR(16777216),
STATE VARCHAR(16777216),
COUNTY VARCHAR(16777216),
HOMES VARCHAR(16777216),
SFU VARCHAR(16777216),
MDU VARCHAR(16777216),
OTHER VARCHAR(16777216));

COPY INTO "V4_CTELL"."TEST"."COMCAST_ZIP9ASSIGN" (ZIP5,ZIP4,H1,H2,H3,H4,H5,H6,SCIERA_CB,SCIERA_DMA,STATE,COUNTY,HOMES,SFU,MDU,OTHER) FROM (SELECT T.$1,T.$2,T.$3,T.$4,T.$5,T.$6,T.$7,T.$8,T.$9,T.$10,T.$11,T.$12,T.$13,T.$14,T.$15,T.$16, FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/comcast/resource/zip9_assignment_combined.bz2/' T) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),ENCODING = 'ISO-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;  

INSERT INTO "V4_CTELL"."ROLLUPS"."ZIP9_ROLLUP" (
MSO,
ZIP5,
ZIP4,
HOMES,
SFU,
MDU,
PROVIDER_NAME,
MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED,
H1,
H2,
H3,
H4,
H5,
H6,
SCIERA_DMA,
UPLOAD_MAX_SPEED)
SELECT 
A.MSO,
  A.ZIP5,
  A.ZIP4,
  B.HOMES,
  B.SFU,
  B.MDU,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  A.COUNT_MAX_SPEED,
  A.MIN_DATE_MAXSPEED,
  A.MAX_DATE_MAXSPEED,
  B.H1,
  B.H2,
  B.H3,
  B.H4,
  B.H5,
  B.H6,
  B.SCIERA_DMA,
  A.UPLOAD_MAX_SPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP_3" A
LEFT OUTER JOIN "V4_CTELL"."TEST"."COMCAST_ZIP9ASSIGN" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.MSO='COMCAST';   

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP" (
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
CASE WHEN UPPER(FIBER_TV_PROVIDER) IN ('UVERSE-TV', 'PRISM-TV', 'FIOS-TV', 'FIOS TV', 'VANTAGE TV', 'SIGNATURE TV') THEN 1
       ELSE 0
  END AS FIBER_TV,
CASE WHEN UPPER(FIBER_PHONE_PROVIDER) IN ('FIOS-PHONE', 'FVC', 'UVERSE-PHONE') THEN 1
       ELSE 0
  END AS FIBER_PHONE, 
CASE WHEN MAX_SPEED IS NOT NULL AND MAX_SPEED > 0 THEN 1
       ELSE 0
       END AS RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CASE
     WHEN MOST_RECENT_CHECK_DATE IS NULL 
     THEN LAST_CHECK_DATE
     ELSE MOST_RECENT_CHECK_DATE
  END AS CHECK_DATE,
  OPEN_DATE
FROM "V4_CTELL"."PUBLISH"."HKEY_CURRENT"
  WHERE MSO='CHARTER'
  AND MAX_SPEED > 0
  AND (CLOSE_DATE IS NULL);
  
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_1"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  CHECK_DATE DATE,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_1" (
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX_SPEED,
  UPLOAD_MAX_SPEED,
  HOMESRUN,
  FIBER_TV,
  FIBER_PHONE,
  CHECK_DATE
)
SELECT
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX(MAX_SPEED) AS MAX_SPEED,
  MAX(UPLOAD_MAX_SPEED) AS UPLOAD_MAX_SPEED,
  SUM(RESULTCOUNT) AS HOMESRUN,
  SUM(FIBER_TV) AS FIBER_TV,
  SUM(FIBER_PHONE) AS FIBER_PHONE,
  MAX(CHECK_DATE) AS CHECK_DATE
FROM "V4_CTELL"."TEST"."HKEY_TEMP"
GROUP BY MSO, ZIP5, ZIP4, PROVIDER_NAME;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_2"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
);

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_2" (
  MSO,
  ZIP5,
  ZIP4,
  PROVIDER_NAME,
  MAX_SPEED,
  COUNT_MAX_SPEED,
  MIN_DATE_MAXSPEED,
  MAX_DATE_MAXSPEED
)
SELECT 
  A.MSO,
  A.ZIP5,
  A.ZIP4,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  COUNT(A.ZIP4) AS COUNT_MAXSPEED,
  MIN(A.OPEN_DATE) AS MIN_DATE_MAXSPEED,
  MAX(A.CHECK_DATE) AS MAX_DATE_MAXSPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP" A
JOIN "V4_CTELL"."TEST"."HKEY_TEMP_1" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.MAX_SPEED GROUP BY A.MSO,A.ZIP5, A.ZIP4, A.PROVIDER_NAME, A.MAX_SPEED;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_3"(
  MSO VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_3" (
MSO,
ZIP5,
ZIP4,
PROVIDER_NAME,
MAX_SPEED,
UPLOAD_MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED)
  SELECT 
  A.MSO,
  A.ZIP5,
  A.ZIP4,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.UPLOAD_MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  B.COUNT_MAX_SPEED,
  B.MIN_DATE_MAXSPEED,
  B.MAX_DATE_MAXSPEED
  FROM "V4_CTELL"."TEST"."HKEY_TEMP_1" AS A
LEFT JOIN "V4_CTELL"."TEST"."HKEY_TEMP_2" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.MAX_SPEED;

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."CHARTER_ZIP9ASSIGN"
(ZIP5 VARCHAR(16777216),
ZIP4 VARCHAR(16777216),
H1 VARCHAR(16777216),
H2 VARCHAR(16777216),
H3 VARCHAR(16777216),
H4 VARCHAR(16777216),
H5 VARCHAR(16777216),
H6 VARCHAR(16777216),
SCIERA_CB VARCHAR(16777216),
SCIERA_DMA VARCHAR(16777216),
STATE VARCHAR(16777216),
COUNTY VARCHAR(16777216),
HOMES VARCHAR(16777216),
SFU VARCHAR(16777216),
MDU VARCHAR(16777216),
OTHER VARCHAR(16777216));

COPY INTO "V4_CTELL"."TEST"."CHARTER_ZIP9ASSIGN" (ZIP5,ZIP4,H1,H2,H3,H4,H5,H6,SCIERA_CB,SCIERA_DMA,STATE,COUNTY,HOMES,SFU,MDU,OTHER) FROM (SELECT T.$1,T.$2,T.$3,T.$4,T.$5,T.$6,T.$7,T.$8,T.$9,T.$10,T.$11,T.$12,T.$13,T.$14,T.$15,T.$16, FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/charter/resource/zip9_assignment_combined.bz2/' T) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),ENCODING = 'ISO-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;  

INSERT INTO "V4_CTELL"."ROLLUPS"."ZIP9_ROLLUP" (
MSO,
ZIP5,
ZIP4,
HOMES,
SFU,
MDU,
PROVIDER_NAME,
MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED,
H1,
H2,
H3,
H4,
H5,
H6,
SCIERA_DMA,
UPLOAD_MAX_SPEED)
SELECT 
A.MSO,
  A.ZIP5,
  A.ZIP4,
  B.HOMES,
  B.SFU,
  B.MDU,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  A.COUNT_MAX_SPEED,
  A.MIN_DATE_MAXSPEED,
  A.MAX_DATE_MAXSPEED,
  B.H1,
  B.H2,
  B.H3,
  B.H4,
  B.H5,
  B.H6,
  B.SCIERA_DMA,
  A.UPLOAD_MAX_SPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP_3" A
LEFT OUTER JOIN "V4_CTELL"."TEST"."CHARTER_ZIP9ASSIGN" AS B
  ON A.ZIP5 = B.ZIP5
  AND A.ZIP4 = B.ZIP4
  AND A.MSO='CHARTER'; 
   

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB"(
  MSO VARCHAR(16777216),
  Fp_Key VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB" (
MSO,
Fp_Key,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
MSO,
fp_key,
ZIP5,
ZIP4,
PROVIDER_NAME,
CASE WHEN UPPER(FIBER_TV_PROVIDER) IN ('UVERSE-TV', 'PRISM-TV', 'FIOS-TV', 'FIOS TV', 'VANTAGE TV', 'YES','SIGNATURE TV') THEN 1
       ELSE 0
  END AS FIBER_TV,
CASE WHEN UPPER(Fiber_Phone_Provider) IN ('Yes','Yes','FIOS-PHONE', 'UVERSE-PHONE') THEN 1
       ELSE 0
  END AS FIBER_PHONE, 
CASE WHEN max_speed IS NOT NULL AND max_speed > 0 THEN 1
       ELSE 0
       END AS RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CASE
     WHEN MOST_RECENT_CHECK_DATE IS NULL 
     THEN LAST_CHECK_DATE
     ELSE Most_Recent_Check_Date
  END AS CHECK_DATE,
  OPEN_DATE
FROM "V4_CTELL"."PUBLISH"."HKEY_CURRENT"
  WHERE MSO='COX'
  AND MAX_SPEED > 0
  AND (CLOSE_DATE IS NULL);
   
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP"(
  MSO VARCHAR(16777216),
  Fp_Key VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 
INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP" (
MSO,
Fp_Key,
SCIERA_CB,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
A.MSO,
A.fp_key,
B.SCIERA_CB,
A.ZIP5,
A.ZIP4,
A.PROVIDER_NAME,
A.FIBER_TV,
A.FIBER_PHONE, 
A.RESULTCOUNT,
A.MAX_SPEED,
A.UPLOAD_MAX_SPEED,
A.CHECK_DATE,
A.OPEN_DATE
from "V4_CTELL"."TEST"."HKEY_TEMP_CB" A JOIN "MSO"."V3_COX_RESOURCE"."FP" B ON A.FP_KEY=B.FP_KEY; 

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_1"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" (
  MSO,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX_SPEED,
  upload_max_speed,
  HOMESRUN,
  FIBER_TV,
  FIBER_PHONE,
  CHECK_DATE,
  OPEN_DATE
)
SELECT
  mso,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX(MAX_SPEED) AS MAX_SPEED,
  MAX(UPLOAD_MAX_SPEED) AS UPLOAD_MAX_SPEED,
  SUM(RESULTCOUNT) AS HOMESRUN,
  SUM(FIBER_TV) AS FIBER_TV,
  SUM(FIBER_PHONE) AS FIBER_PHONE,
  MAX(CHECK_DATE) AS CHECK_DATE,
  MAX(OPEN_DATE) AS OPEN_DATE
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP"
GROUP BY mso,SCIERA_CB,PROVIDER_NAME;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_2"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
);

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_2" (
  MSO,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX_SPEED,
  COUNT_MAX_SPEED,
  MIN_DATE_MAXSPEED,
  MAX_DATE_MAXSPEED
)
SELECT 
  A.MSO,
  A.SCIERA_CB,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  COUNT(a.SCIERA_CB) AS count_maxspeed,
  MIN(A.check_date) AS min_date_maxspeed,
  MAX(A.check_date) AS max_date_maxspeed
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP" a
JOIN "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" AS b
 ON A.SCIERA_cb = B.SCIERA_cb
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.max_speed GROUP BY A.MSO,A.SCIERA_CB, A.PROVIDER_NAME,A.max_speed;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_3"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_3" (
MSO,
SCIERA_CB,
PROVIDER_NAME,
MAX_SPEED,
UPLOAD_MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED)
  SELECT 
  A.MSO,
  A.SCIERA_CB,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.UPLOAD_MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  B.COUNT_MAX_SPEED,
  B.MIN_DATE_MAXSPEED,
  B.MAX_DATE_MAXSPEED
  FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" AS A
LEFT JOIN "V4_CTELL"."TEST"."HKEY_TEMP_CB_2" AS B
  ON A.SCIERA_CB = B.SCIERA_CB
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.max_speed = B.max_speed; 

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COX_CBASSIGN"
(cb_assign VARCHAR(16777216),
H1 VARCHAR(16777216),
H2 VARCHAR(16777216),
H3 VARCHAR(16777216),
H4 VARCHAR(16777216),
H5 VARCHAR(16777216),
H6 VARCHAR(16777216),
SCIERA_DMA VARCHAR(16777216),
STATE VARCHAR(16777216),
COUNTY VARCHAR(16777216),
homes VARCHAR(16777216),
zipCount VARCHAR(16777216),
sfu VARCHAR(16777216),
mdu VARCHAR(16777216),
other VARCHAR(16777216));

COPY INTO "V4_CTELL"."TEST"."COX_CBASSIGN" (cb_assign,H1,H2,H3,H4,H5,H6,SCIERA_DMA,STATE,COUNTY,homes,zipCount,sfu,mdu,other) FROM (SELECT t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15 FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/cox/resource/cb_assignment_combined.bz2/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

CREATE OR REPLACE TABLE "V4_CTELL"."ROLLUPS"."CB_ROLLUP"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  zip9Count VARCHAR(16777216),
  homes VARCHAR(16777216),
  sfu VARCHAR(16777216),
  mdu VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE,
  H1 VARCHAR(16777216),
  H2 VARCHAR(16777216),
  H3 VARCHAR(16777216),
  H4 VARCHAR(16777216),
  H5 VARCHAR(16777216),
  H6 VARCHAR(16777216),
  SCIERA_DMA VARCHAR(16777216),
  UPLOAD_MAX_SPEED FLOAT
);

INSERT INTO "V4_CTELL"."ROLLUPS"."CB_ROLLUP" (
MSO,
SCIERA_CB,
zip9Count,
homes,
sfu,
mdu,
PROVIDER_NAME,
MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED,
H1,
H2,
H3,
H4,
H5,
H6,
SCIERA_DMA,
UPLOAD_MAX_SPEED)
SELECT 
A.MSO,
A.SCIERA_CB,
B.zipCount,
B.homes,
B.sfu,
B.mdu,
A.PROVIDER_NAME,
A.MAX_SPEED,
A.HOMESRUN,
A.FIBER_TV,
A.FIBER_PHONE,
A.CHECK_DATE,
A.COUNT_MAX_SPEED,
A.MIN_DATE_MAXSPEED,
A.MAX_DATE_MAXSPEED,
B.H1,
B.H2,
B.H3,
B.H4,
B.H5,
B.H6,
B.SCIERA_DMA,
A.UPLOAD_MAX_SPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_3" A
LEFT OUTER JOIN "V4_CTELL"."TEST"."COX_CBASSIGN" AS B
  ON A.MSO='COX'
  AND A.SCIERA_CB = B.cb_assign;
  
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB"(
  MSO VARCHAR(16777216),
  Fp_Key VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB" (
MSO,
Fp_Key,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
MSO,
fp_key,
ZIP5,
ZIP4,
PROVIDER_NAME,
CASE WHEN UPPER(FIBER_TV_PROVIDER) IN ('UVERSE-TV', 'PRISM-TV', 'FIOS-TV', 'FIOS TV', 'VANTAGE TV', 'YES','SIGNATURE TV') THEN 1
       ELSE 0
  END AS FIBER_TV,
CASE WHEN UPPER(Fiber_Phone_Provider) IN ('Yes','Yes','FIOS-PHONE', 'UVERSE-PHONE') THEN 1
       ELSE 0
  END AS FIBER_PHONE, 
CASE WHEN max_speed IS NOT NULL AND max_speed > 0 THEN 1
       ELSE 0
       END AS RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CASE
     WHEN MOST_RECENT_CHECK_DATE IS NULL 
     THEN LAST_CHECK_DATE
     ELSE Most_Recent_Check_Date
  END AS CHECK_DATE,
  OPEN_DATE
FROM "V4_CTELL"."PUBLISH"."HKEY_CURRENT"
  WHERE MSO='COMCAST'
  AND MAX_SPEED > 0
  AND (CLOSE_DATE IS NULL);
   
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP"(
  MSO VARCHAR(16777216),
  Fp_Key VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 
INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP" (
MSO,
Fp_Key,
SCIERA_CB,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
A.MSO,
A.fp_key,
B.SCIERA_CB,
A.ZIP5,
A.ZIP4,
A.PROVIDER_NAME,
A.FIBER_TV,
A.FIBER_PHONE, 
A.RESULTCOUNT,
A.MAX_SPEED,
A.UPLOAD_MAX_SPEED,
A.CHECK_DATE,
A.OPEN_DATE
from "V4_CTELL"."TEST"."HKEY_TEMP_CB" A JOIN "MSO"."V3_COMCAST_RESOURCE"."FP" B ON A.FP_KEY=B.FP_KEY; 

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_1"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" (
  MSO,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX_SPEED,
  upload_max_speed,
  HOMESRUN,
  FIBER_TV,
  FIBER_PHONE,
  CHECK_DATE,
  OPEN_DATE
)
SELECT
  mso,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX(MAX_SPEED) AS MAX_SPEED,
  MAX(UPLOAD_MAX_SPEED) AS UPLOAD_MAX_SPEED,
  SUM(RESULTCOUNT) AS HOMESRUN,
  SUM(FIBER_TV) AS FIBER_TV,
  SUM(FIBER_PHONE) AS FIBER_PHONE,
  MAX(CHECK_DATE) AS CHECK_DATE,
  MAX(OPEN_DATE) AS OPEN_DATE
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP"
GROUP BY mso,SCIERA_CB,PROVIDER_NAME;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_2"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
);

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_2" (
  MSO,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX_SPEED,
  COUNT_MAX_SPEED,
  MIN_DATE_MAXSPEED,
  MAX_DATE_MAXSPEED
)
SELECT 
  A.MSO,
  A.SCIERA_CB,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  COUNT(a.SCIERA_CB) AS count_maxspeed,
  MIN(A.check_date) AS min_date_maxspeed,
  MAX(A.check_date) AS max_date_maxspeed
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP" a
JOIN "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" AS b
 ON A.SCIERA_cb = B.SCIERA_cb
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.max_speed GROUP BY A.MSO,A.SCIERA_CB, A.PROVIDER_NAME,A.max_speed;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_3"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_3" (
MSO,
SCIERA_CB,
PROVIDER_NAME,
MAX_SPEED,
UPLOAD_MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED)
  SELECT 
  A.MSO,
  A.SCIERA_CB,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.UPLOAD_MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  B.COUNT_MAX_SPEED,
  B.MIN_DATE_MAXSPEED,
  B.MAX_DATE_MAXSPEED
  FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" AS A
LEFT JOIN "V4_CTELL"."TEST"."HKEY_TEMP_CB_2" AS B
  ON A.SCIERA_CB = B.SCIERA_CB
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.max_speed = B.max_speed; 

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COMCAST_CBASSIGN"
(cb_assign VARCHAR(16777216),
H1 VARCHAR(16777216),
H2 VARCHAR(16777216),
H3 VARCHAR(16777216),
H4 VARCHAR(16777216),
H5 VARCHAR(16777216),
H6 VARCHAR(16777216),
SCIERA_DMA VARCHAR(16777216),
STATE VARCHAR(16777216),
COUNTY VARCHAR(16777216),
homes VARCHAR(16777216),
zipCount VARCHAR(16777216),
sfu VARCHAR(16777216),
mdu VARCHAR(16777216),
other VARCHAR(16777216));

COPY INTO "V4_CTELL"."TEST"."COMCAST_CBASSIGN" (cb_assign,H1,H2,H3,H4,H5,H6,SCIERA_DMA,STATE,COUNTY,homes,zipCount,sfu,mdu,other) FROM (SELECT t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15 FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/comcast/resource/cb_assignment_combined.bz2/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;


INSERT INTO "V4_CTELL"."ROLLUPS"."CB_ROLLUP" (
MSO,
SCIERA_CB,
zip9Count,
homes,
sfu,
mdu,
PROVIDER_NAME,
MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED,
H1,
H2,
H3,
H4,
H5,
H6,
SCIERA_DMA,
UPLOAD_MAX_SPEED)
SELECT 
A.MSO,
A.SCIERA_CB,
B.zipCount,
B.homes,
B.sfu,
B.mdu,
A.PROVIDER_NAME,
A.MAX_SPEED,
A.HOMESRUN,
A.FIBER_TV,
A.FIBER_PHONE,
A.CHECK_DATE,
A.COUNT_MAX_SPEED,
A.MIN_DATE_MAXSPEED,
A.MAX_DATE_MAXSPEED,
B.H1,
B.H2,
B.H3,
B.H4,
B.H5,
B.H6,
B.SCIERA_DMA,
A.UPLOAD_MAX_SPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_3" A
LEFT OUTER JOIN "V4_CTELL"."TEST"."COMCAST_CBASSIGN" AS B
  ON A.MSO='COMCAST'
  AND A.SCIERA_CB = B.cb_assign;  

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB"(
  MSO VARCHAR(16777216),
  Fp_Key VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB" (
MSO,
Fp_Key,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
MSO,
fp_key,
ZIP5,
ZIP4,
PROVIDER_NAME,
CASE WHEN UPPER(FIBER_TV_PROVIDER) IN ('UVERSE-TV', 'PRISM-TV', 'FIOS-TV', 'FIOS TV', 'VANTAGE TV', 'YES','SIGNATURE TV') THEN 1
       ELSE 0
  END AS FIBER_TV,
CASE WHEN UPPER(Fiber_Phone_Provider) IN ('Yes','Yes','FIOS-PHONE', 'UVERSE-PHONE') THEN 1
       ELSE 0
  END AS FIBER_PHONE, 
CASE WHEN max_speed IS NOT NULL AND max_speed > 0 THEN 1
       ELSE 0
       END AS RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CASE
     WHEN MOST_RECENT_CHECK_DATE IS NULL 
     THEN LAST_CHECK_DATE
     ELSE Most_Recent_Check_Date
  END AS CHECK_DATE,
  OPEN_DATE
FROM "V4_CTELL"."PUBLISH"."HKEY_CURRENT"
  WHERE MSO='CHARTER'
  AND MAX_SPEED > 0
  AND (CLOSE_DATE IS NULL);
   
CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP"(
  MSO VARCHAR(16777216),
  Fp_Key VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  ZIP5 VARCHAR(16777216),
  ZIP4 VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  FIBER_TV VARCHAR(16777216),
  FIBER_PHONE VARCHAR(16777216),
  RESULTCOUNT FLOAT,
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 
INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP" (
MSO,
Fp_Key,
SCIERA_CB,
ZIP5,
ZIP4,
PROVIDER_NAME,
FIBER_TV,
FIBER_PHONE,
RESULTCOUNT,
MAX_SPEED,
UPLOAD_MAX_SPEED,
CHECK_DATE,
OPEN_DATE
)
SELECT 
A.MSO,
A.fp_key,
B.SCIERA_CB,
A.ZIP5,
A.ZIP4,
A.PROVIDER_NAME,
A.FIBER_TV,
A.FIBER_PHONE, 
A.RESULTCOUNT,
A.MAX_SPEED,
A.UPLOAD_MAX_SPEED,
A.CHECK_DATE,
A.OPEN_DATE
from "V4_CTELL"."TEST"."HKEY_TEMP_CB" A JOIN "MSO"."V3_CHARTER_RESOURCE"."FP" B ON A.FP_KEY=B.FP_KEY; 

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_1"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  OPEN_DATE DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" (
  MSO,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX_SPEED,
  upload_max_speed,
  HOMESRUN,
  FIBER_TV,
  FIBER_PHONE,
  CHECK_DATE,
  OPEN_DATE
)
SELECT
  mso,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX(MAX_SPEED) AS MAX_SPEED,
  MAX(UPLOAD_MAX_SPEED) AS UPLOAD_MAX_SPEED,
  SUM(RESULTCOUNT) AS HOMESRUN,
  SUM(FIBER_TV) AS FIBER_TV,
  SUM(FIBER_PHONE) AS FIBER_PHONE,
  MAX(CHECK_DATE) AS CHECK_DATE,
  MAX(OPEN_DATE) AS OPEN_DATE
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP"
GROUP BY mso,SCIERA_CB,PROVIDER_NAME;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_2"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
);

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_2" (
  MSO,
  SCIERA_CB,
  PROVIDER_NAME,
  MAX_SPEED,
  COUNT_MAX_SPEED,
  MIN_DATE_MAXSPEED,
  MAX_DATE_MAXSPEED
)
SELECT 
  A.MSO,
  A.SCIERA_CB,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  COUNT(a.SCIERA_CB) AS count_maxspeed,
  MIN(A.check_date) AS min_date_maxspeed,
  MAX(A.check_date) AS max_date_maxspeed
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_FP" a
JOIN "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" AS b
 ON A.SCIERA_cb = B.SCIERA_cb
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.MAX_SPEED = B.max_speed GROUP BY A.MSO,A.SCIERA_CB, A.PROVIDER_NAME,A.max_speed;

CREATE OR REPLACE TEMP TABLE "V4_CTELL"."TEST"."HKEY_TEMP_CB_3"(
  MSO VARCHAR(16777216),
  SCIERA_CB VARCHAR(16777216),
  PROVIDER_NAME VARCHAR(16777216),
  MAX_SPEED FLOAT,
  UPLOAD_MAX_SPEED FLOAT,
  HOMESRUN FLOAT,
  FIBER_TV FLOAT,
  FIBER_PHONE FLOAT,
  CHECK_DATE DATE,
  COUNT_MAX_SPEED FLOAT,
  MIN_DATE_MAXSPEED DATE,
  MAX_DATE_MAXSPEED DATE
); 

INSERT INTO "V4_CTELL"."TEST"."HKEY_TEMP_CB_3" (
MSO,
SCIERA_CB,
PROVIDER_NAME,
MAX_SPEED,
UPLOAD_MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED)
  SELECT 
  A.MSO,
  A.SCIERA_CB,
  A.PROVIDER_NAME,
  A.MAX_SPEED,
  A.UPLOAD_MAX_SPEED,
  A.HOMESRUN,
  A.FIBER_TV,
  A.FIBER_PHONE,
  A.CHECK_DATE,
  B.COUNT_MAX_SPEED,
  B.MIN_DATE_MAXSPEED,
  B.MAX_DATE_MAXSPEED
  FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_1" AS A
LEFT JOIN "V4_CTELL"."TEST"."HKEY_TEMP_CB_2" AS B
  ON A.SCIERA_CB = B.SCIERA_CB
  AND A.PROVIDER_NAME = B.PROVIDER_NAME
  AND A.max_speed = B.max_speed; 

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."CHARTER_CBASSIGN"
(cb_assign VARCHAR(16777216),
H1 VARCHAR(16777216),
H2 VARCHAR(16777216),
H3 VARCHAR(16777216),
H4 VARCHAR(16777216),
H5 VARCHAR(16777216),
H6 VARCHAR(16777216),
SCIERA_DMA VARCHAR(16777216),
STATE VARCHAR(16777216),
COUNTY VARCHAR(16777216),
homes VARCHAR(16777216),
zipCount VARCHAR(16777216),
sfu VARCHAR(16777216),
mdu VARCHAR(16777216),
other VARCHAR(16777216));

COPY INTO "V4_CTELL"."TEST"."CHARTER_CBASSIGN" (cb_assign,H1,H2,H3,H4,H5,H6,SCIERA_DMA,STATE,COUNTY,homes,zipCount,sfu,mdu,other) FROM (SELECT t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15 FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/charter/resource/cb_assignment_combined.bz2/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;


INSERT INTO "V4_CTELL"."ROLLUPS"."CB_ROLLUP" (
MSO,
SCIERA_CB,
zip9Count,
homes,
sfu,
mdu,
PROVIDER_NAME,
MAX_SPEED,
HOMESRUN,
FIBER_TV,
FIBER_PHONE,
CHECK_DATE,
COUNT_MAX_SPEED,
MIN_DATE_MAXSPEED,
MAX_DATE_MAXSPEED,
H1,
H2,
H3,
H4,
H5,
H6,
SCIERA_DMA,
UPLOAD_MAX_SPEED)
SELECT 
A.MSO,
A.SCIERA_CB,
B.zipCount,
B.homes,
B.sfu,
B.mdu,
A.PROVIDER_NAME,
A.MAX_SPEED,
A.HOMESRUN,
A.FIBER_TV,
A.FIBER_PHONE,
A.CHECK_DATE,
A.COUNT_MAX_SPEED,
A.MIN_DATE_MAXSPEED,
A.MAX_DATE_MAXSPEED,
B.H1,
B.H2,
B.H3,
B.H4,
B.H5,
B.H6,
B.SCIERA_DMA,
A.UPLOAD_MAX_SPEED
FROM "V4_CTELL"."TEST"."HKEY_TEMP_CB_3" A
LEFT OUTER JOIN "V4_CTELL"."TEST"."CHARTER_CBASSIGN" AS B
  ON A.MSO='CHARTER'
  AND A.SCIERA_CB = B.cb_assign; 

ALTER TABLE  V4_CTELL.ROLLUPS.ZIP9_ROLLUP ADD COLUMN FIBER_FIRST_FOUND VARCHAR(16777216);

ALTER TABLE  V4_CTELL.ROLLUPS.CB_ROLLUP ADD COLUMN FIBER_FIRST_FOUND VARCHAR(16777216);  
  
INSERT INTO V4_CTELL.PROC.NATIONAL_FIBER_FOUND_HOMES (MSO, FP_KEY, PROVIDER_NAME, FIBER_FIRST_FOUND_DATE)  
SELECT A.MSO, A.FP_KEY, A.PROVIDER_NAME, A.FIBER_FIRST_FOUND_DATE  
FROM (SELECT MSO, FP_KEY, PROVIDER_NAME, MIN(open_date) AS FIBER_FIRST_FOUND_DATE FROM V4_CTELL.PROC.HKEY_CURRENT  WHERE max_speed >= 300  GROUP BY MSO, FP_KEY, PROVIDER_NAME) A LEFT JOIN V4_CTELL.PROC.NATIONAL_FIBER_FOUND_HOMES B  
ON A.MSO = B.MSO  AND A.FP_KEY = B.FP_KEY AND A.PROVIDER_NAME = B.PROVIDER_NAME  
WHERE B.FP_KEY IS NULL;

CREATE OR REPLACE TABLE V4_CTELL.ROLLUPS.FIBER_FOUND_ZIP9 AS 
SELECT MSO,ZIP5,ZIP4,PROVIDER_NAME,COUNT(*) AS ROW_COUNT
,MIN(OPEN_DATE) AS FIBER_FIRST_FOUND
FROM V4_CTELL.PROC.HKEY_CURRENT WHERE MAX_SPEED >= 300 
GROUP BY MSO,ZIP5,ZIP4,PROVIDER_NAME;

UPDATE V4_CTELL.ROLLUPS.ZIP9_ROLLUP A SET A.FIBER_FIRST_FOUND=B.FIBER_FIRST_FOUND
FROM V4_CTELL.ROLLUPS.FIBER_FOUND_ZIP9 B WHERE A.MSO=B.MSO AND A.ZIP5=B.ZIP5 AND A.ZIP4=B.ZIP4 AND A.PROVIDER_NAME=B.PROVIDER_NAME;

CREATE OR REPLACE TABLE V4_CTELL.ROLLUPS.FIBER_FOUND_CB AS
SELECT A.MSO,B.SCIERA_CB,A.PROVIDER_NAME,COUNT(*) AS ROW_COUNT,MIN(A.OPEN_DATE) FIBER_FIRST_FOUND 
FROM V4_CTELL.PROC.HKEY_CURRENT A JOIN MSO.V3_COX_RESOURCE.FP B 
ON A.FP_KEY=B.FP_KEY WHERE A.MSO='COX' AND MAX_SPEED >= 300 GROUP BY ALL;

INSERT INTO V4_CTELL.ROLLUPS.FIBER_FOUND_CB
SELECT A.MSO,B.SCIERA_CB,A.PROVIDER_NAME,COUNT(*) AS ROW_COUNT,MIN(A.OPEN_DATE) FIBER_FIRST_FOUND
FROM V4_CTELL.PROC.HKEY_CURRENT A JOIN MSO.V3_COMCAST_RESOURCE.FP B
ON A.FP_KEY=B.FP_KEY WHERE A.MSO='COMCAST' AND MAX_SPEED >= 300 GROUP BY ALL;

INSERT INTO V4_CTELL.ROLLUPS.FIBER_FOUND_CB
SELECT A.MSO,B.SCIERA_CB,A.PROVIDER_NAME,COUNT(*) AS ROW_COUNT,MIN(A.OPEN_DATE) FIBER_FIRST_FOUND
FROM V4_CTELL.PROC.HKEY_CURRENT A JOIN MSO.V3_CHARTER_RESOURCE.FP B
ON A.FP_KEY=B.FP_KEY WHERE A.MSO='CHARTER' AND MAX_SPEED >= 300  GROUP BY ALL;

UPDATE V4_CTELL.ROLLUPS.CB_ROLLUP A 
SET A.FIBER_FIRST_FOUND=B.FIBER_FIRST_FOUND
FROM V4_CTELL.ROLLUPS.FIBER_FOUND_CB B
WHERE A.MSO=B.MSO AND A.SCIERA_CB=B.SCIERA_CB AND A.PROVIDER_NAME=B.PROVIDER_NAME;

ALTER TABLE V4_CTELL.ROLLUPS.ZIP9_ROLLUP
ADD COLUMN ZIP9 VARCHAR DEFAULT NULL,
		   CHECK_DATE_FL DATE DEFAULT NULL;

UPDATE V4_CTELL.ROLLUPS.ZIP9_ROLLUP
SET CHECK_DATE_FL = DATE_TRUNC('MONTH', DATE(CHECK_DATE)),
    ZIP9 = CONCAT(ZIP5,ZIP4);

ALTER TABLE V4_CTELL.ROLLUPS.CB_ROLLUP
ADD COLUMN CHECK_DATE_FL DATE DEFAULT NULL;

UPDATE V4_CTELL.ROLLUPS.CB_ROLLUP
SET CHECK_DATE_FL = DATE_TRUNC('MONTH', DATE(CHECK_DATE));

CREATE OR REPLACE TABLE V4_CTELL.ROLLUPS.ZIP9_FIRST_CHECK_DATE AS
WITH ZIP9_HKEY AS (SELECT MSO, ZIP5, ZIP4, PROVIDER_NAME, COUNT(*) AS ROW_COUNT, MIN(OPEN_DATE) AS FIRST_CHECK_DATE 
FROM V4_CTELL.PROC.HKEY_CURRENT GROUP BY ALL),
ZIP9_WIP AS (SELECT MSO, ZIP5, ZIP4, SERVICENAME AS PROVIDER_NAME, COUNT(*) AS ROW_COUNT, MIN(CHECK_DATE) AS FIRST_CHECK_DATE
FROM V4_CTELL.PROC.WIP_CURRENT WHERE CHECK_DATE IS NOT NULL AND STATUS IN ('AV','NA','NF','CS','NS') GROUP BY ALL)
SELECT MSO,ZIP5,ZIP4,PROVIDER_NAME,MIN(FIRST_CHECK_DATE) AS FIRST_CHECK_DATE FROM (SELECT * FROM ZIP9_HKEY UNION SELECT * FROM ZIP9_WIP) GROUP BY ALL;

CREATE OR REPLACE TABLE V4_CTELL.ROLLUPS.CB_FIRST_CHECK_DATE AS
WITH CB_HKEY AS (SELECT MSO, SCIERA_CB, PROVIDER_NAME, COUNT(*) AS ROW_COUNT, MIN(OPEN_DATE) AS FIRST_CHECK_DATE
FROM V4_CTELL.PROC.HKEY_CURRENT A LEFT JOIN MSO.V3_COMCAST_RESOURCE.FP B ON A.FP_KEY=B.FP_KEY GROUP BY ALL),
CB_WIP AS (SELECT MSO, CB AS SCIERA_CB, SERVICENAME AS PROVIDER_NAME, COUNT(*) AS ROW_COUNT, MIN(CHECK_DATE) AS FIRST_CHECK_DATE
FROM V4_CTELL.PROC.WIP_CURRENT WHERE CHECK_DATE IS NOT NULL AND STATUS IN ('AV','NA','NF','CS','NS') GROUP BY ALL)
SELECT MSO,SCIERA_CB,PROVIDER_NAME,MIN(FIRST_CHECK_DATE) AS FIRST_CHECK_DATE FROM (SELECT * FROM CB_HKEY UNION SELECT * FROM CB_WIP) GROUP BY ALL;

ALTER TABLE V4_CTELL.ROLLUPS.ZIP9_FIRST_CHECK_DATE
ADD COLUMN ZIP9 VARCHAR DEFAULT NULL,
		   FIRST_CHECK_DATE_FL DATE DEFAULT NULL;

UPDATE V4_CTELL.ROLLUPS.ZIP9_FIRST_CHECK_DATE
SET ZIP9 = CONCAT(ZIP5,ZIP4),
	FIRST_CHECK_DATE_FL = DATE_TRUNC('MONTH', DATE(FIRST_CHECK_DATE));

ALTER TABLE V4_CTELL.ROLLUPS.CB_FIRST_CHECK_DATE
ADD COLUMN FIRST_CHECK_DATE_FL DATE DEFAULT NULL;

UPDATE V4_CTELL.ROLLUPS.CB_FIRST_CHECK_DATE
SET FIRST_CHECK_DATE_FL = DATE_TRUNC('MONTH', DATE(FIRST_CHECK_DATE));

CREATE OR REPLACE TABLE V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS AS 
SELECT DISTINCT MSO,ZIP5,ZIP4,CONCAT(ZIP5,ZIP4) AS ZIP9,SERVICENAME AS PROVIDER_NAME,CHECK_DATE,DATE_TRUNC('MONTH', DATE(CHECK_DATE)) AS CHECK_FL_DATE 
FROM V4_CTELL.PROC.WIP_CURRENT WHERE CHECK_DATE IS NOT NULL;

CREATE OR REPLACE TABLE V4_CTELL.ROLLUPS.CB_ALL_CHECKS AS 
SELECT DISTINCT MSO,CB AS SCIERA_CB,SERVICENAME AS PROVIDER_NAME,CHECK_DATE,DATE_TRUNC('MONTH', DATE(CHECK_DATE)) AS CHECK_FL_DATE 
FROM V4_CTELL.PROC.WIP_CURRENT WHERE CHECK_DATE IS NOT NULL;

CREATE OR REPLACE TABLE USCS.USER_DATA.COMCAST_ZIP9ASSIGN AS
SELECT DISTINCT H1, ZIP5 FROM V4_CTELL.TEST.COMCAST_ZIP9ASSIGN;

GRANT ALL PRIVILEGES ON TABLE USCS.USER_DATA.COMCAST_ZIP9ASSIGN TO ROLE AROSTREAM_ROLE;
