
CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" AS
SELECT  IFF(BUDGET_YEAR IS NULL,QUEUE_YEAR,BUDGET_YEAR) AS BUDGET_YEAR, IFF(BUDGET_MONTH IS NULL,QUEUE_MONTH,BUDGET_MONTH) AS BUDGET_MONTH
,BUDGET_MONTH AS BUDGET_MONTH_ACTUAL,BUDGET_YEAR AS BUDGET_YEAR_ACTUAL,QUEUE_YEAR AS QUEUE_YEAR,QUEUE_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,DWELL_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(SERVICENAME) AS PUBLISHNAME,UPPER(STD_NAME) AS STD_NAME,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,'' AS H1,ZIP5,ZIP4,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300 AND STATUS = 'AV',1,0)) AS FIBER_COUNT,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300 AND STATUS = 'AV' AND DELIVERED_YEAR IS NOT NULL,1,0)) AS FIBER_DELIVERED_COUNT,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NF',1,0)) CHECKED_STATUS_NF, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940 AND STATUS = 'AV',1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NF',1,0)) DELIVERED_STATUS_NF, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940 AND STATUS = 'AV',1,0)) AS DELIVERED_GIG_RESULT,SUM(IFF(DELIVERED_DATE IS NOT NULL AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_ALL_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_ALL_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_CHECKED_12M = 'Y' AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_12M_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_CHECKED_12M = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_12M_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_CHECKED_6M = 'Y' AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_6M_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_CHECKED_6M = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_6M_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_CHECKED_3M = 'Y' AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_3M_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_CHECKED_3M = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_3M_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_NEW_AREA = 'Y' AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_NEWAREA_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND ZIP9_NEW_AREA = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >=CHECK_FL_DATE),1,0)) AS ZIP9_NEWAREA_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_ALL_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_ALL_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_CHECKED_12M = 'Y' AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_12M_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_CHECKED_12M = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_12M_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_CHECKED_6M = 'Y' AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_6M_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_CHECKED_6M = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_6M_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_CHECKED_3M = 'Y' AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_3M_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_CHECKED_3M = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_3M_FIBER,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_NEW_AREA = 'Y' AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_NEWAREA_CHECKS,SUM(IFF(DELIVERED_DATE IS NOT NULL AND CB_NEW_AREA = 'Y' AND MAX_SPEED >= 300 AND (FIBER_FIRST_FOUND_CB IS NULL OR FIBER_FIRST_FOUND_CB_FL_DATE >=CHECK_FL_DATE),1,0)) AS CB_NEWAREA_FIBER
FROM V4_CTELL.PROC.WIP_CURRENT WHERE MSO='COX' AND IFNULL(RESULT_SOURCE,'') <>'DP-PIPE'
GROUP BY BUDGET_YEAR,BUDGET_MONTH,BUDGET_MONTH_ACTUAL,BUDGET_YEAR_ACTUAL,QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,DWELL_TYPE,PROJECT_NAME,SERVICENAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5,ZIP4
ORDER BY UNDELIVERABLE DESC ;


UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"A
SET PROJECT_TYPE = 'OTHERS'
WHERE PROJECT_TYPE IS NULL;
 
UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" A
SET PROJECT_TYPE = 'OTHERS'
WHERE PROJECT_NAME = 'D_COX_RESI_2024-03-01_WATCHLIST_20240302';
 
ALTER TABLE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
ADD COLUMN SERVICENAME VARCHAR(16777216) DEFAULT NULL;

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"  
SET SERVICENAME = REPLACE(REPLACE(REPLACE(RTRIM(PUBLISHNAME), '111', ' '),'222',','),'333','.')  
WHERE SERVICENAME IS NULL ;

ALTER TABLE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
ADD COLUMN DELIVERY_NAME  VARCHAR(16777216) DEFAULT NULL;

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" A
SET DELIVERY_NAME = CASE WHEN A.MSO = 'COX' THEN UPPER(B.COX_DELIVERY_NAME) 
                         WHEN A.MSO = 'COMCAST' THEN UPPER(B.COMCAST_DELIVERY_NAME) 
                         WHEN A.MSO IN ('CHARTER','CHARTER_BUSINESS') THEN UPPER(B.CHARTER_DELIVERY_NAME)
                         ELSE NULL END
FROM  "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B
WHERE A.PUBLISHNAME = B.PROVIDER_NAME;  

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" A
SET DELIVERY_NAME =  STD_NAME                         
WHERE DELIVERY_NAME IS NULL;


UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" A
SET DELIVERY_NAME =  SERVICENAME                         
WHERE DELIVERY_NAME IS NULL;

ALTER TABLE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
ADD COLUMN READY_FOR_DELIVERY VARCHAR(16777216) DEFAULT NULL;

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"A
SET READY_FOR_DELIVERY = CHECKED - DELIVERED - UNDELIVERABLE;
  
ALTER TABLE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
ADD SOW VARCHAR(16777216) DEFAULT NULL, DMA VARCHAR;

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'CORPORATE'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISHNAME IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND H1 IN ('NORTHEAST DIVISION','CENTRAL DIVISION');

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'NED'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISHNAME NOT IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND H1 = 'NORTHEAST DIVISION';

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'CENTRAL'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISHNAME NOT IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND H1 = 'CENTRAL DIVISION';

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'WEST'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') 
AND H1 = 'WEST DIVISION';

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" A
SET A.DMA = B.DMA
FROM V4_CTELL.TEST.DMA_FOR_ZIP9_COX B
WHERE A.ZIP5||A.ZIP4 = B.ZIP9 AND B.RNK = 1;

ALTER TABLE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();


----


CREATE OR REPLACE TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA AS SELECT * FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_20250430;

ALTER TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA ADD COLUMN DMA VARCHAR;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A 
SET A.DMA = B.DMA
FROM V4_CTELL.TEST.DMA_FOR_ZIP9_COX B
WHERE A.ZIP9 = B.ZIP9 AND B.RNK = 1;

----

CREATE OR REPLACE TABLE V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA AS
SELECT CAST('2025' AS INT) AS BUDGET_YEAR, CAST('4' AS INT) AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2025-04-23';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2025 AS BUDGET_YEAR,03 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2025-04-02';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2025 AS BUDGET_YEAR,02 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2025-03-05';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2025 AS BUDGET_YEAR,01 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2025-03-05';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,12 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2025-01-08';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,11 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-12-04';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,10 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-11-06';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,9 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-10-09';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,8 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-09-04';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,7 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-08-07';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,6 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-07-03';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,5 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-06-05';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,4 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-05-08';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,3 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-04-03';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,2 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-03-06';

INSERT INTO V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
SELECT 2024 AS BUDGET_YEAR,1 AS BUDGET_MONTH,A.*,B.FP_KEY,B.SCIERA_ZIP5,B.SCIERA_ZIP4
FROM V4_CTELL.DELIVERIES.COX_DELIVERY A, MSO.V3_COX_RESOURCE.FP B
WHERE A.HOUSE_KEY=B.H5 AND DELETE_DATE IS NULL AND DELIVERED_DATE='2024-02-07';

ALTER TABLE V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA
ADD COLUMN DMA VARCHAR;

UPDATE V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA A
SET A.DMA = B.DMA
FROM V4_CTELL.TEST.DMA_FOR_ZIP9_COX B
WHERE A.SCIERA_ZIP5||A.SCIERA_ZIP4 = B.ZIP9;

----

CREATE OR REPLACE TABLE V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA AS
SELECT BUDGET_YEAR,BUDGET_MONTH,FP_KEY,HOUSE_KEY,SCIERA_ZIP5,SCIERA_ZIP4,UPPER(IFNULL(DMA,'')) AS DMA,ILEC_NAME AS PROVIDER, ILEC_MAX_SPEED AS MAX_SPEED, DATE_CHECKED, DELIVERED_DATE FROM V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA;

INSERT INTO V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA
SELECT BUDGET_YEAR,BUDGET_MONTH,FP_KEY,HOUSE_KEY,SCIERA_ZIP5,SCIERA_ZIP4,UPPER(IFNULL(DMA,'')) AS DMA,OB1_NAME AS PROVIDER, OB1_MAX_SPEED AS MAX_SPEED,'', DELIVERED_DATE FROM V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA WHERE OB1_NAME != '';

INSERT INTO V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA
SELECT BUDGET_YEAR,BUDGET_MONTH,FP_KEY,HOUSE_KEY,SCIERA_ZIP5,SCIERA_ZIP4,UPPER(IFNULL(DMA,'')) AS DMA,OB2_NAME AS PROVIDER, OB2_MAX_SPEED AS MAX_SPEED,'', DELIVERED_DATE FROM V4_CTELL.TEST.COX_DELIVERY_TEMP_BY_DMA WHERE OB2_NAME != '';

----


CREATE OR REPLACE TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,IFNULL(H1,'') AS H1,UPPER(IFNULL(DMA,'')) AS DMA,SOW,PUBLISHNAME FROM "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS" GROUP BY ALL;

ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
ADD COLUMN BUDGET_TYPE  VARCHAR(16777216) DEFAULT NULL,
SERVICENAME  VARCHAR(16777216) DEFAULT NULL,
FIBER_COUNT_NQ  NUMBER(38,0) DEFAULT NULL,
FIBER_COUNT_WL  NUMBER(38,0) DEFAULT NULL,
FIBER_COUNT_BL  NUMBER(38,0) DEFAULT NULL,
FIBER_COUNT  NUMBER(38,0) DEFAULT NULL,
QUEUED_NQ  NUMBER(38,0) DEFAULT NULL,
QUEUED_WL  NUMBER(38,0) DEFAULT NULL,
QUEUED_BL  NUMBER(38,0) DEFAULT NULL,
QUEUED  NUMBER(38,0) DEFAULT NULL,
CHECKED_NQ  NUMBER(38,0) DEFAULT NULL,
CHECKED_WL  NUMBER(38,0) DEFAULT NULL,
CHECKED_BL  NUMBER(38,0) DEFAULT NULL,
CHECKED  NUMBER(38,0) DEFAULT NULL,
DELIVERED_NQ  NUMBER(38,0) DEFAULT NULL,
DELIVERED_WL  NUMBER(38,0) DEFAULT NULL,
DELIVERED_BL  NUMBER(38,0) DEFAULT NULL,
DELIVERED  NUMBER(38,0) DEFAULT NULL,
FIBER_GROWTH_ZIP9_ALL_FIBER  NUMBER(38,0) DEFAULT NULL,
FIBER_GROWTH_ZIP9_12M_FIBER  NUMBER(38,0) DEFAULT NULL,
FIBER_GROWTH_ZIP9_6M_FIBER  NUMBER(38,0) DEFAULT NULL,
FIBER_GROWTH_ZIP9_3M_FIBER  NUMBER(38,0) DEFAULT NULL,
FIBER_GROWTH_ZIP9_NEWAREA_FIBER  NUMBER(38,0) DEFAULT NULL;


UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A
SET BUDGET_TYPE = CASE WHEN UPPER(PUBLISHNAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISHNAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END,
     SERVICENAME = REPLACE(REPLACE(REPLACE(RTRIM(PUBLISHNAME), '111', ' '),'222',','),'333','.') ;


UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A
SET A.FIBER_COUNT_NQ = B.FIBER_COUNT_NQ,
A.FIBER_COUNT_WL  = B.FIBER_COUNT_WL,
A.FIBER_COUNT_BL  = B.FIBER_COUNT_BL,
A.FIBER_COUNT  = B.FIBER_COUNT,
A.QUEUED_NQ  = B.QUEUED_NQ,
A.QUEUED_WL  = B.QUEUED_WL,
A.QUEUED_BL  = B.QUEUED_BL,
A.QUEUED  = B.QUEUED,
A.CHECKED_NQ  = B.CHECKED_NQ,
A.CHECKED_WL  = B.CHECKED_WL,
A.CHECKED_BL  = B.CHECKED_BL,
A.CHECKED  = B.CHECKED,
A.DELIVERED_NQ  = B.DELIVERED_NQ,
A.DELIVERED_WL  = B.DELIVERED_WL,
A.DELIVERED_BL  = B.DELIVERED_BL,
A.DELIVERED  = B.DELIVERED
FROM
(SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,SOW,UPPER(IFNULL(DMA,'')) AS DMA,
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',FIBER_COUNT,0)) AS INT) FIBER_COUNT_NQ,
CAST(SUM(IFF(PROJECT_TYPE= 'WL',FIBER_COUNT,0)) AS INT) FIBER_COUNT_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',FIBER_COUNT,0)) AS INT) FIBER_COUNT_BL,
CAST(SUM(FIBER_COUNT) AS INT) FIBER_COUNT,
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',QUEUED,0)) AS INT) QUEUED_NQ,
CAST(SUM(IFF(PROJECT_TYPE= 'WL',QUEUED,0)) AS INT) QUEUED_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',QUEUED,0)) AS INT) QUEUED_BL,
CAST(SUM(QUEUED) AS INT) QUEUED,
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',CHECKED,0)) AS INT) CHECKED_NQ,
CAST(SUM(IFF(PROJECT_TYPE= 'WL',CHECKED,0)) AS INT) CHECKED_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',CHECKED,0)) AS INT) CHECKED_BL,
CAST(SUM(CHECKED) AS INT) CHECKED,
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',DELIVERED,0)) AS INT) DELIVERED_NQ,
CAST(SUM(IFF(PROJECT_TYPE= 'WL',DELIVERED,0)) AS INT) DELIVERED_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',DELIVERED,0)) AS INT) DELIVERED_BL,
CAST(SUM(DELIVERED) AS INT) DELIVERED
FROM "V4_CTELL"."TEST"."QS_DASHBOARD_ROLLUPS"
GROUP BY ALL
) B
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'') AND A.PUBLISHNAME =B.PUBLISHNAME AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,''));

UPDATE  V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
SET FIBER_COUNT_NQ = CASE WHEN  FIBER_COUNT_NQ  IS NULL THEN 0 ELSE FIBER_COUNT_NQ END,
FIBER_COUNT_WL = CASE WHEN  FIBER_COUNT_WL  IS NULL THEN 0 ELSE FIBER_COUNT_WL END,
FIBER_COUNT_BL = CASE WHEN  FIBER_COUNT_BL  IS NULL THEN 0 ELSE FIBER_COUNT_BL END,
FIBER_COUNT = CASE WHEN  FIBER_COUNT  IS NULL THEN 0 ELSE FIBER_COUNT END,
QUEUED_NQ = CASE WHEN  QUEUED_NQ  IS NULL THEN 0 ELSE QUEUED_NQ END,
QUEUED_WL = CASE WHEN  QUEUED_WL  IS NULL THEN 0 ELSE QUEUED_WL END,
QUEUED_BL = CASE WHEN  QUEUED_BL  IS NULL THEN 0 ELSE QUEUED_BL END,
QUEUED = CASE WHEN  QUEUED  IS NULL THEN 0 ELSE QUEUED END,
CHECKED_NQ = CASE WHEN  CHECKED_NQ  IS NULL THEN 0 ELSE CHECKED_NQ END,
CHECKED_WL = CASE WHEN  CHECKED_WL  IS NULL THEN 0 ELSE CHECKED_WL END,
CHECKED_BL = CASE WHEN  CHECKED_BL  IS NULL THEN 0 ELSE CHECKED_BL END,
CHECKED = CASE WHEN  CHECKED  IS NULL THEN 0 ELSE CHECKED END,
DELIVERED_NQ = CASE WHEN  DELIVERED_NQ  IS NULL THEN 0 ELSE DELIVERED_NQ END,
DELIVERED_WL = CASE WHEN  DELIVERED_WL  IS NULL THEN 0 ELSE DELIVERED_WL END,
DELIVERED_BL = CASE WHEN  DELIVERED_BL  IS NULL THEN 0 ELSE DELIVERED_BL END,
DELIVERED = CASE WHEN  DELIVERED  IS NULL THEN 0 ELSE DELIVERED END;


ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
ADD COLUMN DELIVERY_NAME  VARCHAR(16777216) DEFAULT NULL;

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A
SET DELIVERY_NAME = CASE WHEN A.MSO = 'COX' THEN UPPER(B.COX_DELIVERY_NAME)
                         WHEN A.MSO = 'COMCAST' THEN UPPER(B.COMCAST_DELIVERY_NAME)
                         WHEN A.MSO IN ('CHARTER','CHARTER_BUSINESS') THEN UPPER(B.CHARTER_DELIVERY_NAME)
                         ELSE NULL END
FROM  "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B
WHERE A.PUBLISHNAME = B.PROVIDER_NAME;  

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A
SET DELIVERY_NAME =  B.STD_NAME
FROM  "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B
WHERE DELIVERY_NAME IS NULL AND A.PUBLISHNAME = B.PROVIDER_NAME;

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A
SET DELIVERY_NAME =  SERVICENAME                        
WHERE DELIVERY_NAME IS NULL;

ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA SET UPDATED_DATE=CURRENT_DATE();

----

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A
SET FIBER_GROWTH_ZIP9_ALL_FIBER  = (SELECT COUNT(*) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND RN=1  AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE));

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
FIBER_GROWTH_ZIP9_12M_FIBER  = (SELECT SUM(IFF(ZIP9_CHECKED_12_MONTHS='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND RN=1 );

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
FIBER_GROWTH_ZIP9_6M_FIBER  = (SELECT SUM(IFF(ZIP9_CHECKED_6_MONTHS='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND RN=1  AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE));

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
FIBER_GROWTH_ZIP9_3M_FIBER  = (SELECT SUM(IFF(ZIP9_CHECKED_3_MONTHS='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND RN=1  AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE));

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
FIBER_GROWTH_ZIP9_NEWAREA_FIBER  = (SELECT SUM(IFF(ZIP9_NEW_AREA='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND RN=1  AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE));

----

ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
ADD COLUMN
FIBER_ZIP9_COUNT_NQ  NUMBER(38,0) DEFAULT NULL,
FIBER_ZIP9_COUNT_WL  NUMBER(38,0) DEFAULT NULL,
FIBER_ZIP9_COUNT_BL  NUMBER(38,0) DEFAULT NULL
;

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
FIBER_ZIP9_COUNT_NQ  =  FIBER_ZIP9_NQ,
FIBER_ZIP9_COUNT_WL  =  FIBER_ZIP9_WL,
FIBER_ZIP9_COUNT_BL  =  FIBER_ZIP9_BL
FROM (
SELECT  BUDGET_YEAR,BUDGET_MONTH, MSO, DMA, ENGAGEMENT_TYPE, NULL AS SOW, SERVICENAME,
SUM(IFF(PROJECT_TYPE='BL',1,0)) AS FIBER_ZIP9_BL ,
SUM(IFF(PROJECT_TYPE='WL',1,0)) AS FIBER_ZIP9_WL,
SUM(IFF(PROJECT_TYPE='NQ',1,0)) AS FIBER_ZIP9_NQ  
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA WHERE RN=1 AND  (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) GROUP BY ALL ) B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME);

ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
ADD COLUMN
FIBER_EXTRAPOLATED_COUNT_NQ  NUMBER(38,0) DEFAULT NULL,
FIBER_EXTRAPOLATED_COUNT_WL  NUMBER(38,0) DEFAULT NULL,
FIBER_EXTRAPOLATED_COUNT_BL  NUMBER(38,0) DEFAULT NULL
;

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
A.FIBER_EXTRAPOLATED_COUNT_BL = FIBER_EXTRAPOLATED_BL,
A.FIBER_EXTRAPOLATED_COUNT_WL = FIBER_EXTRAPOLATED_WL,
A.FIBER_EXTRAPOLATED_COUNT_NQ = FIBER_EXTRAPOLATED_NQ
FROM (SELECT A.BUDGET_YEAR,A.BUDGET_MONTH, 'COX' AS MSO, 'RESI'  AS ENGAGEMENT_TYPE, UPPER(IFNULL(A.DMA,'')) AS DMA, NULL AS SOW, SERVICENAME,
SUM(IFF(PROJECT_TYPE='BL',1,0)) AS FIBER_EXTRAPOLATED_BL,
SUM(IFF(PROJECT_TYPE='NQ',1,0)) AS FIBER_EXTRAPOLATED_NQ,
SUM(IFF(PROJECT_TYPE='WL',1,0)) AS FIBER_EXTRAPOLATED_WL
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.CLIENT_DELIVERY_NAME=B.PROVIDER AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) GROUP BY ALL) B
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME);

ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
ADD COLUMN
FIBER_EXTRAPOLATED_COUNT_ALL  NUMBER(38,0) DEFAULT NULL,
FIBER_EXTRAPOLATED_COUNT_3M  NUMBER(38,0) DEFAULT NULL,
FIBER_EXTRAPOLATED_COUNT_6M  NUMBER(38,0) DEFAULT NULL,
FIBER_EXTRAPOLATED_COUNT_12M  NUMBER(38,0) DEFAULT NULL,
FIBER_EXTRAPOLATED_COUNT_NEW_AREA  NUMBER(38,0) DEFAULT NULL
;

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET
A.FIBER_EXTRAPOLATED_COUNT_ALL = ALL_FIBER_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_3M = ZIP9_3_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_6M = ZIP9_6_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_12M = ZIP9_12_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_NEW_AREA = ZIP9_NEW_EXTRAPOLATED
FROM (
SELECT A.BUDGET_YEAR,A.BUDGET_MONTH,MSO,ENGAGEMENT_TYPE, UPPER(IFNULL(A.DMA,'')) AS DMA, NULL AS SOW, SERVICENAME,
COUNT(*) AS ALL_FIBER_EXTRAPOLATED
, SUM(IFF(ZIP9_CHECKED_12_MONTHS='Y',1,0)) AS ZIP9_12_EXTRAPOLATED
, SUM(IFF(ZIP9_CHECKED_6_MONTHS='Y',1,0)) AS ZIP9_6_EXTRAPOLATED
, SUM(IFF(ZIP9_CHECKED_3_MONTHS='Y',1,0)) AS ZIP9_3_EXTRAPOLATED
, SUM(IFF(ZIP9_NEW_AREA='Y',1,0)) AS ZIP9_NEW_EXTRAPOLATED
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND UPPER(A.CLIENT_DELIVERY_NAME)=UPPER(B.PROVIDER) AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE)
GROUP BY ALL )B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME);

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
A.FIBER_EXTRAPOLATED_COUNT_BL = FIBER_EXTRAPOLATED_BL,
A.FIBER_EXTRAPOLATED_COUNT_WL = FIBER_EXTRAPOLATED_WL,
A.FIBER_EXTRAPOLATED_COUNT_NQ = FIBER_EXTRAPOLATED_NQ 
FROM (SELECT A.BUDGET_YEAR,A.BUDGET_MONTH, 'COX' AS MSO, 'RESI'  AS ENGAGEMENT_TYPE, NULL AS SOW, SERVICENAME,
SUM(IFF(PROJECT_TYPE='BL',1,0)) AS FIBER_EXTRAPOLATED_BL,
SUM(IFF(PROJECT_TYPE='NQ',1,0)) AS FIBER_EXTRAPOLATED_NQ,
SUM(IFF(PROJECT_TYPE='WL',1,0)) AS FIBER_EXTRAPOLATED_WL 
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B 
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND A.CLIENT_DELIVERY_NAME=B.PROVIDER AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1 
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) GROUP BY ALL) B
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND A.PUBLISHNAME='QUANTUM111FIBER';

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
A.FIBER_EXTRAPOLATED_COUNT_ALL = ALL_FIBER_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_3M = ZIP9_3_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_6M = ZIP9_6_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_12M = ZIP9_12_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_NEW_AREA = ZIP9_NEW_EXTRAPOLATED 
FROM (
SELECT A.BUDGET_YEAR,A.BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,NULL AS SOW, SERVICENAME,
COUNT(*) AS ALL_FIBER_EXTRAPOLATED
, SUM(IFF(ZIP9_CHECKED_12_MONTHS='Y',1,0)) AS ZIP9_12_EXTRAPOLATED 
, SUM(IFF(ZIP9_CHECKED_6_MONTHS='Y',1,0)) AS ZIP9_6_EXTRAPOLATED 
, SUM(IFF(ZIP9_CHECKED_3_MONTHS='Y',1,0)) AS ZIP9_3_EXTRAPOLATED 
, SUM(IFF(ZIP9_NEW_AREA='Y',1,0)) AS ZIP9_NEW_EXTRAPOLATED 
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B 
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND UPPER(A.CLIENT_DELIVERY_NAME)=UPPER(B.PROVIDER) AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1 
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) 
GROUP BY ALL )B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME)AND A.PUBLISHNAME='QUANTUM111FIBER';

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
A.FIBER_EXTRAPOLATED_COUNT_BL = FIBER_EXTRAPOLATED_BL,
A.FIBER_EXTRAPOLATED_COUNT_WL = FIBER_EXTRAPOLATED_WL,
A.FIBER_EXTRAPOLATED_COUNT_NQ = FIBER_EXTRAPOLATED_NQ 
FROM (SELECT A.BUDGET_YEAR,A.BUDGET_MONTH, 'COX' AS MSO, 'RESI'  AS ENGAGEMENT_TYPE, NULL AS SOW, SERVICENAME,
SUM(IFF(PROJECT_TYPE='BL',1,0)) AS FIBER_EXTRAPOLATED_BL,
SUM(IFF(PROJECT_TYPE='NQ',1,0)) AS FIBER_EXTRAPOLATED_NQ,
SUM(IFF(PROJECT_TYPE='WL',1,0)) AS FIBER_EXTRAPOLATED_WL 
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B 
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND A.CLIENT_DELIVERY_NAME=B.PROVIDER AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1 
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) GROUP BY ALL) B
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND A.PUBLISHNAME='HARGRAY111COMMUNICATIONS111GROUP222111INC333';

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
A.FIBER_EXTRAPOLATED_COUNT_ALL = ALL_FIBER_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_3M = ZIP9_3_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_6M = ZIP9_6_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_12M = ZIP9_12_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_NEW_AREA = ZIP9_NEW_EXTRAPOLATED 
FROM (
SELECT A.BUDGET_YEAR,A.BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,NULL AS SOW, SERVICENAME,
COUNT(*) AS ALL_FIBER_EXTRAPOLATED
, SUM(IFF(ZIP9_CHECKED_12_MONTHS='Y',1,0)) AS ZIP9_12_EXTRAPOLATED 
, SUM(IFF(ZIP9_CHECKED_6_MONTHS='Y',1,0)) AS ZIP9_6_EXTRAPOLATED 
, SUM(IFF(ZIP9_CHECKED_3_MONTHS='Y',1,0)) AS ZIP9_3_EXTRAPOLATED 
, SUM(IFF(ZIP9_NEW_AREA='Y',1,0)) AS ZIP9_NEW_EXTRAPOLATED 
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B 
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND UPPER(A.CLIENT_DELIVERY_NAME)=UPPER(B.PROVIDER) AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1 
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) 
GROUP BY ALL )B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME)AND A.PUBLISHNAME='HARGRAY111COMMUNICATIONS111GROUP222111INC333';

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
A.FIBER_EXTRAPOLATED_COUNT_BL = FIBER_EXTRAPOLATED_BL,
A.FIBER_EXTRAPOLATED_COUNT_WL = FIBER_EXTRAPOLATED_WL,
A.FIBER_EXTRAPOLATED_COUNT_NQ = FIBER_EXTRAPOLATED_NQ 
FROM (SELECT A.BUDGET_YEAR,A.BUDGET_MONTH, 'COX' AS MSO, 'RESI'  AS ENGAGEMENT_TYPE, NULL AS SOW, SERVICENAME,
SUM(IFF(PROJECT_TYPE='BL',1,0)) AS FIBER_EXTRAPOLATED_BL,
SUM(IFF(PROJECT_TYPE='NQ',1,0)) AS FIBER_EXTRAPOLATED_NQ,
SUM(IFF(PROJECT_TYPE='WL',1,0)) AS FIBER_EXTRAPOLATED_WL 
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A,V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B 
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND A.CLIENT_DELIVERY_NAME=B.PROVIDER AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1 
AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) GROUP BY ALL) B
WHERE B.BUDGET_YEAR = 2025 AND B.BUDGET_MONTH = 1 AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND A.FIBER_EXTRAPOLATED_COUNT_ALL IS NULL AND A.PUBLISHNAME IN ('BRIGHTSPEED','WTC','AIREBEAM111INTERNET','CITYSIDE FIBER','DESERT INET','GREAT111PLAINS111COMMUNICATIONS','CAMPUS COMMUNICATIONS GROUP','DOBSON111FIBER','TWIN111VALLEY','RITTER111COMMUNICATIONS','BLUESTREAM FIBER','GONETSPEED');


UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
A.FIBER_EXTRAPOLATED_COUNT_ALL = ALL_FIBER_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_3M = ZIP9_3_EXTRAPOLATED,
A.FIBER_EXTRAPOLATED_COUNT_6M = ZIP9_6_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_12M = ZIP9_12_EXTRAPOLATED ,
A.FIBER_EXTRAPOLATED_COUNT_NEW_AREA = ZIP9_NEW_EXTRAPOLATED 
FROM (
SELECT A.BUDGET_YEAR,A.BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,NULL AS SOW, SERVICENAME,
COUNT(*) AS ALL_FIBER_EXTRAPOLATED
, SUM(IFF(ZIP9_CHECKED_12_MONTHS='Y',1,0)) AS ZIP9_12_EXTRAPOLATED 
, SUM(IFF(ZIP9_CHECKED_6_MONTHS='Y',1,0)) AS ZIP9_6_EXTRAPOLATED 
, SUM(IFF(ZIP9_CHECKED_3_MONTHS='Y',1,0)) AS ZIP9_3_EXTRAPOLATED 
, SUM(IFF(ZIP9_NEW_AREA='Y',1,0)) AS ZIP9_NEW_EXTRAPOLATED 
FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_BY_DMA A, V4_CTELL.TEST.DELIVERY_ENUM_BY_DMA B 
WHERE A.ZIP9 = SCIERA_ZIP5||SCIERA_ZIP4 AND UPPER(A.CLIENT_DELIVERY_NAME)=UPPER(B.PROVIDER) AND TRY_CAST(MAX_SPEED AS DOUBLE) >= 300 AND RN=1 
AND A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) 
GROUP BY ALL )B
WHERE B.BUDGET_YEAR = 2025 AND B.BUDGET_MONTH = 1 AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND A.FIBER_EXTRAPOLATED_COUNT_ALL IS NULL AND A.PUBLISHNAME IN ('BRIGHTSPEED','WTC','AIREBEAM111INTERNET','CITYSIDE FIBER','DESERT INET','GREAT111PLAINS111COMMUNICATIONS','CAMPUS COMMUNICATIONS GROUP','DOBSON111FIBER','TWIN111VALLEY','RITTER111COMMUNICATIONS','BLUESTREAM FIBER','GONETSPEED');



CREATE OR REPLACE TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS AS 
WITH A AS (SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE, ZIP9,SERVICENAME,PROJECT_TYPE, DATE_TRUNC('MONTH', DATE(MIN(CHECK_DATE))) AS CHECK_FL_DATE,
IFF(PROJECT_TYPE='BL',1,IFF(PROJECT_TYPE='WL',2,IFF(PROJECT_TYPE='NQ',3,4))) AS PROJECT_TYPE_INT 
FROM V4_CTELL.PROC.WIP_CURRENT WHERE MSO='COX' AND DELIVERED_DATE IS NOT NULL AND BUDGET_YEAR >= 2024 GROUP BY ALL)
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE, ZIP9,SERVICENAME,PROJECT_TYPE, CHECK_FL_DATE, PROJECT_TYPE_INT ,
RANK() OVER (PARTITION BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE, ZIP9,SERVICENAME ORDER BY PROJECT_TYPE_INT ASC) AS RN  
FROM A;

ALTER TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS ADD COLUMN CLIENT_DELIVERY_NAME VARCHAR, DMA VARCHAR;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A 
SET A.DMA = B.DMA
FROM V4_CTELL.TEST.DMA_FOR_ZIP9_COX B
WHERE A.ZIP9 = B.ZIP9 AND B.RNK = 1;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET A.CLIENT_DELIVERY_NAME=B.COX_DELIVERY_NAME FROM "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B WHERE A.SERVICENAME=B.PROVIDER_NAME;

ALTER TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS ADD COLUMN FIBER_FIRST_FOUND_ZIP9 DATE,FIBER_FIRST_FOUND_ZIP9_FL_DATE DATE,LAST_CHECK_DATE_ZIP9 DATE;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET 
FIBER_FIRST_FOUND_ZIP9 = FIBER_FIRST_FOUND, 
FIBER_FIRST_FOUND_ZIP9_FL_DATE = DATE_TRUNC('MONTH', DATE(FIBER_FIRST_FOUND)) , LAST_CHECK_DATE_ZIP9=B.CHECK_DATE 
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B WHERE 'COX'=B.MSO AND A.ZIP9=B.ZIP5||B.ZIP4 AND A.SERVICENAME=B.PROVIDER_NAME ;

ALTER TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS ADD COLUMN FIRST_CHECK_DATE_ZIP9 DATE;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET FIRST_CHECK_DATE_ZIP9=FIRST_CHECK_DATE FROM V4_CTELL.ROLLUPS.ZIP9_FIRST_CHECK_DATE B 
WHERE 'COX'=B.MSO AND A.ZIP9=B.ZIP5||B.ZIP4 AND A.SERVICENAME=B.PROVIDER_NAME; 

ALTER TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS ADD COLUMN ZIP9_KNOWN_AREA VARCHAR(1),ZIP9_NEW_AREA VARCHAR(1);

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET ZIP9_KNOWN_AREA='Y' WHERE CHECK_FL_DATE > FIRST_CHECK_DATE_ZIP9;
UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET ZIP9_NEW_AREA='Y' WHERE CHECK_FL_DATE <= FIRST_CHECK_DATE_ZIP9 OR FIRST_CHECK_DATE_ZIP9 IS NULL;

ALTER TABLE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS ADD COLUMN ZIP9_CHECKED_12_MONTHS VARCHAR(1),ZIP9_CHECKED_6_MONTHS  VARCHAR(1),ZIP9_CHECKED_3_MONTHS  VARCHAR(1);

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET A.ZIP9_CHECKED_3_MONTHS = 'Y' FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B WHERE  'COX'=B.MSO AND A.ZIP9=B.ZIP5||B.ZIP4 AND A.SERVICENAME=B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE 
AND B.CHECK_FL_DATE < A.CHECK_FL_DATE;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET A.ZIP9_CHECKED_6_MONTHS = 'Y' FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B WHERE  'COX'=B.MSO AND A.ZIP9=B.ZIP5||B.ZIP4 AND A.SERVICENAME=B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE 
AND B.CHECK_FL_DATE < DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND A.ZIP9_CHECKED_3_MONTHS IS NULL;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET A.ZIP9_CHECKED_12_MONTHS = 'Y' FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B WHERE  'COX'=B.MSO AND A.ZIP9=B.ZIP5||B.ZIP4 AND A.SERVICENAME=B.PROVIDER_NAME AND B.CHECK_FL_DATE < DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE 
AND A.ZIP9_CHECKED_3_MONTHS IS NULL  AND A.ZIP9_CHECKED_6_MONTHS IS NULL;

UPDATE V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS A SET A.ZIP9_CHECKED_12_MONTHS = 'Y' WHERE ZIP9_KNOWN_AREA='Y'  
AND (FIBER_FIRST_FOUND_ZIP9 IS NULL OR FIBER_FIRST_FOUND_ZIP9_FL_DATE >= CHECK_FL_DATE) 
AND ZIP9_CHECKED_12_MONTHS IS NULL AND ZIP9_CHECKED_6_MONTHS IS NULL AND ZIP9_CHECKED_3_MONTHS IS NULL AND ZIP9_NEW_AREA IS NULL;

----

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
SET FIBER_GROWTH_ZIP9_ALL_CHECKS = NULL,
           FIBER_GROWTH_ZIP9_12M_CHECKS = NULL,
           FIBER_GROWTH_ZIP9_6M_CHECKS = NULL,
           FIBER_GROWTH_ZIP9_3M_CHECKS = NULL,
           FIBER_GROWTH_ZIP9_NEWAREA_CHECKS = NULL;
           
ALTER TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA
ADD COLUMN FIBER_GROWTH_ZIP9_ALL_CHECKS VARCHAR,
           FIBER_GROWTH_ZIP9_12M_CHECKS VARCHAR,
           FIBER_GROWTH_ZIP9_6M_CHECKS VARCHAR,
           FIBER_GROWTH_ZIP9_3M_CHECKS VARCHAR,
           FIBER_GROWTH_ZIP9_NEWAREA_CHECKS VARCHAR;

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A 
SET FIBER_GROWTH_ZIP9_ALL_CHECKS  = (SELECT COUNT(*) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS B WHERE 
A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE));

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A 
SET FIBER_GROWTH_ZIP9_12M_CHECKS  = (
SELECT SUM(IFF(ZIP9_CHECKED_12_MONTHS='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS B WHERE 
A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE) );

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
FIBER_GROWTH_ZIP9_6M_CHECKS  = (
SELECT SUM(IFF(ZIP9_CHECKED_6_MONTHS='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS B WHERE 
A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE) );

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
FIBER_GROWTH_ZIP9_3M_CHECKS  = (
SELECT SUM(IFF(ZIP9_CHECKED_3_MONTHS='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS B WHERE 
A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE) );

UPDATE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA A SET 
FIBER_GROWTH_ZIP9_NEWAREA_CHECKS  = (
SELECT SUM(IFF(ZIP9_NEW_AREA='Y',1,0)) FROM V4_CTELL.TEST.ZIP9_PROJECT_TYPE_FOR_CHECKS B WHERE 
A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(NULL,'') AND UPPER(IFNULL(A.DMA,'')) = UPPER(IFNULL(B.DMA,'')) AND UPPER(A.PUBLISHNAME) = UPPER(B.SERVICENAME) AND (B.FIBER_FIRST_FOUND_ZIP9 IS NULL OR B.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= B.CHECK_FL_DATE) );


CREATE TABLE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA_FINAL_FOR_RAPH CLONE V4_CTELL.TEST.PROJECT_TYPE_ROLLUPS_FIBER_GROWTH_BY_DMA;
