UPDATE V4_CTELL.PROC.WIP_CURRENT
SET CHECK_DATE_FL = DATE_TRUNC('MONTH', DATE(CHECK_DATE));

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_FIRST_CHECKED = B.FIRST_CHECK_DATE
FROM V4_CTELL.ROLLUPS.ZIP9_FIRST_CHECK_DATE B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.ZIP9 = B.ZIP9 AND B.FIRST_CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_FIRST_CHECKED = B.FIRST_CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_FIRST_CHECK_DATE B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.CB = B.SCIERA_CB AND B.FIRST_CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_FIBER_FOUND = B.FIBER_FIRST_FOUND
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE) AND B.FIBER_FIRST_FOUND IS NOT NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_FIBER_FOUND = B.FIBER_FIRST_FOUND
FROM V4_CTELL.ROLLUPS.CB_ROLLUP B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE) AND B.FIBER_FIRST_FOUND IS NOT NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_EVER_CHECKED_3M = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B
WHERE A.ZIP9 = CONCAT(B.ZIP5,B.ZIP4) AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_DATE_FL >= DATEADD(MONTH, -3, A.CHECK_DATE_FL)::DATE AND B.CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_EVER_CHECKED_3M = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_ROLLUP B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_DATE_FL >= DATEADD(MONTH, -3, A.CHECK_DATE_FL)::DATE AND B.CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_EVER_CHECKED_6M = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_DATE_FL >= DATEADD(MONTH, -6, A.CHECK_DATE_FL)::DATE AND B.CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_EVER_CHECKED_6M = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_ROLLUP B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_DATE_FL >= DATEADD(MONTH, -6, A.CHECK_DATE_FL)::DATE AND B.CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_EVER_CHECKED_12M = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_DATE_FL >= DATEADD(MONTH, -12, A.CHECK_DATE_FL)::DATE AND B.CHECK_DATE_FL < A.CHECK_DATE_FL AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_EVER_CHECKED_12M = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_ROLLUP B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_DATE_FL >= DATEADD(MONTH, -12, A.CHECK_DATE_FL)::DATE AND B.CHECK_DATE_FL < A.CHECK_DATE_FL AND  A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);
