CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER"
(ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
MSO VARCHAR(16777216),
CB VARCHAR(16777216),
ZIP9COUNT VARCHAR(16777216),
HOMES VARCHAR(16777216),
SFU VARCHAR(16777216),
MDU VARCHAR(16777216),
OTHER VARCHAR(16777216),
MULTI_CB VARCHAR(16777216),
ZIPAV VARCHAR(16777216),
ILECAV VARCHAR(16777216),
ILECNA VARCHAR(16777216),
ILECFINAL VARCHAR(16777216),
MAXSPEED_1 VARCHAR(16777216),
MAXSPEED_2 VARCHAR(16777216),
MAXSPEED_3 VARCHAR(16777216),
MAXSPEED_4 VARCHAR(16777216),
MAXSPEED_5 VARCHAR(16777216),
UPDATED_DATE DATE
);

COPY INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" (MSO,CB,ZIP9COUNT,HOMES,SFU,MDU,OTHER,MULTI_CB,ZIPAV,ILECAV,ILECNA,ILECFINAL,MAXSPEED_1,MAXSPEED_2,MAXSPEED_3,MAXSPEED_4,MAXSPEED_5,UPDATED_DATE) FROM (SELECT 'charter_smb',t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,current_date() FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/charter_smb/results/rollup/cb_provider/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

COPY INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" (MSO,CB,ZIP9COUNT,HOMES,SFU,MDU,OTHER,MULTI_CB,ZIPAV,ILECAV,ILECNA,ILECFINAL,MAXSPEED_1,MAXSPEED_2,MAXSPEED_3,MAXSPEED_4,MAXSPEED_5,UPDATED_DATE) FROM (SELECT 'cox_smb',t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,current_date() FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/cox_smb/results/rollup/cb_provider/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

COPY INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" (MSO,CB,ZIP9COUNT,HOMES,SFU,MDU,OTHER,MULTI_CB,ZIPAV,ILECAV,ILECNA,ILECFINAL,MAXSPEED_1,MAXSPEED_2,MAXSPEED_3,MAXSPEED_4,MAXSPEED_5,UPDATED_DATE) FROM (SELECT 'comcast_smb',t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,current_date() FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/comcast_smb/results/rollup/cb_provider/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

COPY INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" (MSO,CB,ZIP9COUNT,HOMES,SFU,MDU,OTHER,MULTI_CB,ZIPAV,ILECAV,ILECNA,ILECFINAL,MAXSPEED_1,MAXSPEED_2,MAXSPEED_3,MAXSPEED_4,MAXSPEED_5,UPDATED_DATE) FROM (SELECT 'charter',t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,current_date() FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/charter/results/rollup/cb_provider/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

COPY INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" (MSO,CB,ZIP9COUNT,HOMES,SFU,MDU,OTHER,MULTI_CB,ZIPAV,ILECAV,ILECNA,ILECFINAL,MAXSPEED_1,MAXSPEED_2,MAXSPEED_3,MAXSPEED_4,MAXSPEED_5,UPDATED_DATE) FROM (SELECT 'comcast',t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,current_date() FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/comcast/results/rollup/cb_provider/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

COPY INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" (MSO,CB,ZIP9COUNT,HOMES,SFU,MDU,OTHER,MULTI_CB,ZIPAV,ILECAV,ILECNA,ILECFINAL,MAXSPEED_1,MAXSPEED_2,MAXSPEED_3,MAXSPEED_4,MAXSPEED_5,UPDATED_DATE) FROM (SELECT 'cox',t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,current_date() FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/cox/results/rollup/cb_provider/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;
