UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"
SET QA_PASSED=CTEL_QUEUE_QA(UPPER(MSO),UPPER(CLIENT_FILENAME),UPPER(PROJECT_NAME),UPPER(PROJECT_TYPE),UPPER(SERVICE_PROVIDER),UPPER(B.LIST_PROVIDER_NAME))
FROM (SELECT LISTAGG(DISTINCT PUBLISH_NAME,',') AS LIST_PROVIDER_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL") B
WHERE <<qa_where_clause>>;

COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/V4_CTELL/WIP_STAGING/PROD/INPUT_QUEUE_QA/QUEUE/<<queue_filename_path>>'
from (SELECT MSO,FP_KEY,SERVICE_PROVIDER,PROJECT_NAME,EXECUTION_TYPE,SCHEDULE_DATE,HOUSENUMBER,PRESTREETDIR,STREETNAME,STREETTYPE,POSTSTREETDIR,UNITTYPE,UNITNUMBER,SVC_ADDRESS_CITY,SVC_ADDRESS_STATE,SVC_ADDR_ZIP_5,SVC_ADDR_ZIP_4,LATITUDE,LONGITUDE,DELIVERABLE  FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER" WHERE QA_PASSED='Y' AND  <<outfile_where_clause>>)
FILE_FORMAT=( TYPE = CSV COMPRESSION ='none' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=TRUE HEADER = TRUE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;

COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/V4_CTELL/WIP_STAGING/PROD/INPUT_QUEUE_QA/SCHEDULED_INPUT/<<input_filename_path>>'
from (SELECT MSO,SERVICE_PROVIDER,FP_KEY,PROJECT_NAME,SCHEDULE_DATE  FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER" WHERE QA_PASSED='Y' AND <<outfile_where_clause>>)
FILE_FORMAT=( TYPE = CSV COMPRESSION ='bz2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=TRUE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;

