COPY INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" (S3FILENAME,INTERNAL_PROJECT_NAME,SOURCE_NAME,AGG_STARTTIME,AVAILABILITY_STATUS,INTERNETSTATUS,PARSER_MAXSPEED,PARSER_SITEADDRESS,STD_ADDRESSID,RWID,COX_FP_KEY,COMCAST_FP_KEY,CHARTER_FP_KEY,COX_SMB_FP_KEY,COMCAST_SMB_FP_KEY,CHARTER_SMB_FP_KEY,MEDIACOM_FP_KEY,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) FROM (SELECT metadata$filename,t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,t.$12,t.$13,t.$14,t.$15,t.$16,'<<source>>','<<file_name>>','<<current_date>>' FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/<<file_path>>' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 1,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING"
SET 
INTERNAL_PROJECT_NAME= UPPER(INTERNAL_PROJECT_NAME),
SOURCE_NAME= UPPER(SOURCE_NAME),
AGG_STARTTIME= UPPER(AGG_STARTTIME),
AVAILABILITY_STATUS= UPPER(AVAILABILITY_STATUS),
INTERNETSTATUS= UPPER(INTERNETSTATUS),
PARSER_MAXSPEED= UPPER(PARSER_MAXSPEED),
PARSER_SITEADDRESS= UPPER(PARSER_SITEADDRESS),
STD_ADDRESSID= UPPER(STD_ADDRESSID),
RWID= UPPER(RWID),
COX_FP_KEY= UPPER(COX_FP_KEY),
COMCAST_FP_KEY= UPPER(COMCAST_FP_KEY),
CHARTER_FP_KEY= UPPER(CHARTER_FP_KEY),
COX_SMB_FP_KEY= UPPER(COX_SMB_FP_KEY),
COMCAST_SMB_FP_KEY= UPPER(COMCAST_SMB_FP_KEY),
CHARTER_SMB_FP_KEY= UPPER(CHARTER_SMB_FP_KEY),
MEDIACOM_FP_KEY= UPPER(MEDIACOM_FP_KEY)
WHERE RESULT_FILENAME='<<file_name>>';
 
INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" (S3FILENAME,MSO,PROJECT_NAME,AGGREGATE_DATE,FIBER_MAXSPEED,HOUSEKEY,SERVICE_PROVIDER,AVAILABILITY_STATUS,STATUS_STD,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE)
SELECT * FROM (SELECT S3FILENAME,'COX' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,COX_FP_KEY AS FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(COX_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
UNION SELECT S3FILENAME,'COMCAST' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,COMCAST_FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(COMCAST_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
UNION SELECT S3FILENAME,'CHARTER' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,CHARTER_FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(CHARTER_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
UNION SELECT S3FILENAME,'COX_SMB' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,COX_SMB_FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(COX_SMB_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
UNION SELECT S3FILENAME,'COMCAST_SMB' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,COMCAST_SMB_FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(COMCAST_SMB_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
UNION SELECT S3FILENAME,'CHARTER_SMB' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,CHARTER_SMB_FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(CHARTER_SMB_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
UNION SELECT S3FILENAME,'MEDIACOM' AS MSO,INTERNAL_PROJECT_NAME,AGG_STARTTIME,PARSER_MAXSPEED,MEDIACOM_FP_KEY,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,AVAILABILITY_STATUS,INTERNETSTATUS,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_DISCOVERY_RESULTS_PRE_STAGING" WHERE IFNULL(MEDIACOM_FP_KEY,'')<>'' AND RESULT_FILENAME='<<file_name>>'
);