COPY INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_LENS_RESULTS_PRE_STAGING" (S3FILENAME,FP_KEY,AVAILABILITY_STATUS,INTERNET_STATUS,MAXSPEED,PROJECT_NAME,SCHEDULE_DATE,CITY,STATE,ZIP5,DIGIT_4,SOURCE_NAME,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) FROM (SELECT metadata$filename,t.$1,t.$2,t.$3,t.$4,t.$5,t.$6,t.$7,t.$8,t.$9,t.$10,t.$11,'<<source>>','<<file_name>>','<<current_date>>' FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/<<file_path>>' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 1,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_LENS_RESULTS_PRE_STAGING"
SET 
FP_KEY= UPPER(FP_KEY),
AVAILABILITY_STATUS= UPPER(AVAILABILITY_STATUS),
INTERNET_STATUS= UPPER(INTERNET_STATUS),
MAXSPEED= UPPER(MAXSPEED),
PROJECT_NAME= UPPER(PROJECT_NAME),
SCHEDULE_DATE= UPPER(SCHEDULE_DATE),
CITY= UPPER(CITY),
STATE= UPPER(STATE),
ZIP5= UPPER(ZIP5),
DIGIT_4= UPPER(DIGIT_4),
SOURCE_NAME= UPPER(SOURCE_NAME)
WHERE RESULT_FILENAME='<<file_name>>';



INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING"  (MSO,S3FILENAME,HOUSEKEY,AVAILABILITY_STATUS,STATUS_STD,FIBER_MAXSPEED,PROJECT_NAME,AGGREGATE_DATE,SERVICE_PROVIDER,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE)
SELECT 'SCIERA' AS MSO,S3FILENAME,FP_KEY,AVAILABILITY_STATUS,INTERNET_STATUS,MAXSPEED,PROJECT_NAME,SCHEDULE_DATE,REPLACE(REPLACE(REPLACE(SOURCE_NAME,' ','111'),',','222'),'.','333') SOURCE_NAME,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_LENS_RESULTS_PRE_STAGING" WHERE RESULT_FILENAME='<<file_name>>';

