UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.SCIERA_CB,
    A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.RWID = B.RWID,
    A.SRWID = B.SRWID	
    FROM (SELECT * FROM "MSO"."V3_CHARTER_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'CHARTER' AND A.HOUSEKEY =B.FP_KEY AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.SCIERA_CB,
    A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.RWID = B.RWID,
    A.SRWID = B.SRWID	 
    FROM (SELECT * FROM "MSO"."V3_COMCAST_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'COMCAST' AND A.HOUSEKEY =B.FP_KEY AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.SCIERA_CB,
    A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.RWID = B.RWID,
    A.SRWID = B.SRWID	 
    FROM (SELECT * FROM "MSO"."V3_COX_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'COX' AND A.HOUSEKEY =B.FP_KEY AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.SCIERA_CB,
    A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.RWID = B.RWID,
    A.SRWID = B.SRWID	 
    FROM (SELECT * FROM "MSO"."V3_COX_PRE_SERV_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) IN('COX-PRE-SERV','COX') AND A.HOUSEKEY =B.FP_KEY AND IS_MOVED = 'N' AND IFNULL(A.ZIP5,'')='' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.CENSUS_BLOCK,
    A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4	 
    FROM (SELECT * FROM "MSO"."V3_CHARTER_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'CHARTER_SMB' AND A.HOUSEKEY =B.STD_BUILDINGID AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.CENSUS_BLOCK,
    A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4	 
    FROM (SELECT * FROM "MSO"."V3_COMCAST_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'COMCAST_SMB' AND A.HOUSEKEY =B.STD_BUILDINGID AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB = B.CENSUS_BLOCK,
    A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4 
    FROM (SELECT * FROM "MSO"."V3_COX_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'COX_SMB' AND A.HOUSEKEY =B.STD_BUILDINGID AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" A
SET A.CB_AVAILABILITY = 'Y' FROM (SELECT * FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_CB_PROVIDER" WHERE  ILECFINAL = 'VERIZON')  B
WHERE REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = REPLACE(UPPER(B.MSO),'BUSINESS','SMB') AND A.CB = B.CB AND IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>' AND UPPER(A.MSO) IN ('COX','COMCAST','CHARTER');
 
INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" (S3FILENAME,MSO,FILE_NAME,PROJECT_NAME,AGGREGATE_DATE,DSL_PROVIDER,DSL_MAXSPEED,FIBER_PROVIDER,FIBER_MAXSPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,DIRECT_TV_PROVIDER,DSL_CUSTOMER,FIBER_CUSTOMER,DSL_CUSTOMER_SPEED,FIBER_CUSTOMER_SPEED,DIRECT_TV_CUSTOMER,FIBER_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,GIGABYTE,HOUSEKEY,FLATTENED_ID,SERVICE_PROVIDER,STATUS_STD,NETWORKTECHNOLOGY,AVAILABILITY_STATUS,RESULT_TYPE,SPRESALEESTIMATEDAYS,NEXTUPDATEDATE,WIRECENTERCODE,UPLOADMAXSPEED,S5G,LTE,S5G_SPEED,S4G_SPEED,S5G_UPLOAD_SPEED,AGG_SERVICE_PROVIDER,SCHEDULE_DATE,CB,ZIP5,ZIP4,CB_AVAILABILITY,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) SELECT S3FILENAME,MSO,FILE_NAME,PROJECT_NAME,AGGREGATE_DATE,DSL_PROVIDER,'',FIBER_PROVIDER,S5G_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,DIRECT_TV_PROVIDER,DSL_CUSTOMER,FIBER_CUSTOMER,DSL_CUSTOMER_SPEED,FIBER_CUSTOMER_SPEED,DIRECT_TV_CUSTOMER,FIBER_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,GIGABYTE,HOUSEKEY,FLATTENED_ID,'ATT-AIR',STATUS_STD,NETWORKTECHNOLOGY,'AV',RESULT_TYPE,SPRESALEESTIMATEDAYS,NEXTUPDATEDATE,WIRECENTERCODE,S5G_UPLOAD_SPEED,S5G,LTE,S5G_SPEED,S4G_SPEED,S5G_UPLOAD_SPEED,AGG_SERVICE_PROVIDER,SCHEDULE_DATE,CB,ZIP5,ZIP4,CB_AVAILABILITY,'DP-PIPE',RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" WHERE UPPER(SERVICE_PROVIDER) = 'ATT' AND S5G = 'Y' AND IS_MOVED = 'N' AND RESULT_FILENAME='<<file_name>>';
 
INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" (S3FILENAME,MSO,FILE_NAME,PROJECT_NAME,AGGREGATE_DATE,DSL_PROVIDER,DSL_MAXSPEED,FIBER_PROVIDER,FIBER_MAXSPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,DIRECT_TV_PROVIDER,DSL_CUSTOMER,FIBER_CUSTOMER,DSL_CUSTOMER_SPEED,FIBER_CUSTOMER_SPEED,DIRECT_TV_CUSTOMER,FIBER_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,GIGABYTE,HOUSEKEY,FLATTENED_ID,SERVICE_PROVIDER,STATUS_STD,NETWORKTECHNOLOGY,AVAILABILITY_STATUS,RESULT_TYPE,SPRESALEESTIMATEDAYS,NEXTUPDATEDATE,WIRECENTERCODE,UPLOADMAXSPEED,S5G,LTE,S5G_SPEED,S4G_SPEED,S5G_UPLOAD_SPEED,AGG_SERVICE_PROVIDER,SCHEDULE_DATE,CB,ZIP5,ZIP4,CB_AVAILABILITY,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) SELECT S3FILENAME,MSO,FILE_NAME,PROJECT_NAME,AGGREGATE_DATE,DSL_PROVIDER,'',FIBER_PROVIDER,CASE WHEN S5G = 'Y' THEN S5G_SPEED  ELSE  S4G_SPEED END,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,DIRECT_TV_PROVIDER,DSL_CUSTOMER,FIBER_CUSTOMER,DSL_CUSTOMER_SPEED,FIBER_CUSTOMER_SPEED,DIRECT_TV_CUSTOMER,FIBER_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,GIGABYTE,HOUSEKEY,FLATTENED_ID,'VERIZON1115G',STATUS_STD,NETWORKTECHNOLOGY,'AV',RESULT_TYPE,SPRESALEESTIMATEDAYS,NEXTUPDATEDATE,WIRECENTERCODE,S5G_UPLOAD_SPEED,S5G,LTE,S5G_SPEED,S4G_SPEED,S5G_UPLOAD_SPEED,AGG_SERVICE_PROVIDER,SCHEDULE_DATE,CB,ZIP5,ZIP4,CB_AVAILABILITY,'DP-PIPE',RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" WHERE UPPER(SERVICE_PROVIDER) = 'VERIZON' AND (S5G = 'Y' OR LTE = 'Y') AND IS_MOVED = 'N' AND UPPER(MSO) IN ('COX','COMCAST','CHARTER') AND RESULT_FILENAME='<<file_name>>';


UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET STATUS_CHANGED = 'AV' WHERE UPPER(SERVICE_PROVIDER) = 'VERIZON' AND UPPER(AVAILABILITY_STATUS) = 'NA' AND CB_AVAILABILITY = 'Y' AND IS_MOVED = 'N' AND UPPER(MSO) IN ('COX','COMCAST','CHARTER') AND RESULT_FILENAME='<<file_name>>';

INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" (S3FILENAME,MSO,FILE_NAME,PROJECT_NAME,AGGREGATE_DATE,DSL_PROVIDER,DSL_MAXSPEED,FIBER_PROVIDER,FIBER_MAXSPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,DIRECT_TV_PROVIDER,DSL_CUSTOMER,FIBER_CUSTOMER,DSL_CUSTOMER_SPEED,FIBER_CUSTOMER_SPEED,DIRECT_TV_CUSTOMER,FIBER_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,GIGABYTE,HOUSEKEY,FLATTENED_ID,SERVICE_PROVIDER,STATUS_STD,NETWORKTECHNOLOGY,AVAILABILITY_STATUS,RESULT_TYPE,SPRESALEESTIMATEDAYS,NEXTUPDATEDATE,WIRECENTERCODE,UPLOADMAXSPEED,S5G,LTE,S5G_SPEED,S4G_SPEED,S5G_UPLOAD_SPEED,AGG_SERVICE_PROVIDER,SCHEDULE_DATE,CB,ZIP5,ZIP4,CB_AVAILABILITY,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) SELECT S3FILENAME,MSO,FILE_NAME,PROJECT_NAME,AGGREGATE_DATE,DSL_PROVIDER,DSL_MAXSPEED,FIBER_PROVIDER,FIBER_MAXSPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,DIRECT_TV_PROVIDER,DSL_CUSTOMER,FIBER_CUSTOMER,DSL_CUSTOMER_SPEED,FIBER_CUSTOMER_SPEED,DIRECT_TV_CUSTOMER,FIBER_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,GIGABYTE,HOUSEKEY,FLATTENED_ID,'VERIZON1115G',STATUS_STD,NETWORKTECHNOLOGY,AVAILABILITY_STATUS,RESULT_TYPE,SPRESALEESTIMATEDAYS,NEXTUPDATEDATE,WIRECENTERCODE,UPLOADMAXSPEED,S5G,LTE,S5G_SPEED,S4G_SPEED,S5G_UPLOAD_SPEED,AGG_SERVICE_PROVIDER,SCHEDULE_DATE,CB,ZIP5,ZIP4,CB_AVAILABILITY,'DP-PIPE',RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" WHERE UPPER(SERVICE_PROVIDER) = 'VERIZON' AND UPPER(AVAILABILITY_STATUS) ='NA' AND CB_AVAILABILITY='N' AND IS_MOVED = 'N' AND UPPER(MSO) IN ('COX','COMCAST','CHARTER') AND RESULT_FILENAME='<<file_name>>';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET STATUS_CHANGED = 'OA' WHERE UPPER(SERVICE_PROVIDER) = 'VERIZON' AND AVAILABILITY_STATUS = 'NA' AND CB_AVAILABILITY='N' AND IS_MOVED = 'N' AND UPPER(MSO) IN ('COX','COMCAST','CHARTER') AND RESULT_FILENAME='<<file_name>>';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET INTERNETCUSTOMER =
CASE WHEN IFNULL(DSL_CUSTOMER,'')='' THEN FIBER_CUSTOMER ELSE DSL_CUSTOMER END WHERE IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>' AND IFNULL(INTERNETCUSTOMER,'')='' ; 

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET INTERNETCUSTOMERSPEED =
CASE WHEN IFNULL(DSL_CUSTOMER_SPEED,'')='' THEN FIBER_CUSTOMER_SPEED ELSE DSL_CUSTOMER_SPEED END  WHERE IS_MOVED = 'N'  AND  RESULT_FILENAME='<<file_name>>' AND IFNULL(INTERNETCUSTOMERSPEED,'')='' ;  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET PROVIDERTYPE =
CASE WHEN UPPER(SERVICE_PROVIDER) IN ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON')
THEN 'ILEC' ELSE 'OB' END  WHERE IS_MOVED = 'N'  AND  RESULT_FILENAME='<<file_name>>' AND IFNULL(PROVIDERTYPE,'')='' ; 

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET CHECK_DATE = DATE(AGGREGATE_DATE)  WHERE IS_MOVED = 'N'  AND  RESULT_FILENAME='<<file_name>>' AND IFNULL(CHECK_DATE,'')='' ;  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET MAX_SPEED = CASE WHEN UPPER(CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END) ILIKE ('%MBPS%') THEN CAST(REGEXP_REPLACE(UPPER(CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END),'MBPS','') AS VARCHAR) 
      WHEN UPPER(CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END) ILIKE ('%KBPS%') THEN CAST(CAST(REGEXP_REPLACE(UPPER(CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END),'KBPS','') AS DOUBLE)/1000  AS VARCHAR) 
      WHEN IFNULL(CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END,'')='' OR CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END='' THEN CAST('0.0' AS VARCHAR)  ELSE CAST(CASE WHEN IFNULL((CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END),'') =''THEN (CASE WHEN IFNULL(FIBER_MAXSPEED,'')=''OR CAST(FIBER_MAXSPEED AS DOUBLE)=0 THEN '' ELSE FIBER_MAXSPEED END) ELSE (CASE WHEN IFNULL(DSL_MAXSPEED,'')=''OR CAST(DSL_MAXSPEED AS DOUBLE)=0 THEN '' ELSE DSL_MAXSPEED END) END AS VARCHAR)  END 
       WHERE IS_MOVED = 'N'  AND  RESULT_FILENAME='<<file_name>>' AND IFNULL(MAX_SPEED,'')='' ;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET MAX_SPEED_CHANGED = CASE WHEN SERVICE_PROVIDER='ATT' AND MAX_SPEED='14.0' THEN '18.0'
WHEN SERVICE_PROVIDER='ATT' AND MAX_SPEED='27.0' THEN '25.0'
ELSE MAX_SPEED END;	   
        
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET FIBER_TV_PROVIDER_UPDATED = IFNULL(CASE WHEN LENGTH(TRIM(IFNULL(FIBER_TV_PROVIDER,'')))!=0 THEN FIBER_TV_PROVIDER 
     WHEN LENGTH(TRIM(IFNULL(FIBER_TV_PROVIDER,'')))=0 AND LENGTH(TRIM(IFNULL(DIRECT_TV_PROVIDER,'')))!=0 THEN DIRECT_TV_PROVIDER             
     ELSE FIBER_TV_PROVIDER END,'') WHERE IS_MOVED = 'N'  AND  RESULT_FILENAME='<<file_name>>' AND IFNULL(FIBER_TV_PROVIDER_UPDATED,'')='' ;  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING"  SET STATUS_CHANGED = CASE WHEN STATUS_CHANGED IS NULL THEN AVAILABILITY_STATUS ELSE STATUS_CHANGED END WHERE IFNULL(STATUS_CHANGED,'')='' ;  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET MSO_CHANGED = UPPER(REPLACE(MSO,'SMB','BUSINESS')) WHERE IFNULL(MSO_CHANGED,'')='' ;  
	 

INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_HKEY_TO_CLOSE"(MSO,PROJECT_NAME,FP_KEY,SERVICE_PROVIDER,MAX_SPEED,CHECK_DATE,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) SELECT MSO_CHANGED,PROJECT_NAME,HOUSEKEY,SERVICE_PROVIDER,MAX_SPEED_CHANGED,CHECK_DATE,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" WHERE UPPER(SERVICE_PROVIDER)  = 'ATT' AND S5G = 'Y' AND UPPER(AVAILABILITY_STATUS) = 'NA' AND IS_MOVED = 'N' AND RESULT_FILENAME='<<file_name>>'; 	 
	 
INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" (MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,PROVIDER_TYPE,STATUS,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,INTERNET_CUSTOMER,INTERNET_CUSTOMER_SPEED,FIBER_TV_CUSTOMER,DIRECT_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,CHECK_DATE,UPLOAD_MAX_SPEED,SCHEDULE_DATE,CB,ZIP5,ZIP4,RWID,SRWID,RESULT_SOURCE,RESULT_FILENAME,RESULT_FILEDATE) SELECT MSO_CHANGED,HOUSEKEY,PROJECT_NAME,SERVICE_PROVIDER,PROVIDERTYPE,STATUS_CHANGED,TRY_CAST(MAX_SPEED_CHANGED AS DOUBLE),FIBER_TV_PROVIDER_UPDATED,FIBER_PHONE_PROVIDER,INTERNETCUSTOMER,TRY_CAST(INTERNETCUSTOMERSPEED AS DOUBLE),FIBER_TV_CUSTOMER,DIRECT_TV_CUSTOMER,WIRELESS_CUSTOMER,POTS_CUSTOMER,TRY_CAST(CHECK_DATE AS DATE),TRY_CAST(UPLOADMAXSPEED AS DOUBLE),TRY_CAST(SCHEDULE_DATE AS DATE),CB,ZIP5,ZIP4,RWID,SRWID,RESULT_SOURCE,RESULT_FILENAME,TRY_CAST(RESULT_FILEDATE AS DATE)
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" WHERE IS_MOVED = 'N' AND  RESULT_FILENAME='<<file_name>>';


UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING"
SET STATUS_PRIORITY = CASE WHEN STATUS = 'AV' THEN 1 
                           WHEN STATUS = 'CS' THEN 2
                           WHEN STATUS = 'NS' THEN 3
                           WHEN STATUS = 'NA' THEN 4
                           WHEN STATUS = 'NF' THEN 5
                           WHEN STATUS = 'ER' THEN 6 END
WHERE  RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" A
SET A.WIP_RNK = B.WIP_RNK_COMPUTED,
    A.HKEY_RNK = B.HKEY_RNK_COMPUTED
  FROM (SELECT *,ROW_NUMBER() OVER(PARTITION BY MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME ORDER BY STATUS_PRIORITY ASC,MAX_SPEED DESC,CHECK_DATE DESC) AS WIP_RNK_COMPUTED
,ROW_NUMBER() OVER(PARTITION BY MSO,FP_KEY,PROVIDER_NAME ORDER BY STATUS_PRIORITY ASC,MAX_SPEED DESC,CHECK_DATE DESC) AS HKEY_RNK_COMPUTED
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" WHERE RESULT_FILENAME='<<file_name>>' ) B
WHERE A.ID = B.ID AND A.RESULT_FILENAME='<<file_name>>';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RAW_RESULTS_STAGING" SET IS_MOVED = 'Y' WHERE IS_MOVED = 'N'  AND  RESULT_FILENAME='<<file_name>>'; 

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" A 
SET READY_TO_RELEASE = 'N' 
  FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_RELEASE_SCHEDULE" B
WHERE UPPER(A.PROVIDER_NAME) = UPPER(B.PROVIDER) AND UPPER(A.MSO) = UPPER(B.MSO) AND A.WIP_PROCESSED = 'N' AND DATEDIFF(DAY,A.RESULT_FILEDATE,CURRENT_DATE())< B.DAYS AND  RESULT_FILENAME='<<file_name>>' AND B.ACTIVE = 'Y';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A 
    SET A.STATUS = B.STATUS,
        A.CHECK_DATE = B.CHECK_DATE,                     
        A.MAX_SPEED = B.MAX_SPEED,
        A.UPLOAD_MAX_SPEED = B.UPLOAD_MAX_SPEED,
        A.RESULT_SOURCE = B.RESULT_SOURCE,
        A.RESULT_FILE_NAME = B.RESULT_FILENAME,
        A.RESULT_FILE_DATE = B.RESULT_FILEDATE,
		A.PROCESSED_DATE = CURRENT_DATE()
    FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" B
WHERE UPPER(A.MSO) = UPPER(B.MSO) AND A.FP_KEY = B.FP_KEY AND UPPER(A.SERVICENAME) = UPPER(B.PROVIDER_NAME) AND 
UPPER(A.PROJECTNAME) = UPPER(B.PROJECT_NAME)
AND A.SCHEDULEDATE<= B.CHECK_DATE  AND  B.WIP_PROCESSED = 'N' AND B.WIP_RNK = 1 AND B.READY_TO_RELEASE = 'Y' AND  B.RESULT_FILENAME='<<file_name>>' ;

INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" (MSO,SERVICENAME,FP_KEY,PROJECTNAME,SCHEDULEDATE,STATUS,CHECK_DATE,MAX_SPEED,UPLOAD_MAX_SPEED,DELIVERED_DATE,INPUT_FILE_NAME,INPUT_FILE_DATE,RESULT_FILE_NAME,RESULT_FILE_DATE,RESULT_SOURCE,PROCESSED_DATE) SELECT A.MSO,A.PROVIDER_NAME,A.FP_KEY,A.PROJECT_NAME,CASE WHEN A.SCHEDULE_DATE IS NULL THEN A.CHECK_DATE ELSE A.SCHEDULE_DATE END AS SCHEDULE_DATE,A.STATUS,A.CHECK_DATE,A.MAX_SPEED,A.UPLOAD_MAX_SPEED,NULL,A.RESULT_FILENAME,A.RESULT_FILEDATE,A.RESULT_FILENAME,A.RESULT_FILEDATE,A.RESULT_SOURCE,CURRENT_DATE()
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" A LEFT JOIN "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" B
ON UPPER(A.MSO) = UPPER(B.MSO) AND A.FP_KEY = B.FP_KEY AND UPPER(A.PROVIDER_NAME) = UPPER(B.SERVICENAME) AND 
UPPER(A.PROJECT_NAME) = UPPER(B.PROJECTNAME) AND A.CHECK_DATE>= B.SCHEDULEDATE  WHERE B.FP_KEY IS NULL AND  A.WIP_PROCESSED = 'N'  AND A.WIP_RNK = 1 AND A.READY_TO_RELEASE = 'Y' AND  A.RESULT_FILENAME='<<file_name>>';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" 
    SET WIP_PROCESSED = 'Y',
        WIP_PROCESSED_DATE = CURRENT_DATE()
		WHERE WIP_PROCESSED = 'N' AND READY_TO_RELEASE = 'Y' AND  RESULT_FILENAME='<<file_name>>';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" A
     SET A.FIBER_TV_PROVIDER = B.FIBER_TV_PROVIDER,
         A.FIBER_PHONE_PROVIDER = B.FIBER_PHONE_PROVIDER,
		 A.LAST_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
         A.MOST_RECENT_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
		 A.MOST_RECENT_MAX_SPEED = B.MAX_SPEED,
         A.UPLOAD_MAX_SPEED = B.UPLOAD_MAX_SPEED
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" B
WHERE UPPER(A.MSO) = UPPER(B.MSO) AND A.FP_KEY = B.FP_KEY AND UPPER(A.PROVIDER_NAME) = UPPER(B.PROVIDER_NAME) AND UPPER(B.STATUS) = 'AV' AND A.CLOSE_DATE IS NULL AND (
(CAST(A.MAX_SPEED AS DOUBLE) = CAST(B.MAX_SPEED AS DOUBLE))
 OR (UPPER(B.PROVIDER_NAME)<>'BRIGHTSPEED' AND CAST(A.MAX_SPEED AS DOUBLE) > CAST(B.MAX_SPEED AS DOUBLE))
 OR ( NOT(UPPER(B.PROVIDER_NAME)='FRONTIER111COMMUNICATIONS' AND CAST(B.MAX_SPEED AS DOUBLE) = 10.0 AND CAST(B.UPLOAD_MAX_SPEED AS DOUBLE) = 1.0 AND (UPPER(B.MSO) = 'CHARTER' OR UPPER(B.MSO) = 'CHARTER_SMB' OR UPPER(B.MSO) = 'CHARTER_BUSINESS') AND CAST(A.MAX_SPEED AS DOUBLE) > CAST(B.MAX_SPEED AS DOUBLE))
 )) AND B.HKEY_PROCESSED = 'N' AND B.HKEY_RNK = 1 AND B.READY_TO_RELEASE = 'Y' AND  B.RESULT_FILENAME='<<file_name>>' ;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" A
     SET A.CLOSE_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
		 A.LAST_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
         A.MOST_RECENT_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
		 A.MOST_RECENT_MAX_SPEED = B.MAX_SPEED
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" B
WHERE UPPER(A.MSO) = UPPER(B.MSO) AND A.FP_KEY = B.FP_KEY AND UPPER(A.PROVIDER_NAME) = UPPER(B.PROVIDER_NAME) AND UPPER(B.STATUS) = 'AV' AND A.CLOSE_DATE IS NULL AND (
(CAST(A.MAX_SPEED AS DOUBLE) < CAST(B.MAX_SPEED AS DOUBLE))
OR (UPPER(B.PROVIDER_NAME)='BRIGHTSPEED' AND CAST(A.MAX_SPEED AS DOUBLE) <> CAST(B.MAX_SPEED AS DOUBLE))
OR (UPPER(B.PROVIDER_NAME)='FRONTIER111COMMUNICATIONS' AND CAST(B.MAX_SPEED AS DOUBLE) = 10.0 AND CAST(B.UPLOAD_MAX_SPEED AS DOUBLE) = 1.0 AND (UPPER(B.MSO) = 'CHARTER' OR UPPER(B.MSO) = 'CHARTER_SMB'  OR UPPER(B.MSO) = 'CHARTER_BUSINESS')AND CAST(A.MAX_SPEED AS DOUBLE) <> CAST(B.MAX_SPEED AS DOUBLE))) AND B.HKEY_PROCESSED = 'N' AND B.HKEY_RNK = 1 AND B.READY_TO_RELEASE = 'Y' AND  B.RESULT_FILENAME='<<file_name>>' ;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" A
     SET A.CLOSE_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
		 A.LAST_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
         A.MOST_RECENT_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE),
		 A.MOST_RECENT_MAX_SPEED = B.MAX_SPEED
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_HKEY_TO_CLOSE" B
WHERE UPPER(A.MSO) = UPPER(B.MSO) AND A.FP_KEY = B.FP_KEY AND UPPER(A.PROVIDER_NAME) = UPPER(B.SERVICE_PROVIDER) AND A.CLOSE_DATE IS NULL AND B.RESULT_FILENAME='<<file_name>>' AND B.IS_CLOSED = 'N';
 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_HKEY_TO_CLOSE" A
     SET A.IS_CLOSED = 'Y' WHERE A.RESULT_FILENAME='<<file_name>>' AND A.IS_CLOSED = 'N';
		 
 
INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" (MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,PROVIDER_TYPE,ZIP5,ZIP4,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,OPEN_DATE,CLOSE_DATE,LAST_CHECK_DATE,PREV_MAX_SPEED,PREV_FIBER_TV_PROVIDER,PREV_FIBER_PHONE_PROVIDER,PREV_OPEN_DATE,FP_RWID,FP_SRWID,MOST_RECENT_CHECK_DATE,MOST_RECENT_MAX_SPEED,UPLOAD_MAX_SPEED,ACTIVE_RESULT_SOURCE,ACTIVE_RESULT_FILENAME,ACTIVE_RESULT_FILEDATE) 
 SELECT A.MSO,A.FP_KEY,A.PROJECT_NAME,A.PROVIDER_NAME,A.PROVIDER_TYPE,A.ZIP5,A.ZIP4,A.MAX_SPEED,A.FIBER_TV_PROVIDER,A.FIBER_PHONE_PROVIDER,TRY_CAST(A.CHECK_DATE AS DATE) AS OPEN_DATE,NULL AS CLOSE_DATE,TRY_CAST(A.CHECK_DATE AS DATE) AS LAST_CHECK_DATE,NULL AS PREV_MAX_SPEED,NULL AS PREV_FIBER_TV_PROVIDER,NULL AS PREV_FIBER_PHONE_PROVIDER,NULL AS PREV_OPEN_DATE,RWID AS FP_RWID,SRWID AS FP_SRWID,TRY_CAST(A.CHECK_DATE AS DATE) AS MOST_RECENT_CHECK_DATE,A.MAX_SPEED AS MOST_RECENT_MAX_SPEED,A.UPLOAD_MAX_SPEED,A.RESULT_SOURCE AS ACTIVE_RESULT_SOURCE,A.RESULT_FILENAME AS ACTIVE_RESULT_FILENAME,A.RESULT_FILEDATE AS ACTIVE_RESULT_FILEDATE FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" A LEFT JOIN "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" B ON A.FP_KEY = B.FP_KEY AND UPPER(A.PROVIDER_NAME) = UPPER(B.PROVIDER_NAME) AND UPPER(A.MSO) = UPPER(B.MSO) AND UPPER(A.STATUS) = 'AV' AND B.CLOSE_DATE IS NULL WHERE B.FP_KEY IS NULL AND UPPER(A.STATUS) = 'AV' AND A.HKEY_RNK = 1 AND  A.HKEY_PROCESSED = 'N' AND A.READY_TO_RELEASE = 'Y' AND  A.RESULT_FILENAME='<<file_name>>' ;

UPDATE  "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" A
SET A.PREV_MAX_SPEED = B.UPDATED_PREV_MAX_SPEED,
    A.PREV_FIBER_TV_PROVIDER = B.UPDATED_PREV_FIBER_TV_PROVIDER,
    A.PREV_FIBER_PHONE_PROVIDER = B.UPDATED_PREV_FIBER_PHONE_PROVIDER,
    A.PREV_OPEN_DATE = B.UPDATED_PREV_OPEN_DATE 
    FROM ( SELECT LEAD(OPEN_DATE,1) OVER(PARTITION BY FP_KEY,PROVIDER_NAME ORDER BY OPEN_DATE DESC) AS UPDATED_PREV_OPEN_DATE,
LEAD(FIBER_TV_PROVIDER,1) OVER(PARTITION BY FP_KEY,PROVIDER_NAME ORDER BY OPEN_DATE DESC) AS UPDATED_PREV_FIBER_TV_PROVIDER,
LEAD(FIBER_PHONE_PROVIDER,1) OVER(PARTITION BY FP_KEY,PROVIDER_NAME ORDER BY OPEN_DATE DESC) AS UPDATED_PREV_FIBER_PHONE_PROVIDER,
LEAD(MAX_SPEED,1) OVER(PARTITION BY FP_KEY,PROVIDER_NAME ORDER BY OPEN_DATE DESC) AS UPDATED_PREV_MAX_SPEED,
* FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" ) B
WHERE A.ID =B.ID AND A.CLOSE_DATE IS NULL; 

UPDATE  "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" A
     SET A.MOST_RECENT_CHECK_DATE = TRY_CAST(B.CHECK_DATE AS DATE)
FROM  "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" B
WHERE UPPER(A.MSO) = UPPER(B.MSO) AND A.FP_KEY = B.FP_KEY AND UPPER(A.PROVIDER_NAME) = UPPER(B.PROVIDER_NAME) AND UPPER(B.STATUS) = 'NS' AND A.CLOSE_DATE IS NULL 
AND B.HKEY_PROCESSED = 'N' AND B.HKEY_RNK = 1 AND B.READY_TO_RELEASE = 'Y' AND  B.RESULT_FILENAME='<<file_name>>' ;


UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."RESULTS_STAGING" 
    SET HKEY_PROCESSED = 'Y',
        HKEY_PROCESSED_DATE = CURRENT_DATE()
		WHERE HKEY_PROCESSED = 'N' AND READY_TO_RELEASE = 'Y' AND RESULT_FILENAME='<<file_name>>';
		
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = B.DWELL_TYPE,
	A.DMA = B.SCIERA_DMA	
    FROM (SELECT * FROM "MSO"."V3_CHARTER_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'CHARTER' AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = B.DWELL_TYPE,
	A.REGION = B.H2,
    A.DMA = B.SCIERA_DMA	
    FROM (SELECT * FROM "MSO"."V3_COMCAST_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'COMCAST' AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = B.DWELL_TYPE,
    A.DMA = B.SCIERA_DMA	
    FROM (SELECT * FROM "MSO"."V3_COX_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'COX' AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  


UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.CENSUS_BLOCK,
    A.H1 = B.H1,
	A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.ZIP5,''),IFNULL(B.ZIP4,'')),''),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_CHARTER_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'CHARTER_SMB' AND A.FP_KEY =B.STD_BUILDINGID AND IFNULL(A.CB,'')='';  
  
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.CENSUS_BLOCK,
    A.H1 = B.H1,
	A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.ZIP5,''),IFNULL(B.ZIP4,'')),''),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_COMCAST_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'COMCAST_SMB' AND A.FP_KEY =B.STD_BUILDINGID AND IFNULL(A.CB,'')='';  
  
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.CENSUS_BLOCK,
    A.H1 = B.H1,
	A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.ZIP5,''),IFNULL(B.ZIP4,'')),''),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_COX_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'COX_SMB' AND A.FP_KEY =B.STD_BUILDINGID AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = UPPER(B.DWELL_TYPE),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_COX_PRE_SERV_RESOURCE"."FP"  WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) IN('COX-PRE-SERV','COX') AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET BUDGET_TYPE = CASE WHEN UPPER(SERVICENAME)='ATT' THEN 'ATT'
                       WHEN UPPER(SERVICENAME) IN ('TMOBILE5G-HOME','TMOBILE5G-FIBER','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END
WHERE BUDGET_TYPE IS NULL;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET PROJECT_TYPE = CASE WHEN UPPER(SUBSTR(PROJECTNAME,1,1))='B'  THEN 'BL'
                        WHEN UPPER(SUBSTR(PROJECTNAME,1,1))='D' OR 
                             UPPER(SUBSTR(PROJECTNAME,1,2))='NQ' THEN 'NQ'
                        WHEN UPPER(SUBSTR(PROJECTNAME,1,1))='W' THEN 'WL'
                        WHEN UPPER(SUBSTR(PROJECTNAME,1,2))='A_' THEN 'AH'
                        ELSE NULL END
WHERE PROJECT_TYPE IS NULL;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET ENGAGEMENT_TYPE = CASE WHEN UPPER(MSO) LIKE '%BUSINESS%' THEN 'SMB'
                        ELSE 'RESI' END
WHERE ENGAGEMENT_TYPE IS NULL;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET QUEUE_YEAR=YEAR(CAST(SCHEDULEDATE AS DATE)) WHERE QUEUE_YEAR IS NULL ;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET QUEUE_MONTH= MONTH(CAST(SCHEDULEDATE AS DATE)) WHERE QUEUE_MONTH IS NULL ;

UPDATE "V4_CTELL"."PROC"."WIP_CURRENT"
SET DELIVERED_YEAR= YEAR(CAST(DELIVERED_DATE AS DATE)) WHERE DELIVERED_YEAR IS NULL AND DELIVERED_DATE IS NOT NULL;

UPDATE "V4_CTELL"."PROC"."WIP_CURRENT"
SET DELIVERED_MONTH=MONTH(CAST(DELIVERED_DATE AS DATE)) WHERE DELIVERED_MONTH IS NULL AND DELIVERED_DATE IS NOT NULL ;


UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
 SET A.STD_NAME=B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
 WHERE UPPER(A.SERVICENAME)=UPPER(PUBLISH_NAME) AND ACTIVE='Y' AND A.STD_NAME IS NULL;
 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"  A
SET A.STD_NAME= B.STD_NAME
FROM "V4_CTELL"."TEST"."MASTER_STD_NAME_CTELL_EXCEPTIONAL" B
WHERE UPPER(A.SERVICENAME)=B.PUBLISH_NAME AND A.STD_NAME IS NULL; 

 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CLIENT_FILENAME = B.CLIENT_FILENAME,
    A.CLIENT_SENT_DATE = B.CLIENT_SENT_DATE, 
    A.CLIENT_PROVIDER_NAME = B.CLIENT_PROVIDER_NAME
 FROM  "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"  B
 WHERE A.FP_KEY = B.FP_KEY AND A.PROJECTNAME =B.PROJECT_NAME AND A.SERVICENAME = B.SERVICE_PROVIDER
AND A.CLIENT_FILENAME IS NULL;
 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CLIENT_FILENAME = B.CLIENT_FILENAME,
    A.CLIENT_SENT_DATE = B.CLIENT_SENT_DATE, 
    A.CLIENT_PROVIDER_NAME = B.CLIENT_PROVIDER_NAME
 FROM  "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"  B
 WHERE A.FP_KEY = B.UQID AND A.PROJECTNAME =B.PROJECT_NAME AND A.SERVICENAME = B.SERVICE_PROVIDER
AND A.CLIENT_FILENAME IS NULL;
 
 UPDATE "V4_CTELL"."PROC"."WIP_CURRENT" A
SET A.BUDGET_YEAR = B.BUDGET_YEAR,
    A.BUDGET_MONTH = B.BUDGET_MONTH 
 FROM  "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"  B
 WHERE A.FP_KEY = B.FP_KEY AND A.PROJECTNAME =B.PROJECT_NAME AND A.SERVICENAME = B.SERVICE_PROVIDER
AND (A.BUDGET_YEAR IS NULL OR A.BUDGET_MONTH IS NULL);
 
UPDATE "V4_CTELL"."PROC"."WIP_CURRENT" A
SET A.BUDGET_MONTH = B.BUDGET_MONTH,
    A.BUDGET_YEAR = B.BUDGET_YEAR
FROM    
(SELECT BUDGET_YEAR,BUDGET_MONTH,PROJECTNAME,REPLACE(REPLACE(SERVICENAME,'ATT','ATT-AIR'),'VERIZON','VERIZON1115G') AS SERVICENAME,FP_KEY FROM "V4_CTELL"."PROC"."WIP_CURRENT"
WHERE SERVICENAME IN ('ATT','VERIZON') AND QUEUE_YEAR = 2024  ) B
WHERE A.FP_KEY = B.FP_KEY AND A.SERVICENAME = B.SERVICENAME AND  A.PROJECTNAME = B.PROJECTNAME
 AND (A.BUDGET_YEAR IS NULL OR A.BUDGET_MONTH IS NULL); 
 
CREATE OR REPLACE TABLE "<<DB_NAME>>"."PUBLISH"."WIP_CURRENT"  CLONE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" ;

CREATE OR REPLACE TABLE "<<DB_NAME>>"."PUBLISH"."HKEY_CURRENT"  CLONE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" ;
		
		
		
		

