INSERT INTO AROSCOP_INT.SUDHA.ASKONE_REPORTING_MASTER_QUEUE (ADVERTISERGUID,TOPIC_NAME,TOPIC_ID,TOPIC_CREATED_DATE) SELECT a.ADVERTISERGUID,a.TOPIC_NAME,a.TOPIC_ID,CURRENT_TIMESTAMP FROM (SELECT DISTINCT ADVERTISERGUID,TOPIC_NAME,TOPIC_ID FROM AROSCOP_EXT.SCHEMA_AROSCOP_EXT.ASKONE_REPORTING WHERE ADVERTISERGUID IN ('<<ADVERTISERGUID_STRING>>') ) a LEFT JOIN AROSCOP_INT.SUDHA.ASKONE_REPORTING_MASTER_QUEUE b ON a.ADVERTISERGUID = b.ADVERTISERGUID AND a.TOPIC_NAME = b.TOPIC_NAME AND a.TOPIC_ID = b.TOPIC_ID WHERE b.ADVERTISERGUID IS NULL;

INSERT INTO AROSCOP_INT.SUDHA.TOPIC_ASKONE_MASTER (IMPRESSION_ID,IMPRESSION_TIME,ADVERTISERGUID,SURVEY_ID,TOPIC_ID,QUESTION_GUID,ANSWER_GUIDS,COUNTRYID,STATEID,CITYID,GENDER,AGE,HH_INCOME_RNG,ENVIRONMENT,USER_COUNTRY_ID,USER_STATE_ID,USER_CITY_ID,ANSWER_BASED_COUNT,QUESTION_BASED_COUNT,SURVEY_BASED_COUNT,TARGETABLEDOMAIN,ANSWER_TEXT,QR_ID,VERSION,ANSWER_POSITION,NAME,PHONE,EMAIL,ADDRESS,CUSTOM_PARAMS,TOTALOPTIONS,QR_NAME,TOPIC_NAME,QUESTION,ANSWER,SURVEY_NAME,UNIQUEUSER_ID,QUESTION_POSITION,ADVERTISER_NAME,DEVICEOSID,DEVICETYPEID,CONNECTIONTYPEID,BROWSERID,COUNTRYCARRIERID,INSERTED_DATE) 
SELECT A.IMPRESSION_ID,A.IMPRESSION_TIME,A.ADVERTISERGUID,A.SURVEY_ID,A.TOPIC_ID,A.QUESTION_GUID,A.ANSWER_GUIDS,A.COUNTRYID,A.STATEID,A.CITYID,A.GENDER,A.AGE,A.HH_INCOME_RNG,A.ENVIRONMENT,A.USER_COUNTRY_ID,A.USER_STATE_ID,A.USER_CITY_ID,A.ANSWER_BASED_COUNT,A.QUESTION_BASED_COUNT,A.SURVEY_BASED_COUNT,A.TARGETABLEDOMAIN,A.ANSWER_TEXT,A.QR_ID,A.VERSION,A.ANSWER_POSITION,A.NAME,A.PHONE,A.EMAIL,A.ADDRESS,A.CUSTOM_PARAMS,A.TOTALOPTIONS,A.QR_NAME,A.TOPIC_NAME,A.QUESTION,A.ANSWER,A.SURVEY_NAME,A.UNIQUEUSER_ID,A.QUESTION_POSITION,A.ADVERTISER_NAME,A.DEVICEOSID,A.DEVICETYPEID,A.CONNECTIONTYPEID,A.BROWSERID,A.COUNTRYCARRIERID,CURRENT_DATE() FROM 
(SELECT IMPRESSION_ID,IMPRESSION_TIME,ADVERTISERGUID,SURVEY_ID,TOPIC_ID,QUESTION_GUID,ANSWER_GUIDS,COUNTRYID,STATEID,CITYID,GENDER,AGE,HH_INCOME_RNG,ENVIRONMENT,USER_COUNTRY_ID,USER_STATE_ID,USER_CITY_ID,ANSWER_BASED_COUNT,QUESTION_BASED_COUNT,SURVEY_BASED_COUNT,TARGETABLEDOMAIN,ANSWER_TEXT,QR_ID,VERSION,ANSWER_POSITION,NAME,PHONE,EMAIL,ADDRESS,CUSTOM_PARAMS,TOTALOPTIONS,QR_NAME,TOPIC_NAME,QUESTION,ANSWER,SURVEY_NAME,UNIQUEUSER_ID,QUESTION_POSITION,ADVERTISER_NAME,DEVICEOSID,DEVICETYPEID,CONNECTIONTYPEID,BROWSERID,COUNTRYCARRIERID,HASH(IMPRESSION_ID,IMPRESSION_TIME,ADVERTISERGUID,SURVEY_ID,TOPIC_ID,QUESTION_GUID,ANSWER_GUIDS,COUNTRYID,STATEID,CITYID,GENDER,AGE,HH_INCOME_RNG,ENVIRONMENT,USER_COUNTRY_ID,USER_STATE_ID,USER_CITY_ID,ANSWER_BASED_COUNT,QUESTION_BASED_COUNT,SURVEY_BASED_COUNT,TARGETABLEDOMAIN,ANSWER_TEXT,QR_ID,VERSION,ANSWER_POSITION,NAME,PHONE,EMAIL,ADDRESS,CUSTOM_PARAMS,TOTALOPTIONS,QR_NAME,TOPIC_NAME,QUESTION,ANSWER,SURVEY_NAME,UNIQUEUSER_ID,QUESTION_POSITION,ADVERTISER_NAME,DEVICEOSID,DEVICETYPEID,CONNECTIONTYPEID,BROWSERID,COUNTRYCARRIERID) AS HASH_VAL FROM AROSCOP_EXT.SCHEMA_AROSCOP_EXT.ASKONE_REPORTING  WHERE ADVERTISERGUID IN ('<<ADVERTISERGUID_STRING>>')) A 
LEFT JOIN (SELECT IMPRESSION_ID,IMPRESSION_TIME,ADVERTISERGUID,SURVEY_ID,TOPIC_ID,QUESTION_GUID,ANSWER_GUIDS,COUNTRYID,STATEID,CITYID,GENDER,AGE,HH_INCOME_RNG,ENVIRONMENT,USER_COUNTRY_ID,USER_STATE_ID,USER_CITY_ID,ANSWER_BASED_COUNT,QUESTION_BASED_COUNT,SURVEY_BASED_COUNT,TARGETABLEDOMAIN,ANSWER_TEXT,QR_ID,VERSION,ANSWER_POSITION,NAME,PHONE,EMAIL,ADDRESS,CUSTOM_PARAMS,TOTALOPTIONS,QR_NAME,TOPIC_NAME,QUESTION,ANSWER,SURVEY_NAME,UNIQUEUSER_ID,QUESTION_POSITION,ADVERTISER_NAME,DEVICEOSID,DEVICETYPEID,CONNECTIONTYPEID,BROWSERID,COUNTRYCARRIERID,HASH(IMPRESSION_ID,IMPRESSION_TIME,ADVERTISERGUID,SURVEY_ID,TOPIC_ID,QUESTION_GUID,ANSWER_GUIDS,COUNTRYID,STATEID,CITYID,GENDER,AGE,HH_INCOME_RNG,ENVIRONMENT,USER_COUNTRY_ID,USER_STATE_ID,USER_CITY_ID,ANSWER_BASED_COUNT,QUESTION_BASED_COUNT,SURVEY_BASED_COUNT,TARGETABLEDOMAIN,ANSWER_TEXT,QR_ID,VERSION,ANSWER_POSITION,NAME,PHONE,EMAIL,ADDRESS,CUSTOM_PARAMS,TOTALOPTIONS,QR_NAME,TOPIC_NAME,QUESTION,ANSWER,SURVEY_NAME,UNIQUEUSER_ID,QUESTION_POSITION,ADVERTISER_NAME,DEVICEOSID,DEVICETYPEID,CONNECTIONTYPEID,BROWSERID,COUNTRYCARRIERID) AS HASH_VAL FROM  "AROSCOP_INT"."SUDHA"."TOPIC_ASKONE_MASTER") B ON A.HASH_VAL = B.HASH_VAL WHERE B.HASH_VAL IS NULL;


UPDATE AROSCOP_INT.SUDHA.TOPIC_ASKONE_MASTER A 
    SET A.SRCREQUESTID=B.SRCREQUESTID 
    FROM  AROSCOP_EXT.SCHEMA_AROSCOP_EXT.AROSCOP_POSTIMPRESSION_LOG_DETAILS B 
    WHERE A.IMPRESSION_ID=B.IMPRESSIONID AND A.SRCREQUESTID IS NULL;

UPDATE AROSCOP_INT.SUDHA.TOPIC_ASKONE_MASTER A 
 SET
    A.DEVICEID = B.DEVICEID,
 	A.DEVICEMANUFACTURERID = B.DEVICEMANUFACTURERID,
	A.DEVICEMODELID = B.DEVICEMODELID,
    A.IPADDRESS = B.IPADDRESS,
    A.ENDUSERLATITUDEVALUE = B.ENDUSERLATITUDEVALUE,
	A.ENDUSERLONGITUDEVALUE = B.ENDUSERLONGITUDEVALUE,
    A.SUPPLY_SOURCE_TYPE = B.SUPPLY_SOURCE_TYPE,
    A.DEVICETYPE = B.DEVICETYPE,
    A.CENSUS_BLOCK = B.CENSUS_BLOCK,
	A.ISP_NAME = B.ISP_NAME,
	A.DOMAIN_NAME = B.DOMAIN_NAME,
	A.NETSPEED = B.NETSPEED,
	A.MOBILE_BRAND = B.MOBILE_BRAND,
	A.USAGE_TYPE = B.USAGE_TYPE,
	A.CENSUS_BLOCK_20 = B.CENSUS_BLOCK_20 
 FROM AROSCOP_INT.SCHEMA_AROSCOP_INT.AROSCOP_ADSERVING_LOG_DETAILS_ACTIVITY B,(SELECT TO_VARCHAR(ADD_MONTHS(DATE(CURRENT_DATE()), -1), 'YYYY-MM-01') DATE_VALUE ) C
 WHERE A.SRCREQUESTID = B.REQUESTID AND DATE(B.INJECTDATE) >=  C.DATE_VALUE ;
 	
UPDATE AROSCOP_INT.SUDHA.TOPIC_ASKONE_MASTER A SET CONNECTIONTYPE_DESC = DESCRIPTION FROM AROSCOP_EXT.SCHEMA_AROSCOP_EXT.AROSCOP_META_CONNECTIONTYPE B WHERE A.CONNECTIONTYPEID=B.ID;
 
UPDATE AROSCOP_INT.SUDHA.TOPIC_ASKONE_MASTER A SET APPSITE_DESC = DESCRIPTION FROM AROSCOP_EXT.SCHEMA_AROSCOP_EXT.AROSCOP_META_APPSITE B WHERE A.SUPPLY_SOURCE_TYPE=B.ID;
 
UPDATE AROSCOP_INT.SUDHA.TOPIC_ASKONE_MASTER A SET DEVICETYPE_DESC = DESCRIPTION FROM AROSCOP_EXT.SCHEMA_AROSCOP_EXT.AROSCOP_META_DEVICETYPE B WHERE A.DEVICETYPE=B.ID;	

UPDATE "AROSCOP_INT"."SUDHA"."ASKONE_REPORTING_MASTER_QUEUE" SET DAILY_EXECUTION_FLAG =  'N';

UPDATE "AROSCOP_INT"."SUDHA"."ASKONE_REPORTING_MASTER_QUEUE" A 
SET DAILY_EXECUTION_FLAG =  'Y'
FROM (SELECT TOPIC_ID,TOPIC_NAME,COUNT(*) FROM "AROSCOP_INT"."SUDHA"."TOPIC_ASKONE_MASTER" WHERE SRCREQUESTID IS NULL OR IPADDRESS IS NULL
GROUP BY 1,2) B
WHERE  UPPER(TRIM(A.TOPIC_ID)) = UPPER(TRIM(B.TOPIC_ID))AND UPPER(TRIM(A.TOPIC_NAME)) = UPPER(TRIM(B.TOPIC_NAME));		   
		   
UPDATE "AROSCOP_INT"."SUDHA"."ASKONE_REPORTING_MASTER_QUEUE" 
       SET LAST_UPDATED_LOG_ID =  <<CURRENT_LATEST_LOG_ID>>,
           LAST_UPDATED_DATE =  CURRENT_TIMESTAMP 
		   WHERE DAILY_EXECUTION_FLAG =  'Y' ;
		   
COPY INTO '@"AROSCOP_INT"."SUDHA"."SKYANALYST"/AROSCOP_INT/ASKONE/ASKONE_TOPIC/TOPIC_ASKONE_OVERALL.bz2' from (
SELECT * FROM "AROSCOP_INT"."SUDHA"."TOPIC_ASKONE_MASTER" QUALIFY ROW_NUMBER() OVER( PARTITION BY  TOPIC_NAME,IMPRESSION_ID ORDER BY IMPRESSION_TIME ) = 1 
) FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=TRUE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;
		   
		   
		   