CREATE OR REPLACE TABLE SCIERA_SUBSYSTEM.SKY_OP.WIP_CURRENT_BACKUP CLONE V4_CTELL.PROC.WIP_CURRENT;

COPY INTO V4_CTELL.TEST.COX_DELIVERY_WEEKLY_RESULTS (FP_KEY, SERVICENAME, MAX_SPEED, CHECK_DATE, S3FILENAME) FROM (SELECT t.$1,t.$2,t.$3,t.$4,metadata$filename FROM'@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/cox/weekly_results_from_sf_for_delivery/<<DT_PATH>>/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 1,FIELD_OPTIONALLY_ENCLOSED_BY = '"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE ;

UPDATE V4_CTELL.TEST.COX_DELIVERY_WEEKLY_RESULTS 
SET DT=REGEXP_SUBSTR(S3FILENAME, '[0-9]{4}[0-9]{2}[0-9]{2}')
WHERE DT IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A SET DELIVERED_DATE = '<<DELIVERED_DATE>>' FROM (SELECT FP_KEY,SERVICENAME,MIN(CHECK_DATE) CHECK_DATE FROM V4_CTELL.TEST.COX_DELIVERY_WEEKLY_RESULTS WHERE DT = '<<DT>>' GROUP BY 1,2) B WHERE A.FP_KEY = B.FP_KEY AND A.SERVICENAME = B.SERVICENAME AND B.CHECK_DATE >= A.SCHEDULEDATE AND A.MSO = 'COX' AND A.SCHEDULEDATE >= '2023-06-01' AND DELIVERED_DATE IS NULL AND A.STATUS IS NOT NULL; 

COPY INTO V4_CTELL.TEST.COX_PRE_SERV_DELIVERY_WEEKLY_RESULTS (FP_KEY, SERVICENAME, MAX_SPEED, CHECK_DATE, S3FILENAME) FROM (SELECT t.$1,t.$2,t.$3,t.$4,metadata$filename FROM'@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/cox-pre-serv/weekly_results_from_sf_for_delivery/<<DT_PATH>>/' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 1,FIELD_OPTIONALLY_ENCLOSED_BY = '"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE ;

UPDATE V4_CTELL.TEST.COX_PRE_SERV_DELIVERY_WEEKLY_RESULTS 
SET DT=REGEXP_SUBSTR(S3FILENAME, '[0-9]{4}[0-9]{2}[0-9]{2}')
WHERE DT IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A SET DELIVERED_DATE = '<<DELIVERED_DATE>>' FROM (SELECT FP_KEY,SERVICENAME,MIN(CHECK_DATE) CHECK_DATE FROM V4_CTELL.TEST.COX_PRE_SERV_DELIVERY_WEEKLY_RESULTS WHERE DT = '<<DT>>' GROUP BY 1,2) B WHERE A.FP_KEY = B.FP_KEY AND A.SERVICENAME = B.SERVICENAME AND B.CHECK_DATE >= A.SCHEDULEDATE AND A.MSO = 'COX' AND A.SCHEDULEDATE >= '2023-06-01' AND DELIVERED_DATE IS NULL AND A.STATUS IS NOT NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT
SET DELIVERED_YEAR= YEAR(CAST(DELIVERED_DATE AS DATE)) WHERE DELIVERED_YEAR IS NULL AND DELIVERED_DATE IS NOT NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT
SET DELIVERED_MONTH=MONTH(CAST(DELIVERED_DATE AS DATE)) WHERE DELIVERED_MONTH IS NULL AND DELIVERED_DATE IS NOT NULL;
