CREATE OR REPLACE TABLE V4_CTELL.TEST.COMCAST_DELIVERY_ROLLUP_STAGING AS
SELECT DT, HOUSE_KEY, OB_NAME AS PROVIDER, OB_MAXSPEED AS MAX_SPEED, CHECKFLAG, CHECKDATE,CAST('OB' AS VARCHAR) PROVIDER_TYPE 
FROM USCS.DELIVERY.COMCAST_DELIVERY_OB_RESULTS WHERE DT = '<<yyyymm>>';

INSERT INTO V4_CTELL.TEST.COMCAST_DELIVERY_ROLLUP_STAGING
SELECT DT, HOUSE_KEY, ILEC, MAXSPEED, ADDRESSCHECK, CHECKDATE,'ILEC' PROVIDER_TYPE 
FROM  USCS.DELIVERY.COMCAST_DELIVERY_ILEC_RESULTS 
WHERE UPPER(ILEC) IN ('ATT','CENTURYLINK','VERIZON','FRONTIER','WINDSTREAM','BRIGHTSPEED') AND DT = '<<yyyymm>>';

ALTER TABLE V4_CTELL.TEST.COMCAST_DELIVERY_ROLLUP_STAGING
ADD COLUMN H1  VARCHAR(16777216),
          H2  VARCHAR(16777216),
          SCIERA_DMA  VARCHAR(16777216),
          ZIP5 VARCHAR(16777216),
          ZIP4 VARCHAR(16777216),
          DWELL_TYPE  VARCHAR(16777216);

UPDATE V4_CTELL.TEST.COMCAST_DELIVERY_ROLLUP_STAGING A
SET A.H1 = B.H1,
    A.H2 = B.H2,
    A.SCIERA_DMA = B.SCIERA_DMA,
    A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.DWELL_TYPE = UPPER(B.DWELL_TYPE)
FROM "MSO"."V3_COMCAST_RESOURCE"."FP" B
WHERE A.HOUSE_KEY = B.HOUSEKEY AND IFNULL(B.DELETE_DATE,'')=''
AND UPPER(B.H1) IN ('WEST DIVISION','NORTHEAST DIVISION','CENTRAL DIVISION') AND UPPER(B.DWELL_TYPE) IN ('HOME', 'APT')
;

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."COMCAST_DELIVERY_FIBER_SUMMARY"
SELECT  PROVIDER,CHECKFLAG,PROVIDER_TYPE,H1 AS DIVISION,DWELL_TYPE,DT,COUNT(*) AS COUNT
 FROM V4_CTELL.TEST.COMCAST_DELIVERY_ROLLUP_STAGING WHERE TRY_CAST(MAX_SPEED AS DOUBLE)>=300 GROUP BY  PROVIDER,CHECKFLAG,PROVIDER_TYPE,H1,DWELL_TYPE,DT;
