CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING" AS
SELECT *,IFF(MAX_SPEED>=300,'Y',NULL) AS IS_FIBER_ZIP9,IFF(ZIP9_CHECKED>0,'Y',NULL) AS IS_ZIP9_CHECKED,
IFF(ZIP9_DELIVERED>0,'Y',NULL) AS IS_ZIP9_DELIVERED FROM 
(SELECT IFF(BUDGET_YEAR IS NULL,QUEUE_YEAR,BUDGET_YEAR) BUDGET_YEAR ,IFF(BUDGET_MONTH IS NULL,QUEUE_MONTH,BUDGET_MONTH) BUDGET_MONTH,REPLACE(REPLACE(REPLACE(RTRIM(SERVICENAME), '111', ' '),'222',','),'333','.') as SERVICENAME,DMA,H1,ZIP5,ZIP4,REGION,
sum(IFF(PROJECT_TYPE='BL',1,0)) as BAU,sum(IFF(PROJECT_TYPE='NQ',1,0)) as NQ,
sum(IFF(PROJECT_TYPE='WL',1,0)) as WL,
SUM(IFF(CHECK_DATE is not NULL,1,0)) ZIP9_CHECKED, 
SUM(IFF(DELIVERED_DATE is not NULL,1,0)) ZIP9_DELIVERED, 
 MAX(CAST (MAX_SPEED AS DOUBLE)) AS MAX_SPEED,
FROM "V4_CTELL"."PROC"."WIP_CURRENT" WHERE MSO = 'COMCAST'  GROUP BY 1,2,3,4,5,6,7,8);

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_1" AS
SELECT A.*,B.HOME_PASSED FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING" A
LEFT JOIN (SELECT H1,SCIERA_DMA, SCIERA_ZIP5,SCIERA_ZIP4,H2,COUNT(*) AS HOME_PASSED
FROM "MSO"."V3_COMCAST_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='' GROUP BY 1,2,3,4,5) B 
ON A.DMA = B.SCIERA_DMA AND A.ZIP5 = B.SCIERA_ZIP5 AND A.ZIP4 = B.SCIERA_ZIP4 AND A.REGION = B.H2 AND A.H1 =B.H1;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,SERVICENAME,DMA,H1,ZIP5,REGION,SUM(BAU) BAU,SUM(NQ) NQ,SUM(WL) WL,
COUNT(DISTINCT IFF(IS_FIBER_ZIP9 = 'Y',CONCAT(ZIP5,ZIP4),NULL)) AS FIBER_ZIP9,
COUNT(DISTINCT IFF(IS_ZIP9_CHECKED = 'Y',CONCAT(ZIP5,ZIP4),NULL)) ZIP_CHECKED,
COUNT(DISTINCT IFF(IS_ZIP9_DELIVERED = 'Y',CONCAT(ZIP5,ZIP4),NULL)) ZIP_DELIVERED,
SUM(IFF(IS_FIBER_ZIP9 = 'Y',HOME_PASSED,0)) AS ACTUAL_HP FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_1"
GROUP BY 1,2,3,4,5,6,7;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_3" AS
SELECT A.*,COALESCE(BAU,0) BAU,COALESCE(NQ,0) NQ,COALESCE(WL,0) WL,COALESCE(FIBER_ZIP9,0) FIBER_ZIP9,COALESCE(ZIP_CHECKED,0) ZIP_CHECKED
,COALESCE(ZIP_DELIVERED,0) ZIP_DELIVERED,COALESCE(ACTUAL_HP,0) ACTUAL_HP FROM (SELECT * FROM 
 (SELECT EXTRACT(YEAR FROM DATEADD(MONTH, seq4(), TO_DATE('2022-01-01'))) AS BUDGET_YEAR,
        EXTRACT(MONTH FROM DATEADD(MONTH, seq4(), TO_DATE('2022-01-01'))) AS BUDGET_MONTH
    FROM TABLE(GENERATOR(ROWCOUNT => 12 * (YEAR(CURRENT_DATE()) - 2022  + 1)))) YEAR_MONTH_GEN
CROSS JOIN (SELECT DISTINCT SERVICENAME,DMA,H1,ZIP5,REGION FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2" ) DIST_NAME
) A
LEFT JOIN "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2" B
ON A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND A.SERVICENAME = B.SERVICENAME 
AND A.DMA = B.DMA AND A.H1 = B.H1 AND A.ZIP5 = B.ZIP5 AND A.REGION = B.REGION;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED" AS
SELECT *,COALESCE(LAG(ACTUAL_HP,1) OVER( PARTITION BY SERVICENAME,DMA,H1,ZIP5,REGION ORDER BY BUDGET_YEAR,BUDGET_MONTH ),0) MOM_HP,
COALESCE(LAG(ACTUAL_HP,3) OVER( PARTITION BY SERVICENAME,DMA,H1,ZIP5 ORDER BY BUDGET_YEAR,BUDGET_MONTH ),0) MO3M_HP
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_3" ;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED"
ADD COLUMN INCLUDE VARCHAR(16777216) DEFAULT 'N';

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED" A
SET A.INCLUDE = B.INCLUDE
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."COMCAST_DMA_REGION_VALIDATION" B
WHERE A.DMA = B.DMA AND A.H1 = B.DIVISION AND A.REGION = B.REGION;

DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING";
DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_1";
DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2";
DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_3";

