CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT"  AS
SELECT SITE_ID,HOUSE_NBR,ILEC_NAME AS PROVIDER_NAME ,ILEC_MAX_SPEED AS MAX_SPEED,ILEC_FIBER_TV AS FIBER_TV,HOME_MAX_SPEED,FIBER_TV_AVAILABLE,'ILEC' AS PROVIDER FROM  "V4_CTELL"."DELIVERIES"."COX_DELIVERY" WHERE DELIVERED_DATE = '<<DELIVERED_DATE>>' ;

INSERT INTO "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" (SITE_ID,HOUSE_NBR,PROVIDER_NAME ,MAX_SPEED,FIBER_TV,PROVIDER)
SELECT SITE_ID,HOUSE_NBR,OB1_NAME ,OB1_MAX_SPEED,OB1_FIBER_TV,'OB' AS PROVIDER FROM  "V4_CTELL"."DELIVERIES"."COX_DELIVERY" WHERE DELIVERED_DATE = '<<DELIVERED_DATE>>' AND OB1_NAME<>'' AND OB1_NAME IS NOT NULL;

INSERT INTO "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" (SITE_ID,HOUSE_NBR,PROVIDER_NAME ,MAX_SPEED,FIBER_TV,PROVIDER)
SELECT SITE_ID,HOUSE_NBR,OB2_NAME ,OB2_MAX_SPEED,OB2_FIBER_TV,'OB' AS PROVIDER  FROM  "V4_CTELL"."DELIVERIES"."COX_DELIVERY" WHERE DELIVERED_DATE = '<<DELIVERED_DATE>>' AND OB2_NAME<>'' AND OB2_NAME IS NOT NULL;

ALTER TABLE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" 
ADD COLUMN H2 VARCHAR(16777216) DEFAULT NULL,
 REGION VARCHAR(16777216) DEFAULT NULL,
 SYSTEM VARCHAR(16777216) DEFAULT NULL;

UPDATE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" A
SET A.H2 = B.H2
FROM "MSO"."V3_COX_RESOURCE"."FP" B
WHERE  A.SITE_ID = B.H1 AND A.HOUSE_NBR = B.H6 AND IFNULL(B.DELETE_DATE,'')='' ;

UPDATE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" A
SET A.H2 = B.H2
FROM "MSO"."V3_COX_RESOURCE"."FP" B
WHERE  A.SITE_ID = B.H1 AND A.HOUSE_NBR = B.H6 AND A.H2 IS NULL ;

UPDATE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" A
SET A.REGION = B.REGION,
    A.SYSTEM = B.SYSTEM
FROM "V4_CTELL"."TEST"."SUB_SYSTEM_MAPPING" B
WHERE A.H2 = B.H2 AND A.REGION IS NULL;

UPDATE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" A
SET A.PROVIDER_NAME = UPPER(A.PROVIDER_NAME);

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_INTERMEDIATE" AS
SELECT REGION,SYSTEM,HOUSE_NBR,SITE_ID,MAX(CAST(MAX_SPEED AS DOUBLE)) AS MAX_SPEED, MAX(FIBER_TV) FIBER_TV
FROM "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" 
WHERE  NOT(PROVIDER_NAME = 'TMOBILE5G-HOME') AND	
NOT(PROVIDER_NAME = 'VERIZON 5G')	
GROUP BY REGION,SYSTEM,HOUSE_NBR,SITE_ID; 

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_ROLLUP" AS
SELECT REGION,SYSTEM,COUNT(DISTINCT HOUSE_NBR) HOUSE_NBR,MAX(CAST(MAX_SPEED AS INT)) AS MAX_SPEED,
SUM(IFF( CAST(MAX_SPEED AS DOUBLE)=0,1,0)) AS NO_HSI,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>0 AND CAST(MAX_SPEED AS DOUBLE)<=10,1,0)) AS LTE_10,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>10 AND CAST(MAX_SPEED AS DOUBLE)<=18,1,0)) AS LTE_18,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>18 AND CAST(MAX_SPEED AS DOUBLE)<=25,1,0)) AS LTE_25,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>25 AND CAST(MAX_SPEED AS DOUBLE)<=45,1,0)) AS LTE_45,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>45 AND CAST(MAX_SPEED AS DOUBLE)<=74,1,0)) AS LTE_74,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>74 AND CAST(MAX_SPEED AS DOUBLE)<=100,1,0)) AS LTE_100,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>100 AND CAST(MAX_SPEED AS DOUBLE)<=299,1,0)) AS LTE_299,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>299 AND CAST(MAX_SPEED AS DOUBLE)<=749,1,0)) AS LTE_749,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>749 AND CAST(MAX_SPEED AS DOUBLE)<=900,1,0)) AS LTE_999,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>900 AND CAST(MAX_SPEED AS DOUBLE)<=1999,1,0)) AS LTE_1000,
SUM(IFF(CAST(MAX_SPEED  AS DOUBLE)>1999,1,0)) AS EQ_2000_PLUS,
SUM(IFF(FIBER_TV<>'' AND FIBER_TV<>'NO' AND FIBER_TV<>'N' AND FIBER_TV<>'N' AND FIBER_TV<>'0' ,1,0)) AS FIBER_TV_AVAILABLE
FROM "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_INTERMEDIATE" 
GROUP BY REGION,SYSTEM;

CREATE OR REPLACE TABLE "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_PROVIDER_ROLLUP" AS
SELECT REGION,SYSTEM,PROVIDER_NAME,PROVIDER,COUNT(DISTINCT HOUSE_NBR) HOUSE_NBR,MAX(CAST(MAX_SPEED AS DOUBLE)) AS MAX_SPEED,
SUM(IFF( CAST(MAX_SPEED AS DOUBLE)=0,1,0)) AS NO_HSI,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>0 AND CAST(MAX_SPEED AS DOUBLE)<=10,1,0)) AS LTE_10,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>10 AND CAST(MAX_SPEED AS DOUBLE)<=18,1,0)) AS LTE_18,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>18 AND CAST(MAX_SPEED AS DOUBLE)<=25,1,0)) AS LTE_25,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>25 AND CAST(MAX_SPEED AS DOUBLE)<=45,1,0)) AS LTE_45,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>45 AND CAST(MAX_SPEED AS DOUBLE)<=74,1,0)) AS LTE_74,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>74 AND CAST(MAX_SPEED AS DOUBLE)<=100,1,0)) AS LTE_100,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>100 AND CAST(MAX_SPEED AS DOUBLE)<=299,1,0)) AS LTE_299,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>299 AND CAST(MAX_SPEED AS DOUBLE)<=749,1,0)) AS LTE_749,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>749 AND CAST(MAX_SPEED AS DOUBLE)<=900,1,0)) AS LTE_999,
SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>900 AND CAST(MAX_SPEED AS DOUBLE)<=1999,1,0)) AS LTE_1000,
SUM(IFF(CAST(MAX_SPEED  AS DOUBLE)>1999,1,0)) AS EQ_2000_PLUS,
SUM(IFF(FIBER_TV<>'' AND FIBER_TV<>'NO' AND FIBER_TV<>'N' AND FIBER_TV<>'N' AND FIBER_TV<>'0' ,1,0)) AS FIBER_TV_AVAILABLE
FROM "V4_CTELL"."TEST"."COX_MONTHLY_REPORT" 
GROUP BY REGION,SYSTEM,PROVIDER_NAME,PROVIDER;

DELETE FROM "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_PROVIDER_ROLLUP"
WHERE (PROVIDER_NAME = 'WINDSTREAM' AND SYSTEM = 'KANSAS') OR
(PROVIDER_NAME = 'TMOBILE5G-HOME') OR	
(PROVIDER_NAME = 'VERIZON 5G') OR	
(PROVIDER_NAME = 'GOOGLE FIBER' AND SYSTEM = 'SAN DIEGO');

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."COX_MONTHLY_REPORT_PROVIDER_ROLLUP"
SELECT *,'<<DELIVERED_DATE>>' AS DT, CURRENT_DATE FROM "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_PROVIDER_ROLLUP";

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."COX_MONTHLY_REPORT_ROLLUP"
SELECT *,'<<DELIVERED_DATE>>' AS DT, CURRENT_DATE FROM "V4_CTELL"."TEST"."COX_MONTHLY_REPORT_ROLLUP";

