-------------- INTERMEDIATE TO CREATE COUNTS -------------------
CREATE TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_FCC_LIST" AS
 SELECT DISTINCT FRN,BRAND_NAME,BLOCK_GEOID FROM "SCIERA_SUBSYSTEM"."NATIONAL_RES"."FCC_FABRIC_LATEST" 
 
 ALTER TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_FCC_LIST" 
ADD MSO VARCHAR(16777216),
 STD_NAME VARCHAR(16777216);
 
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_FCC_LIST"
 SET MSO = 'CHARTER'
 FROM (SELECT DISTINCT SCIERA_CB FROM "MSO"."V3_CHARTER_RESOURCE"."FP" WHERE DELETE_DATE ='' OR DELETE_DATE IS NULL ) B
 WHERE BLOCK_GEOID = SCIERA_CB;
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_FCC_LIST"
 SET MSO = 'OTHERS'
  WHERE MSO IS NULL;
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_FCC_LIST" A
 SET A.STD_NAME = B.STD_NAME
 FROM (SELECT DISTINCT FRN,STD_NAME FROM "SCIERA_SUBSYSTEM"."SKY_OP_FCC"."MASTER_STD_NAME_FRN_DETAIL" ) B
  WHERE A.FRN = B.FRN AND A.STD_NAME IS NULL;
 
-------------------------  CHARTER_PROVIDER_TRACKER -----------
 CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" AS
 SELECT DISTINCT SERVICENAME,STD_NAME FROM "V4_CTELL"."PROC"."WIP_CURRENT" ;
 
 
 INSERT INTO "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" (SERVICENAME,STD_NAME)
 VALUES ('HUNTER COMMUNICATIONS','HUNTER COMMUNICATIONS');
 
 ---- No need to Run these
 ALTER TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" 
ADD STD_NAME VARCHAR(16777216);
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER"
 SET STD_NAME = B.STD_NAME
 FROM "SCIERA_SUBSYSTEM"."SKY_OP"."MASTER_STD_NAME_CTELL" B
 WHERE UPPER(SERVICENAME) = UPPER(PUBLISH_NAME) ;
 ------------------------
 ALTER TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" 
ADD OB_ID VARCHAR(16777216);
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" A
 SET A.OB_ID = B.OB_ID
 FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_OB_MASTER" B
 WHERE  REPLACE(REPLACE(REPLACE(REPLACE(A.SERVICENAME,'111',' '),'222',', '),'333','.'),'  ',' ') = UPPER(B.OB_NAME);
 
 
 ALTER TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" 
ADD CHARTER_CB_FABRIC_COUNT VARCHAR(16777216),
 OTHERS_CB_FABRIC_COUNT VARCHAR(16777216);
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" A
 SET CHARTER_CB_FABRIC_COUNT = B.CHARTER_COUNT,
     OTHERS_CB_FABRIC_COUNT = B.OTHERS_COUNT
 FROM (SELECT STD_NAME, SUM(CASE WHEN MSO = 'CHARTER' THEN CNT ELSE 0 END ) CHARTER_COUNT,
  SUM(CASE WHEN MSO = 'OTHERS' THEN CNT ELSE 0 END ) OTHERS_COUNT
FROM 
 (SELECT STD_NAME,MSO,COUNT(DISTINCT BLOCK_GEOID) AS CNT FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_FCC_LIST" GROUP BY 1,2) GROUP BY 1
 ) B
 WHERE A.STD_NAME = B.STD_NAME ;
 
 
 ALTER TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" 
ADD RESI_SCRIPT_AVAILABLE VARCHAR(16777216),
 SMB_SCRIPT_AVAILABLE VARCHAR(16777216),
 BUDGET_TYPE VARCHAR(16777216);
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" A
 SET RESI_SCRIPT_AVAILABLE =CASE WHEN UPPER(B.RESI_SCRIPTING_STATUS) ='IN PROD' THEN 'Y' ELSE NULL END,
     SMB_SCRIPT_AVAILABLE = CASE WHEN UPPER(B.SMB_SCRIPTING_STATUS) ='IN PROD' THEN 'Y' ELSE NULL END 
 FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CTEL_SOURCE_MASTER" B
 WHERE  A.SERVICENAME = B.PUBLISH_NAME;
 
 UPDATE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER" A
 SET BUDGET_TYPE = CASE WHEN SERVICENAME = 'ATT' THEN  'ATT' 
                        WHEN SERVICENAME IN ('TMOBILE5G-FIBER','TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                        ELSE 'NON ATT' END ;
 
 
CREATE TABLE "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER_BAK" CLONE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
  CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER" AS
SELECT *,ROW_NUMBER() OVER(PARTITION BY STD_NAME ORDER BY RESI_SCRIPT_AVAILABLE,SMB_SCRIPT_AVAILABLE,OB_ID ) AS RNK FROM "SCIERA_SUBSYSTEM"."SKY_OP"."CHARTER_PROVIDER_TRACKER"


UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET RNK = 2 WHERE STD_NAME='T-MOBILE FIBER'
 
 UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET RESI_SCRIPT_AVAILABLE = 'Y',
    RNK = 1
WHERE SERVICENAME='TEC';

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET RNK = 2
WHERE SERVICENAME='SOUTHERN111PINE111ELECTRIC';
 
 
 UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET RESI_SCRIPT_AVAILABLE = 'N'
WHERE RESI_SCRIPT_AVAILABLE IS NULL;

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET SMB_SCRIPT_AVAILABLE = 'N'
WHERE SMB_SCRIPT_AVAILABLE IS NULL;


UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET CHARTER_CB_FABRIC_COUNT = 0
WHERE CHARTER_CB_FABRIC_COUNT IS NULL;

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."CHARTER_PROVIDER_TRACKER"
SET OTHERS_CB_FABRIC_COUNT = 0
WHERE OTHERS_CB_FABRIC_COUNT IS NULL;

