
TRUNCATE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN";

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE,RECEIVED_COUNT,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP)
SELECT TRY_CAST(BUDGET_YEAR AS INT), TRY_CAST(BUDGET_MONTH AS INT),
CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,TASK_NAME,INPUT_CLIENT_NAME,TRY_CAST(DATE_CREATED AS DATE),TRY_CAST(SPLIT_PART(T1.VALUE,'=',2) AS INT),PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,TRIM(SPLIT_PART(T1.VALUE,'=',1)) AS ZIP FROM  "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."COX_BUDGET_PLAN" , 
    LATERAL SPLIT_TO_TABLE(ZIP_EXP, ',') AS T1 WHERE INPUT_TYPE = 'ZIP5_LEVEL';

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE,RECEIVED_COUNT,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP)
SELECT TRY_CAST(BUDGET_YEAR AS INT), TRY_CAST(BUDGET_MONTH AS INT),
CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,TASK_NAME,INPUT_CLIENT_NAME,TRY_CAST(DATE_CREATED AS DATE),TARGET_VOLUME,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP FROM  "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."COX_BUDGET_PLAN" WHERE INPUT_TYPE <> 'ZIP5_LEVEL';	

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE,RECEIVED_COUNT,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP,DIVISION)
SELECT TRY_CAST(BUDGET_YEAR AS INT), TRY_CAST(BUDGET_MONTH AS INT),
CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,TASK_NAME,INPUT_CLIENT_NAME,TRY_CAST(DATE_CREATED AS DATE),TRY_CAST(SPLIT_PART(T1.VALUE,'=',2) AS INT),PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,TRIM(SPLIT_PART(T1.VALUE,'=',1)) AS ZIP,DIVISION FROM  "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."COMCAST_BUDGET_PLAN" , 
    LATERAL SPLIT_TO_TABLE(ZIP_EXP, ',') AS T1 WHERE INPUT_TYPE = 'ZIP5_LEVEL';

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE,RECEIVED_COUNT,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP,DIVISION)
SELECT TRY_CAST(BUDGET_YEAR AS INT), TRY_CAST(BUDGET_MONTH AS INT),
CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,INPUT_TYPE,TASK_ID,TASK_NAME,INPUT_CLIENT_NAME,TRY_CAST(DATE_CREATED AS DATE),TARGET_VOLUME,PROJECT_NAME,PROVIDER_NAME,PUBLISH_NAME,DELIVERY_NAME,ZIP,DIVISION FROM  "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."COMCAST_BUDGET_PLAN" WHERE INPUT_TYPE <> 'ZIP5_LEVEL';	

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (MSO,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,INPUT_TYPE,RECEIVED_DATE,RECEIVED_COUNT)
SELECT 'CHARTER' MSO,NEW_PUBLISH_NAME,PROJECT_NAME  INPUT_FILE_NAME ,COMPETITOR INPUT_CLIENT_NAME,
CASE WHEN DAY(CAST(EXTRACT_DATE AS DATE)) < 25 THEN  YEAR(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) )) 
                          ELSE YEAR(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) + INTERVAL '1 MONTH'))  END BUDGET_YEAR,
CASE WHEN DAY(CAST(EXTRACT_DATE AS DATE)) < 25 THEN  MONTH(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) ))  
                          ELSE MONTH(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) + INTERVAL '1 MONTH'))  END BUDGET_MONTH,
CASE WHEN UPPER(NEW_PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(NEW_PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,
'RESI' ENGAGEMENT_TYPE,
'HOUSKEY_LEVEL' INPUT_TYPE,
CAST(EXTRACT_DATE AS DATE) RECEIVED_DATE,
COUNT(*) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI" 
GROUP BY MSO,NEW_PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,
INPUT_TYPE,RECEIVED_DATE ;

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (MSO,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,INPUT_TYPE,RECEIVED_DATE,RECEIVED_COUNT)
SELECT 'CHARTER_BUSINESS' MSO,NEW_PUBLISH_NAME,PROJECT_NAME  INPUT_FILE_NAME ,COMPETITOR INPUT_CLIENT_NAME,
CASE WHEN DAY(CAST(EXTRACT_DATE AS DATE)) < 25 THEN  YEAR(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) )) 
                          ELSE YEAR(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) + INTERVAL '1 MONTH'))  END BUDGET_YEAR,
CASE WHEN DAY(CAST(EXTRACT_DATE AS DATE)) < 25 THEN  MONTH(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) ))  
                          ELSE MONTH(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) + INTERVAL '1 MONTH'))  END BUDGET_MONTH,
CASE WHEN UPPER(NEW_PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(NEW_PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,
'SMB' ENGAGEMENT_TYPE,
'HOUSKEY_LEVEL' INPUT_TYPE,
CAST(EXTRACT_DATE AS DATE) RECEIVED_DATE,
COUNT(*) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_SMB" 
GROUP BY MSO,NEW_PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,
INPUT_TYPE,RECEIVED_DATE ;


INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" (MSO,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,INPUT_TYPE,RECEIVED_DATE,RECEIVED_COUNT)
SELECT 'CHARTER' MSO,NEW_PUBLISH_NAME,PROJECT_NAME  INPUT_FILE_NAME ,COMPETITOR INPUT_CLIENT_NAME,
CASE WHEN DAY(CAST(EXTRACT_DATE AS DATE)) < 25 THEN  YEAR(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) )) 
                          ELSE YEAR(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) + INTERVAL '1 MONTH'))  END BUDGET_YEAR,
CASE WHEN DAY(CAST(EXTRACT_DATE AS DATE)) < 25 THEN  MONTH(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) ))  
                          ELSE MONTH(DATE_TRUNC('MONTH', CAST(EXTRACT_DATE AS DATE) + INTERVAL '1 MONTH'))  END BUDGET_MONTH,
CASE WHEN UPPER(NEW_PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(NEW_PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,
'RESI' ENGAGEMENT_TYPE,
'CB_LEVEL' INPUT_TYPE,
CAST(EXTRACT_DATE AS DATE) RECEIVED_DATE,
SUM(COUNT_PER_CB) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."CTEL"."DEEPDIVE_MASTER_TABLE_RESI_CB" 
GROUP BY MSO,NEW_PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,ENGAGEMENT_TYPE,
INPUT_TYPE,RECEIVED_DATE;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" A
SET A.PROJECT_NAME = CASE WHEN A.PROJECT_NAME IS NULL THEN B.PROJECTNAME ELSE A.PROJECT_NAME END,
    A.SCHEDULE_DATE = B.SCHEDULEDATE,
    A.QUEUED = B.QUEUED,
    A.CHECKED = B.CHECKED,
    A.DELIVERED = B.DELIVERED,
    A.UNDELIVERABLE = B.UNDELIVERABLE,
    A.FIBER_COUNT =B.FIBER_COUNT
FROM (SELECT MSO,SERVICENAME,PROJECTNAME,ZIP5,MIN(SCHEDULEDATE) SCHEDULEDATE,COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300,1,0)) AS FIBER_COUNT FROM "V4_CTELL"."PROC"."WIP_CURRENT" 
 GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,SERVICENAME,PROJECTNAME,ZIP5) B    
WHERE A.MSO = B.MSO AND UPPER(A.PUBLISH_NAME) = UPPER(B.SERVICENAME)
 AND  ( UPPER(A.PROJECT_NAME) = UPPER(B.PROJECTNAME) 
       OR UPPER(A.INPUT_FILE_NAME) LIKE '%' || UPPER(B.PROJECTNAME)||'%'
 OR  UPPER(B.PROJECTNAME) LIKE '%' || UPPER(A.INPUT_FILE_NAME)||'%'
)
 AND A.ZIP = B.ZIP5 AND A.INPUT_TYPE = 'ZIP5_LEVEL';


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" A
SET A.PROJECT_NAME = CASE WHEN A.PROJECT_NAME IS NULL THEN B.PROJECTNAME ELSE A.PROJECT_NAME END,
    A.SCHEDULE_DATE = B.SCHEDULEDATE,
    A.QUEUED = B.QUEUED,
    A.CHECKED = B.CHECKED,
    A.DELIVERED = B.DELIVERED,
    A.UNDELIVERABLE = B.UNDELIVERABLE,
    A.FIBER_COUNT =B.FIBER_COUNT
FROM (SELECT MSO,SERVICENAME,PROJECTNAME,MIN(SCHEDULEDATE) SCHEDULEDATE,COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300,1,0)) AS FIBER_COUNT FROM "V4_CTELL"."PROC"."WIP_CURRENT" 
 GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,SERVICENAME,PROJECTNAME) B    
WHERE A.MSO = B.MSO AND UPPER(A.PUBLISH_NAME) = UPPER(B.SERVICENAME)
 AND  (UPPER(A.PROJECT_NAME) = UPPER(B.PROJECTNAME)
  OR UPPER(A.INPUT_FILE_NAME) LIKE '%' || UPPER(B.PROJECTNAME)||'%'
 OR  UPPER(B.PROJECTNAME) LIKE '%' || UPPER(A.INPUT_FILE_NAME)||'%' )
 AND A.INPUT_TYPE <> 'ZIP5_LEVEL';	
 
 
 UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN"  A
SET A.READY_FOR_DELIVERY = CHECKED - DELIVERED - UNDELIVERABLE;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" 
SET PROJECT_TYPE = CASE WHEN UPPER(SUBSTR(PROJECT_NAME,1,1))='B'  THEN 'BL'
                        WHEN UPPER(SUBSTR(PROJECT_NAME,1,1))='D' OR 
                             UPPER(SUBSTR(PROJECT_NAME,1,2))='NQ'  THEN 'NQ'
                        WHEN UPPER(SUBSTR(PROJECT_NAME,1,1))='W' THEN 'WL'
                        WHEN UPPER(SUBSTR(PROJECT_NAME,1,2))='A_' THEN 'AH'
                        ELSE NULL END
WHERE PROJECT_TYPE IS NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN"
SET SOW = 'CORPORATE'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISH_NAME IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND DIVISION IN ('NORTHEAST DIVISION','CENTRAL DIVISION');

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN"
SET SOW = 'NED'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISH_NAME NOT IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND DIVISION = 'NORTHEAST DIVISION';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN"
SET SOW = 'CENTRAL'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISH_NAME NOT IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND DIVISION = 'CENTRAL DIVISION';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN"
SET SOW = 'WEST'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') 
AND DIVISION = 'WEST DIVISION';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" SET UPDATED_DATE=CURRENT_DATE();

/*Updated on : 2025-01-31 - We've added IFNULL(RESULT_SOURCE,'') <>'DP-PIPE' in QS_DASHBOARD_ROLLUPS To Remove System Generated ATT-AIR and VERIZON5G Results in The Dashboard*/

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" AS
SELECT  IFF(BUDGET_YEAR IS NULL,QUEUE_YEAR,BUDGET_YEAR) AS BUDGET_YEAR, IFF(BUDGET_MONTH IS NULL,QUEUE_MONTH,BUDGET_MONTH) AS BUDGET_MONTH
,BUDGET_MONTH AS BUDGET_MONTH_ACTUAL,BUDGET_YEAR AS BUDGET_YEAR_ACTUAL,QUEUE_YEAR AS QUEUE_YEAR,QUEUE_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,DWELL_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(SERVICENAME) AS PUBLISHNAME,UPPER(STD_NAME) AS STD_NAME,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5,DMA,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300 AND STATUS = 'AV',1,0)) AS FIBER_COUNT,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300 AND STATUS = 'AV' AND DELIVERED_YEAR IS NOT NULL,1,0)) AS FIBER_DELIVERED_COUNT,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NF',1,0)) CHECKED_STATUS_NF, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940 AND STATUS = 'AV',1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NF',1,0)) DELIVERED_STATUS_NF, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940 AND STATUS = 'AV',1,0)) AS DELIVERED_GIG_RESULT
FROM "V4_CTELL"."PROC"."WIP_CURRENT" WHERE MSO='COMCAST' AND IFNULL(RESULT_SOURCE,'') <>'DP-PIPE'
GROUP BY BUDGET_YEAR,BUDGET_MONTH,BUDGET_MONTH_ACTUAL,BUDGET_YEAR_ACTUAL,QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,DWELL_TYPE,PROJECT_NAME,SERVICENAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5,DMA
ORDER BY UNDELIVERABLE DESC ;

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
SELECT  IFF(BUDGET_YEAR IS NULL,QUEUE_YEAR,BUDGET_YEAR) AS BUDGET_YEAR, IFF(BUDGET_MONTH IS NULL,QUEUE_MONTH,BUDGET_MONTH) AS BUDGET_MONTH
,BUDGET_MONTH AS BUDGET_MONTH_ACTUAL,BUDGET_YEAR AS BUDGET_YEAR_ACTUAL,QUEUE_YEAR AS QUEUE_YEAR,QUEUE_MONTH AS QUEUE_MONTH,YEAR(CHECK_DATE) AS CHECKED_YEAR, MONTH(CHECK_DATE) AS CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH,UPPER(MSO) AS MSO,UPPER(ENGAGEMENT_TYPE) AS ENGAGEMENT_TYPE,UPPER(BUDGET_TYPE) AS BUDGET_TYPE,UPPER(PROJECT_TYPE) AS PROJECT_TYPE,DWELL_TYPE,
UPPER(PROJECTNAME) AS PROJECT_NAME,UPPER(SERVICENAME) AS PUBLISHNAME,UPPER(STD_NAME) AS STD_NAME,
CASE WHEN SERVICENAME IN  ('ATT','BRIGHTSPEED','CENTURYLINK','FRONTIER111COMMUNICATIONS','WINDSTREAM','VERIZON') 
THEN 'ILEC' ELSE 'OTHERS' END PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,'' AS H1,ZIP5,DMA,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300 AND STATUS = 'AV',1,0)) AS FIBER_COUNT,
SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=300 AND STATUS = 'AV' AND DELIVERED_YEAR IS NOT NULL,1,0)) AS FIBER_DELIVERED_COUNT,
COUNT(*) QUEUED, SUM(IFF(CHECK_DATE IS NOT NULL,1,0)) CHECKED, SUM(IFF(DELIVERED_YEAR IS NOT NULL,1,0)) DELIVERED,
 SUM(IFF(QUARANTINE_FLAG ='Y',1,0)) UNDELIVERABLE,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'AV',1,0)) CHECKED_STATUS_AV,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NA',1,0)) CHECKED_STATUS_NA,SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'ER',1,0)) CHECKED_STATUS_ER,
SUM(IFF(CHECK_DATE IS NOT NULL AND STATUS = 'NF',1,0)) CHECKED_STATUS_NF, SUM(IFF(CHECK_DATE IS NOT NULL AND MAX_SPEED>=940 AND STATUS = 'AV',1,0)) AS CHECKED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'AV',1,0)) DELIVERED_STATUS_AV,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NA',1,0)) DELIVERED_STATUS_NA,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'ER',1,0)) DELIVERED_STATUS_ER,SUM(IFF(DELIVERED_YEAR IS NOT NULL AND STATUS = 'NF',1,0)) DELIVERED_STATUS_NF, SUM(IFF(DELIVERED_YEAR IS NOT NULL AND MAX_SPEED>=940 AND STATUS = 'AV',1,0)) AS DELIVERED_GIG_RESULT
FROM "V4_CTELL"."PROC"."WIP_CURRENT" WHERE MSO<>'COMCAST' AND IFNULL(RESULT_SOURCE,'') <>'DP-PIPE'
GROUP BY BUDGET_YEAR,BUDGET_MONTH,BUDGET_MONTH_ACTUAL,BUDGET_YEAR_ACTUAL,QUEUE_YEAR,QUEUE_MONTH,CHECKED_YEAR, CHECKED_MONTH, DELIVERED_YEAR,DELIVERED_MONTH
,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,DWELL_TYPE,PROJECT_NAME,SERVICENAME,STD_NAME,PROVIDER_TYPE,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME,H1,ZIP5,DMA
ORDER BY UNDELIVERABLE DESC ;


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET PROJECT_TYPE = 'OTHERS'
WHERE PROJECT_TYPE IS NULL;
 
UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET PROJECT_TYPE = 'OTHERS'
WHERE PROJECT_NAME = 'D_COX_RESI_2024-03-01_WATCHLIST_20240302';
 
ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
ADD COLUMN SERVICENAME VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"  
SET SERVICENAME = REPLACE(REPLACE(REPLACE(RTRIM(PUBLISHNAME), '111', ' '),'222',','),'333','.')  
WHERE SERVICENAME IS NULL ;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
ADD COLUMN DELIVERY_NAME  VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET DELIVERY_NAME = CASE WHEN A.MSO = 'COX' THEN UPPER(B.COX_DELIVERY_NAME) 
                         WHEN A.MSO = 'COMCAST' THEN UPPER(B.COMCAST_DELIVERY_NAME) 
                         WHEN A.MSO IN ('CHARTER','CHARTER_BUSINESS') THEN UPPER(B.CHARTER_DELIVERY_NAME)
                         ELSE NULL END
FROM  "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B
WHERE A.PUBLISHNAME = B.PROVIDER_NAME;  

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET DELIVERY_NAME =  STD_NAME                         
WHERE DELIVERY_NAME IS NULL;


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" A
SET DELIVERY_NAME =  SERVICENAME                         
WHERE DELIVERY_NAME IS NULL;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
ADD COLUMN READY_FOR_DELIVERY VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"A
SET READY_FOR_DELIVERY = CHECKED - DELIVERED - UNDELIVERABLE;
  
ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
ADD SOW VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'CORPORATE'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISHNAME IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND H1 IN ('NORTHEAST DIVISION','CENTRAL DIVISION');

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'NED'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISHNAME NOT IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND H1 = 'NORTHEAST DIVISION';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'CENTRAL'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') AND PUBLISHNAME NOT IN ('ATT','BRIGHTSPEED','CENTURYLINK')
AND H1 = 'CENTRAL DIVISION';

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
SET SOW = 'WEST'
WHERE (MSO= 'COMCAST_BUSINESS' OR MSO= 'COMCAST') 
AND H1 = 'WEST DIVISION';

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();

  
CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ZIP_ROLLUPS" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,ZIP5,DELIVERY_NAME,
SUM(FIBER_COUNT) FIBER_COUNT,SUM(QUEUED) QUEUED,SUM(CHECKED) CHECKED,SUM(DELIVERED) DELIVERED,SUM(UNDELIVERABLE) UNDELIVERABLE,SUM(READY_FOR_DELIVERY) READY_FOR_DELIVERY,
SUM(CHECKED_STATUS_AV) CHECKED_STATUS_AV,SUM(CHECKED_STATUS_NA) CHECKED_STATUS_NA,SUM(CHECKED_STATUS_ER) CHECKED_STATUS_ER,SUM(CHECKED_STATUS_NF) CHECKED_STATUS_NF,
SUM(CHECKED_GIG_RESULT) CHECKED_GIG_RESULT,SUM(DELIVERED_STATUS_AV) DELIVERED_STATUS_AV,SUM(DELIVERED_STATUS_NA) DELIVERED_STATUS_NA,
SUM(DELIVERED_STATUS_ER) DELIVERED_STATUS_ER,
SUM(DELIVERED_STATUS_NF) DELIVERED_STATUS_NF,SUM(DELIVERED_GIG_RESULT) DELIVERED_GIG_RESULT FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,ZIP5,DELIVERY_NAME;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ZIP_ROLLUPS"
ADD COLUMN RECEIVED_COUNT VARCHAR(16777216) DEFAULT NULL;


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ZIP_ROLLUPS"A
SET A.RECEIVED_COUNT = B.RECEIVED_COUNT FROM
(SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,PROJECT_NAME,PUBLISH_NAME,ZIP,SUM(RECEIVED_COUNT) RECEIVED_COUNT
 FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,PROJECT_NAME,PUBLISH_NAME,ZIP ) B WHERE 
UPPER(A.PROJECT_NAME)= UPPER(B.PROJECT_NAME)
AND UPPER(A.PUBLISHNAME )= UPPER( B.PUBLISH_NAME) AND A.BUDGET_YEAR = B.BUDGET_YEAR
AND A.BUDGET_MONTH = B.BUDGET_MONTH AND A.MSO = B.MSO AND A.ZIP5 = B.ZIP; 

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ZIP_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ZIP_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_DMA_ZIP_ROLLUPS" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,ZIP5,DMA,DELIVERY_NAME,
SUM(FIBER_COUNT) FIBER_COUNT,SUM(QUEUED) QUEUED,SUM(CHECKED) CHECKED,SUM(DELIVERED) DELIVERED,SUM(UNDELIVERABLE) UNDELIVERABLE,SUM(READY_FOR_DELIVERY) READY_FOR_DELIVERY,
SUM(CHECKED_STATUS_AV) CHECKED_STATUS_AV,SUM(CHECKED_STATUS_NA) CHECKED_STATUS_NA,SUM(CHECKED_STATUS_ER) CHECKED_STATUS_ER,SUM(CHECKED_STATUS_NF) CHECKED_STATUS_NF,
SUM(CHECKED_GIG_RESULT) CHECKED_GIG_RESULT,SUM(DELIVERED_STATUS_AV) DELIVERED_STATUS_AV,SUM(DELIVERED_STATUS_NA) DELIVERED_STATUS_NA,
SUM(DELIVERED_STATUS_ER) DELIVERED_STATUS_ER,
SUM(DELIVERED_STATUS_NF) DELIVERED_STATUS_NF,SUM(DELIVERED_GIG_RESULT) DELIVERED_GIG_RESULT
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,ZIP5,DMA,DELIVERY_NAME;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_DMA_ZIP_ROLLUPS" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,ZIP5,DMA,
DELIVERY_NAME,FIBER_COUNT,QUEUED,CHECKED,DELIVERED,UNDELIVERABLE,READY_FOR_DELIVERY,CHECKED_STATUS_AV,
CHECKED_STATUS_NA,CHECKED_STATUS_ER,CHECKED_STATUS_NF,CHECKED_GIG_RESULT,DELIVERED_STATUS_AV,DELIVERED_STATUS_NA,
DELIVERED_STATUS_ER,DELIVERED_STATUS_NF,DELIVERED_GIG_RESULT,SUM(FIBER_COUNT) OVER(PARTITION BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,PUBLISHNAME,ZIP5  ) AS 
MTD_ZIP5,SUM(FIBER_COUNT) OVER(PARTITION BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PUBLISHNAME ) AS 
MTD_FIBER_PROVIDER,SUM(DELIVERED) OVER(PARTITION BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PUBLISHNAME ) AS 
MTD_DELIVERED_PROVIDER  FROM  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_DMA_ZIP_ROLLUPS"  ;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_DMA_ZIP_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_DMA_ZIP_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();


CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,H1,SOW,DELIVERY_NAME,
SUM(FIBER_COUNT) FIBER_COUNT,SUM(FIBER_DELIVERED_COUNT) FIBER_DELIVERED_COUNT,SUM(QUEUED) QUEUED,SUM(CHECKED) CHECKED,SUM(DELIVERED) DELIVERED,SUM(UNDELIVERABLE) UNDELIVERABLE,SUM(READY_FOR_DELIVERY) READY_FOR_DELIVERY,
SUM(CHECKED_STATUS_AV) CHECKED_STATUS_AV,SUM(CHECKED_STATUS_NA) CHECKED_STATUS_NA,SUM(CHECKED_STATUS_ER) CHECKED_STATUS_ER,SUM(CHECKED_STATUS_NF) CHECKED_STATUS_NF,
SUM(CHECKED_GIG_RESULT) CHECKED_GIG_RESULT,SUM(DELIVERED_STATUS_AV) DELIVERED_STATUS_AV,SUM(DELIVERED_STATUS_NA) DELIVERED_STATUS_NA,
SUM(DELIVERED_STATUS_ER) DELIVERED_STATUS_ER,
SUM(DELIVERED_STATUS_NF) DELIVERED_STATUS_NF,SUM(DELIVERED_GIG_RESULT) DELIVERED_GIG_RESULT,
SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=1 AND DELIVERED_YEAR,DELIVERED,0)) AS JAN_2024,SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=2,DELIVERED,0)) AS FEB_2024,
SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=3,DELIVERED,0)) AS MARCH_2024,SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=4,DELIVERED,0)) AS APRIL_2024,
SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=5,DELIVERED,0)) AS MAY_2024,SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=6,DELIVERED,0)) AS JUNE_2024,
SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=7,DELIVERED,0)) AS JULY_2024,SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=8,DELIVERED,0)) AS AUG_2024,
SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=9,DELIVERED,0)) AS SEP_2024,SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=10,DELIVERED,0)) AS OCT_2024,
SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=11,DELIVERED,0)) AS NOV_2024,SUM(IFF(DELIVERED_YEAR = 2024 AND DELIVERED_MONTH=12,DELIVERED,0)) AS DEC_2024
 FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,PROJECT_TYPE,PROJECT_NAME,PUBLISHNAME,SERVICENAME,H1,SOW,DELIVERY_NAME;



ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS"
ADD COLUMN CLIENT_SENT_DATE VARCHAR(16777216) DEFAULT NULL,
    COLUMN CLIENT_FILE_NAME VARCHAR(16777216) DEFAULT NULL,
    COLUMN CLIENT_PROVIDER_NAME VARCHAR(16777216) DEFAULT NULL,
    COLUMN RECEIVED_COUNT VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS" A
SET A.RECEIVED_COUNT = B.RECEIVED_COUNT,
    A.CLIENT_FILE_NAME = B.INPUT_FILE_NAME,
    A.CLIENT_PROVIDER_NAME = B.INPUT_CLIENT_NAME,
    A.CLIENT_SENT_DATE = B.RECEIVED_DATE
    FROM
(SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,PROJECT_NAME,PUBLISH_NAME,SUM(RECEIVED_COUNT) RECEIVED_COUNT,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE
 FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN" GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,PROJECT_NAME,PUBLISH_NAME,INPUT_FILE_NAME,INPUT_CLIENT_NAME,RECEIVED_DATE ) B WHERE 
UPPER(A.PROJECT_NAME)= UPPER(B.PROJECT_NAME)
AND UPPER(A.PUBLISHNAME )= UPPER( B.PUBLISH_NAME) AND A.BUDGET_YEAR = B.BUDGET_YEAR
AND A.BUDGET_MONTH = B.BUDGET_MONTH AND A.MSO = B.MSO; 

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS"
SET FIBER_COUNT = CASE WHEN FIBER_COUNT  IS NULL THEN 0 ELSE FIBER_COUNT END,
FIBER_DELIVERED_COUNT = CASE WHEN FIBER_COUNT  IS NULL THEN 0 ELSE FIBER_DELIVERED_COUNT END,
QUEUED = CASE WHEN QUEUED  IS NULL THEN 0 ELSE QUEUED END,
CHECKED = CASE WHEN CHECKED  IS NULL THEN 0 ELSE CHECKED END,
DELIVERED = CASE WHEN DELIVERED  IS NULL THEN 0 ELSE DELIVERED END,
UNDELIVERABLE = CASE WHEN UNDELIVERABLE  IS NULL THEN 0 ELSE UNDELIVERABLE END,
READY_FOR_DELIVERY = CASE WHEN READY_FOR_DELIVERY  IS NULL THEN 0 ELSE READY_FOR_DELIVERY END,
CHECKED_STATUS_AV = CASE WHEN CHECKED_STATUS_AV  IS NULL THEN 0 ELSE CHECKED_STATUS_AV END,
CHECKED_STATUS_NA = CASE WHEN CHECKED_STATUS_NA  IS NULL THEN 0 ELSE CHECKED_STATUS_NA END,
CHECKED_STATUS_ER = CASE WHEN CHECKED_STATUS_ER  IS NULL THEN 0 ELSE CHECKED_STATUS_ER END,
CHECKED_STATUS_NF = CASE WHEN CHECKED_STATUS_NF  IS NULL THEN 0 ELSE CHECKED_STATUS_NF END,
CHECKED_GIG_RESULT = CASE WHEN CHECKED_GIG_RESULT  IS NULL THEN 0 ELSE CHECKED_GIG_RESULT END,
DELIVERED_STATUS_AV = CASE WHEN DELIVERED_STATUS_AV  IS NULL THEN 0 ELSE DELIVERED_STATUS_AV END,
DELIVERED_STATUS_NA = CASE WHEN DELIVERED_STATUS_NA  IS NULL THEN 0 ELSE DELIVERED_STATUS_NA END,
DELIVERED_STATUS_ER = CASE WHEN DELIVERED_STATUS_ER  IS NULL THEN 0 ELSE DELIVERED_STATUS_ER END,
DELIVERED_STATUS_NF = CASE WHEN DELIVERED_STATUS_NF  IS NULL THEN 0 ELSE DELIVERED_STATUS_NF END,
DELIVERED_GIG_RESULT = CASE WHEN DELIVERED_GIG_RESULT  IS NULL THEN 0 ELSE DELIVERED_GIG_RESULT END,
JAN_2024 = CASE WHEN JAN_2024  IS NULL THEN 0 ELSE JAN_2024 END,
FEB_2024 = CASE WHEN FEB_2024  IS NULL THEN 0 ELSE FEB_2024 END,
MARCH_2024 = CASE WHEN MARCH_2024  IS NULL THEN 0 ELSE MARCH_2024 END,
APRIL_2024 = CASE WHEN APRIL_2024  IS NULL THEN 0 ELSE APRIL_2024 END,
MAY_2024 = CASE WHEN MAY_2024  IS NULL THEN 0 ELSE MAY_2024 END,
JUNE_2024 = CASE WHEN JUNE_2024  IS NULL THEN 0 ELSE JUNE_2024 END,
JULY_2024 = CASE WHEN JULY_2024  IS NULL THEN 0 ELSE JULY_2024 END,
AUG_2024 = CASE WHEN AUG_2024  IS NULL THEN 0 ELSE AUG_2024 END,
SEP_2024 = CASE WHEN SEP_2024  IS NULL THEN 0 ELSE SEP_2024 END,
OCT_2024 = CASE WHEN OCT_2024  IS NULL THEN 0 ELSE OCT_2024 END,
NOV_2024 = CASE WHEN NOV_2024  IS NULL THEN 0 ELSE NOV_2024 END,
DEC_2024 = CASE WHEN DEC_2024  IS NULL THEN 0 ELSE DEC_2024 END,
RECEIVED_COUNT = CASE WHEN RECEIVED_COUNT  IS NULL THEN 0 ELSE RECEIVED_COUNT END;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();

CREATE OR REPLACE TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" AS
SELECT BUDGET_YEAR, BUDGET_MONTH,IFF(ENGAGEMENT_TYPE = 'RESI',MSO,MSO||'_BUSINESS') AS MSO,ENGAGEMENT_TYPE,DIVISION AS H1,SOW,PUBLISH_NAME AS PUBLISHNAME,
CAST(MONTHLY_TARGET AS INT) TARGET FROM "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."MSO_TRACKING_2024" ;

INSERT INTO "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" (BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,H1,SOW,PUBLISHNAME,TARGET)
SELECT A.BUDGET_YEAR,A.BUDGET_MONTH,A.MSO,A.ENGAGEMENT_TYPE,A.H1,A.SOW,A.PUBLISHNAME,0 AS TARGET
 FROM (SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,H1,SOW
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,H1,SOW) A LEFT JOIN 
"SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" B ON  A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') =  IFNULL(B.SOW,'') AND A.PUBLISHNAME =B.PUBLISHNAME
WHERE B.PUBLISHNAME IS  NULL;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" 
ADD COLUMN BUDGET_TYPE  VARCHAR(16777216) DEFAULT NULL,
SERVICENAME  VARCHAR(16777216) DEFAULT NULL,
FIBER_COUNT_NQ  NUMBER(38,0) DEFAULT NULL,
FIBER_COUNT_WL  NUMBER(38,0) DEFAULT NULL,
FIBER_COUNT_BL  NUMBER(38,0) DEFAULT NULL,
FIBER_COUNT  NUMBER(38,0) DEFAULT NULL,
QUEUED_NQ  NUMBER(38,0) DEFAULT NULL,
QUEUED_WL  NUMBER(38,0) DEFAULT NULL,
QUEUED_BL  NUMBER(38,0) DEFAULT NULL,
QUEUED  NUMBER(38,0) DEFAULT NULL,
CHECKED_NQ  NUMBER(38,0) DEFAULT NULL,
CHECKED_WL  NUMBER(38,0) DEFAULT NULL,
CHECKED_BL  NUMBER(38,0) DEFAULT NULL,
CHECKED  NUMBER(38,0) DEFAULT NULL,
DELIVERED_NQ  NUMBER(38,0) DEFAULT NULL,
DELIVERED_WL  NUMBER(38,0) DEFAULT NULL,
DELIVERED_BL  NUMBER(38,0) DEFAULT NULL,
DELIVERED  NUMBER(38,0) DEFAULT NULL,
RECEIVED_COUNT_NQ  NUMBER(38,0) DEFAULT NULL,
RECEIVED_COUNT_WL  NUMBER(38,0) DEFAULT NULL,
RECEIVED_COUNT_BL   NUMBER(38,0) DEFAULT NULL,
RECEIVED_COUNT  NUMBER(38,0) DEFAULT NULL;


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET BUDGET_TYPE = CASE WHEN UPPER(PUBLISHNAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISHNAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END,
     SERVICENAME = REPLACE(REPLACE(REPLACE(RTRIM(PUBLISHNAME), '111', ' '),'222',','),'333','.') ; 


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET A.FIBER_COUNT_NQ = B.FIBER_COUNT_NQ,
A.FIBER_COUNT_WL  = B.FIBER_COUNT_WL,
A.FIBER_COUNT_BL  = B.FIBER_COUNT_BL,
A.FIBER_COUNT  = B.FIBER_COUNT,
A.QUEUED_NQ  = B.QUEUED_NQ,
A.QUEUED_WL  = B.QUEUED_WL,
A.QUEUED_BL  = B.QUEUED_BL,
A.QUEUED  = B.QUEUED,
A.CHECKED_NQ  = B.CHECKED_NQ,
A.CHECKED_WL  = B.CHECKED_WL,
A.CHECKED_BL  = B.CHECKED_BL,
A.CHECKED  = B.CHECKED,
A.DELIVERED_NQ  = B.DELIVERED_NQ,
A.DELIVERED_WL  = B.DELIVERED_WL,
A.DELIVERED_BL  = B.DELIVERED_BL,
A.DELIVERED  = B.DELIVERED
FROM
(SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,SOW,
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',FIBER_COUNT,0)) AS INT) FIBER_COUNT_NQ, 
CAST(SUM(IFF(PROJECT_TYPE= 'WL',FIBER_COUNT,0)) AS INT) FIBER_COUNT_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',FIBER_COUNT,0)) AS INT) FIBER_COUNT_BL, 
CAST(SUM(FIBER_COUNT) AS INT) FIBER_COUNT, 
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',QUEUED,0)) AS INT) QUEUED_NQ, 
CAST(SUM(IFF(PROJECT_TYPE= 'WL',QUEUED,0)) AS INT) QUEUED_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',QUEUED,0)) AS INT) QUEUED_BL, 
CAST(SUM(QUEUED) AS INT) QUEUED, 
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',CHECKED,0)) AS INT) CHECKED_NQ, 
CAST(SUM(IFF(PROJECT_TYPE= 'WL',CHECKED,0)) AS INT) CHECKED_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',CHECKED,0)) AS INT) CHECKED_BL, 
CAST(SUM(CHECKED) AS INT) CHECKED, 
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',DELIVERED,0)) AS INT) DELIVERED_NQ, 
CAST(SUM(IFF(PROJECT_TYPE= 'WL',DELIVERED,0)) AS INT) DELIVERED_WL,
CAST(SUM(IFF(PROJECT_TYPE= 'BL',DELIVERED,0)) AS INT) DELIVERED_BL, 
CAST(SUM(DELIVERED) AS INT) DELIVERED, 
CAST(SUM(IFF(PROJECT_TYPE= 'NQ',RECEIVED_COUNT,0)) AS INT) RECEIVED_COUNT_NQ, 
CAST(SUM(IFF(PROJECT_TYPE= 'WL',RECEIVED_COUNT,0)) AS INT) RECEIVED_COUNT_WL, 
CAST(SUM(IFF(PROJECT_TYPE= 'BL',RECEIVED_COUNT,0)) AS INT) RECEIVED_COUNT_BL, 
CAST(SUM(RECEIVED_COUNT) AS INT) RECEIVED_COUNT
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,SOW
) B
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'') AND A.PUBLISHNAME =B.PUBLISHNAME ;


UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET A.RECEIVED_COUNT_NQ  = B.RECEIVED_COUNT_NQ,
A.RECEIVED_COUNT_WL  = B.RECEIVED_COUNT_WL,
A.RECEIVED_COUNT   = B.RECEIVED_COUNT 
FROM (SELECT BUDGET_YEAR,BUDGET_MONTH, MSO,ENGAGEMENT_TYPE,PUBLISH_NAME,SOW,SUM(RECEIVED_COUNT) RECEIVED_COUNT
,SUM(CASE WHEN PROJECT_TYPE='NQ' THEN RECEIVED_COUNT ELSE 0 END) AS RECEIVED_COUNT_NQ
 ,SUM(CASE WHEN PROJECT_TYPE='WL' THEN RECEIVED_COUNT ELSE 0 END) AS RECEIVED_COUNT_WL FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_PLAN"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PUBLISH_NAME,SOW)B
WHERE A.BUDGET_YEAR =B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH 
AND A.MSO = B.MSO  AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'')
AND UPPER(A.PUBLISHNAME) = UPPER(B.PUBLISH_NAME) ;


UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET RECEIVED_COUNT_BL = TARGET - (IFF(RECEIVED_COUNT_NQ IS NULL ,0,RECEIVED_COUNT_NQ) + IFF(RECEIVED_COUNT_WL IS NULL ,0,RECEIVED_COUNT_WL));

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" 
SET RECEIVED_COUNT_BL = CASE WHEN CAST(RECEIVED_COUNT_BL AS INT)<0 THEN 0 ELSE RECEIVED_COUNT_BL END ;

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS"
SET FIBER_COUNT_NQ = CASE WHEN  FIBER_COUNT_NQ  IS NULL THEN 0 ELSE FIBER_COUNT_NQ END,
FIBER_COUNT_WL = CASE WHEN  FIBER_COUNT_WL  IS NULL THEN 0 ELSE FIBER_COUNT_WL END,
FIBER_COUNT_BL = CASE WHEN  FIBER_COUNT_BL  IS NULL THEN 0 ELSE FIBER_COUNT_BL END,
FIBER_COUNT = CASE WHEN  FIBER_COUNT  IS NULL THEN 0 ELSE FIBER_COUNT END,
QUEUED_NQ = CASE WHEN  QUEUED_NQ  IS NULL THEN 0 ELSE QUEUED_NQ END,
QUEUED_WL = CASE WHEN  QUEUED_WL  IS NULL THEN 0 ELSE QUEUED_WL END,
QUEUED_BL = CASE WHEN  QUEUED_BL  IS NULL THEN 0 ELSE QUEUED_BL END,
QUEUED = CASE WHEN  QUEUED  IS NULL THEN 0 ELSE QUEUED END,
CHECKED_NQ = CASE WHEN  CHECKED_NQ  IS NULL THEN 0 ELSE CHECKED_NQ END,
CHECKED_WL = CASE WHEN  CHECKED_WL  IS NULL THEN 0 ELSE CHECKED_WL END,
CHECKED_BL = CASE WHEN  CHECKED_BL  IS NULL THEN 0 ELSE CHECKED_BL END,
CHECKED = CASE WHEN  CHECKED  IS NULL THEN 0 ELSE CHECKED END,
DELIVERED_NQ = CASE WHEN  DELIVERED_NQ  IS NULL THEN 0 ELSE DELIVERED_NQ END,
DELIVERED_WL = CASE WHEN  DELIVERED_WL  IS NULL THEN 0 ELSE DELIVERED_WL END,
DELIVERED_BL = CASE WHEN  DELIVERED_BL  IS NULL THEN 0 ELSE DELIVERED_BL END,
DELIVERED = CASE WHEN  DELIVERED  IS NULL THEN 0 ELSE DELIVERED END,
RECEIVED_COUNT_NQ = CASE WHEN  RECEIVED_COUNT_NQ  IS NULL THEN 0 ELSE RECEIVED_COUNT_NQ END,
RECEIVED_COUNT_WL = CASE WHEN  RECEIVED_COUNT_WL  IS NULL THEN 0 ELSE RECEIVED_COUNT_WL END,
RECEIVED_COUNT_BL = CASE WHEN  RECEIVED_COUNT_BL  IS NULL THEN 0 ELSE RECEIVED_COUNT_BL END,
RECEIVED_COUNT = CASE WHEN  RECEIVED_COUNT  IS NULL THEN 0 ELSE RECEIVED_COUNT END,
TARGET = CASE WHEN  TARGET  IS NULL THEN 0 ELSE TARGET END;


ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS"
ADD COLUMN DELIVERY_NAME  VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET DELIVERY_NAME = CASE WHEN A.MSO = 'COX' THEN UPPER(B.COX_DELIVERY_NAME) 
                         WHEN A.MSO = 'COMCAST' THEN UPPER(B.COMCAST_DELIVERY_NAME) 
                         WHEN A.MSO IN ('CHARTER','CHARTER_BUSINESS') THEN UPPER(B.CHARTER_DELIVERY_NAME)
                         ELSE NULL END
FROM  "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B
WHERE A.PUBLISHNAME = B.PROVIDER_NAME;  

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET DELIVERY_NAME =  B.STD_NAME 
FROM  "V4_CTELL"."TEST"."CTEL_MASTER_PROVIDER_NAME" B
WHERE DELIVERY_NAME IS NULL AND A.PUBLISHNAME = B.PROVIDER_NAME;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" A
SET DELIVERY_NAME =  SERVICENAME                         
WHERE DELIVERY_NAME IS NULL;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();


CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,H1,SOW,
CAST(SUM(FIBER_COUNT_NQ) AS INT) FIBER_COUNT_NQ, 
CAST(SUM(FIBER_COUNT_WL) AS INT) FIBER_COUNT_WL,
CAST(SUM(FIBER_COUNT_BL) AS INT) FIBER_COUNT_BL, 
CAST(SUM(FIBER_COUNT) AS INT) FIBER_COUNT, 
CAST(SUM(QUEUED_NQ) AS INT) QUEUED_NQ, 
CAST(SUM(QUEUED_WL) AS INT) QUEUED_WL,
CAST(SUM(QUEUED_BL) AS INT) QUEUED_BL, 
CAST(SUM(QUEUED) AS INT) QUEUED, 
CAST(SUM(CHECKED_NQ) AS INT) CHECKED_NQ, 
CAST(SUM(CHECKED_WL) AS INT) CHECKED_WL,
CAST(SUM(CHECKED_BL) AS INT) CHECKED_BL, 
CAST(SUM(CHECKED) AS INT) CHECKED, 
CAST(SUM(DELIVERED_NQ) AS INT) DELIVERED_NQ, 
CAST(SUM(DELIVERED_WL) AS INT) DELIVERED_WL,
CAST(SUM(DELIVERED_BL) AS INT) DELIVERED_BL, 
CAST(SUM(DELIVERED) AS INT) DELIVERED, 
CAST(SUM(RECEIVED_COUNT_NQ) AS INT) RECEIVED_COUNT_NQ, 
CAST(SUM(RECEIVED_COUNT_WL) AS INT) RECEIVED_COUNT_WL, 
CAST(SUM(RECEIVED_COUNT_BL) AS INT) RECEIVED_COUNT_BL ,
CAST(SUM(RECEIVED_COUNT) AS INT) RECEIVED_COUNT, 
CAST(SUM(TARGET) AS INT) TARGET_QUEUED
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,BUDGET_TYPE,H1,SOW;


ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS"
ADD COLUMN TARGET VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS"   A
SET TARGET = B.MONTHLY_TARGET
FROM (SELECT MSO,ENGAGEMENT_TYPE,DIVISION,BUDGET_YEAR,CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,CAST(SUM(MONTHLY_TARGET)/12 AS INT) AS MONTHLY_TARGET FROM
                       "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."MSO_TRACKING_2024" GROUP BY 1,2,3,4,5) B
WHERE UPPER(A.BUDGET_TYPE) =  UPPER(B.BUDGET_TYPE) AND A.BUDGET_YEAR = B.BUDGET_YEAR  AND REPLACE(A.MSO,'_BUSINESS','') = B.MSO
AND A.MSO <>'COMCAST'AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE ;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS"   A
SET TARGET = B.MONTHLY_TARGET
FROM (SELECT MSO,ENGAGEMENT_TYPE,SOW,BUDGET_YEAR,CASE WHEN UPPER(PUBLISH_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PUBLISH_NAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END BUDGET_TYPE,CAST(SUM(MONTHLY_TARGET)/12 AS INT) AS MONTHLY_TARGET FROM
                       "SCIERA_SUBSYSTEM"."CTELL_TRACKING"."MSO_TRACKING_2024" GROUP BY 1,2,3,4,5) B
WHERE UPPER(A.BUDGET_TYPE) =  UPPER(B.BUDGET_TYPE) AND A.BUDGET_YEAR = B.BUDGET_YEAR  AND REPLACE(A.MSO,'_BUSINESS','') = B.MSO
AND A.MSO ='COMCAST' AND  IFNULL(A.SOW,'') = IFNULL(B.SOW,'') AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE ;

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS"
SET FIBER_COUNT_NQ = CASE WHEN  FIBER_COUNT_NQ  IS NULL THEN 0 ELSE FIBER_COUNT_NQ END,
FIBER_COUNT_WL = CASE WHEN  FIBER_COUNT_WL  IS NULL THEN 0 ELSE FIBER_COUNT_WL END,
FIBER_COUNT_BL = CASE WHEN  FIBER_COUNT_BL  IS NULL THEN 0 ELSE FIBER_COUNT_BL END,
FIBER_COUNT = CASE WHEN  FIBER_COUNT  IS NULL THEN 0 ELSE FIBER_COUNT END,
QUEUED_NQ = CASE WHEN  QUEUED_NQ  IS NULL THEN 0 ELSE QUEUED_NQ END,
QUEUED_WL = CASE WHEN  QUEUED_WL  IS NULL THEN 0 ELSE QUEUED_WL END,
QUEUED_BL = CASE WHEN  QUEUED_BL  IS NULL THEN 0 ELSE QUEUED_BL END,
QUEUED = CASE WHEN  QUEUED  IS NULL THEN 0 ELSE QUEUED END,
CHECKED_NQ = CASE WHEN  CHECKED_NQ  IS NULL THEN 0 ELSE CHECKED_NQ END,
CHECKED_WL = CASE WHEN  CHECKED_WL  IS NULL THEN 0 ELSE CHECKED_WL END,
CHECKED_BL = CASE WHEN  CHECKED_BL  IS NULL THEN 0 ELSE CHECKED_BL END,
CHECKED = CASE WHEN  CHECKED  IS NULL THEN 0 ELSE CHECKED END,
DELIVERED_NQ = CASE WHEN  DELIVERED_NQ  IS NULL THEN 0 ELSE DELIVERED_NQ END,
DELIVERED_WL = CASE WHEN  DELIVERED_WL  IS NULL THEN 0 ELSE DELIVERED_WL END,
DELIVERED_BL = CASE WHEN  DELIVERED_BL  IS NULL THEN 0 ELSE DELIVERED_BL END,
DELIVERED = CASE WHEN  DELIVERED  IS NULL THEN 0 ELSE DELIVERED END,
RECEIVED_COUNT_NQ = CASE WHEN  RECEIVED_COUNT_NQ  IS NULL THEN 0 ELSE RECEIVED_COUNT_NQ END,
RECEIVED_COUNT_WL = CASE WHEN  RECEIVED_COUNT_WL  IS NULL THEN 0 ELSE RECEIVED_COUNT_WL END,
RECEIVED_COUNT_BL = CASE WHEN  RECEIVED_COUNT_BL  IS NULL THEN 0 ELSE RECEIVED_COUNT_BL END,
RECEIVED_COUNT = CASE WHEN  RECEIVED_COUNT  IS NULL THEN 0 ELSE RECEIVED_COUNT END,
TARGET_QUEUED = CASE WHEN  TARGET_QUEUED  IS NULL THEN 0 ELSE TARGET_QUEUED END,
TARGET = CASE WHEN  TARGET  IS NULL THEN 0 ELSE TARGET END;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_BUDGET_TYPE_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROVIDER_ROLLUPS" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,SOW,DELIVERY_NAME,
CAST(SUM(FIBER_COUNT) AS INT) FIBER_COUNT, 
CAST(SUM(QUEUED) AS INT) QUEUED, 
CAST(SUM(CHECKED) AS INT) CHECKED, 
CAST(SUM(DELIVERED) AS INT) DELIVERED, 
CAST(SUM(RECEIVED_COUNT) AS INT) RECEIVED_COUNT,
CAST(SUM(UNDELIVERABLE) AS INT) UNDELIVERABLE,
CAST(SUM(READY_FOR_DELIVERY) AS INT) READY_FOR_DELIVERY,
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_ROLLUPS"
GROUP BY BUDGET_YEAR,BUDGET_MONTH,MSO,ENGAGEMENT_TYPE,PROJECT_TYPE,BUDGET_TYPE,SERVICENAME,PUBLISHNAME,SOW,DELIVERY_NAME;


ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROVIDER_ROLLUPS" 
ADD COLUMN TARGET VARCHAR(16777216) DEFAULT NULL;

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROVIDER_ROLLUPS" A
SET TARGET = CASE WHEN PROJECT_TYPE = 'NQ' THEN RECEIVED_COUNT_NQ 
                  WHEN PROJECT_TYPE = 'BL' THEN RECEIVED_COUNT_BL 
                  WHEN PROJECT_TYPE = 'WL' THEN RECEIVED_COUNT_WL ELSE 0 END
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROJECT_TYPE_ROLLUPS" B
WHERE A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH
AND A.MSO = B.MSO AND A.ENGAGEMENT_TYPE = B.ENGAGEMENT_TYPE AND IFNULL(A.SOW,'') = IFNULL(B.SOW,'') AND A.PUBLISHNAME =B.PUBLISHNAME ; 

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROVIDER_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_PROVIDER_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();


CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_SMB_DELIVERY_ROLLUPS" 
(MSO  VARCHAR(16777216) DEFAULT NULL,
BUDGET_MONTH  VARCHAR(16777216) DEFAULT NULL,
BUDGET_YEAR  VARCHAR(16777216) DEFAULT NULL,
PROVIDER  VARCHAR(16777216) DEFAULT NULL,
 CLENT_DELIVERY_NAME VARCHAR(16777216) DEFAULT NULL,
BUDGET_TYPE  VARCHAR(16777216) DEFAULT NULL,
DELIVERED  VARCHAR(16777216) DEFAULT NULL,
FIBER_COUNT  VARCHAR(16777216) DEFAULT NULL);


INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_SMB_DELIVERY_ROLLUPS"
 SELECT 'COX_BUSINESS' AS MSO,MONTH(TRY_CAST(DELIVERY_DATE AS DATE)) AS BUDGET_MONTH,YEAR(TRY_CAST(DELIVERY_DATE AS DATE)) AS BUDGET_YEAR,PROVIDER,
 REPLACE(REPLACE(REPLACE(RTRIM(PROVIDER), '111', ' '),'222',','),'333','.') AS CLENT_DELIVERY_NAME,
CASE WHEN UPPER(PROVIDER)='ATT' THEN 'ATT'
                       WHEN UPPER(PROVIDER) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END AS BUDGET_TYPE,
COUNT(*) AS DELIVERED,SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>=300,1,0)) AS FIBER_COUNT  FROM "V4_CTELL"."DELIVERIES"."COX_SMB_DELIVERY" 
GROUP BY 1,2,3,4,5;

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_SMB_DELIVERY_ROLLUPS"
SELECT 'COMCAST_BUSINESS' AS MSO,MONTH(TRY_CAST(DELIVERED_DATE AS DATE)) AS BUDGET_MONTH,YEAR(TRY_CAST(DELIVERED_DATE AS DATE)) AS BUDGET_YEAR,PROVIDER_NAME,
REPLACE(REPLACE(REPLACE(RTRIM(PROVIDER_NAME), '111', ' '),'222',','),'333','.') AS CLENT_DELIVERY_NAME,
CASE WHEN UPPER(PROVIDER_NAME)='ATT' THEN 'ATT'
                       WHEN UPPER(PROVIDER_NAME) IN ('T-MOBILE 5G','TMOBILE 5G','VERIZON 5G') THEN 'FWA'
                       ELSE 'NON ATT' END AS BUDGET_TYPE,
COUNT(*) AS DELIVERED,SUM(IFF(CAST(MAX_SPEED AS DOUBLE)>=300,1,0)) AS FIBER_COUNT  FROM "V4_CTELL"."DELIVERIES"."COMCAST_SMB_DELIVERY" 
GROUP BY 1,2,3,4,5;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_SMB_DELIVERY_ROLLUPS" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_SMB_DELIVERY_ROLLUPS" SET UPDATED_DATE=CURRENT_DATE();


INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_PROVIDER" (FL_DATE, SOW_PROJECT, CLIENT_PROVIDER_NAME, CHECKS, UPDATED_DATE)
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_PROVIDER" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_PROVIDER" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_CHECKS"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_CHECKS" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_CHECKS" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_CB"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_COVERAGE_CB" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_CB" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_BIZ"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_COVERAGE_BIZ" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_BIZ" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_CB_TIER_ILEC"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_COVERAGE_CB_TIER_ILEC" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_CB_TIER_ILEC" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_BIZ_TIER_ILEC"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_COVERAGE_BIZ_TIER_ILEC" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_BIZ_TIER_ILEC" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_CB_TIER_TIER2"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_COVERAGE_CB_TIER_TIER2" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_CB_TIER_TIER2" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

INSERT INTO  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_BIZ_TIER_TIER2"
(SELECT A.*, CURRENT_DATE() FROM "MSO"."V3_COMCAST_SMB"."RPT_PROJECT_COVERAGE_BIZ_TIER_TIER2" A
LEFT JOIN  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."RPT_PROJECT_COVERAGE_BIZ_TIER_TIER2" B 
ON A.FL_DATE = B.FL_DATE WHERE B.FL_DATE IS NULL);

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING" AS
SELECT *,IFF(MAX_SPEED>=300,'Y',NULL) AS IS_FIBER_ZIP9,IFF(ZIP9_CHECKED>0,'Y',NULL) AS IS_ZIP9_CHECKED,
IFF(ZIP9_DELIVERED>0,'Y',NULL) AS IS_ZIP9_DELIVERED FROM 
(SELECT IFF(BUDGET_YEAR IS NULL,QUEUE_YEAR,BUDGET_YEAR) BUDGET_YEAR ,IFF(BUDGET_MONTH IS NULL,QUEUE_MONTH,BUDGET_MONTH) BUDGET_MONTH,REPLACE(REPLACE(REPLACE(RTRIM(SERVICENAME), '111', ' '),'222',','),'333','.') as SERVICENAME,DMA,H1,ZIP5,ZIP4,REGION,
sum(IFF(PROJECT_TYPE='BL',1,0)) as BAU,sum(IFF(PROJECT_TYPE='NQ',1,0)) as NQ,
sum(IFF(PROJECT_TYPE='WL',1,0)) as WL,
SUM(IFF(CHECK_DATE is not NULL,1,0)) ZIP9_CHECKED, 
SUM(IFF(DELIVERED_DATE is not NULL,1,0)) ZIP9_DELIVERED, 
 MAX(CAST (MAX_SPEED AS DOUBLE)) AS MAX_SPEED,
FROM "V4_CTELL"."PROC"."WIP_CURRENT" WHERE MSO = 'COMCAST'  GROUP BY 1,2,3,4,5,6,7,8);

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_1" AS
SELECT A.*,B.HOME_PASSED FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING" A
LEFT JOIN (SELECT H1,SCIERA_DMA, SCIERA_ZIP5,SCIERA_ZIP4,H2,COUNT(*) AS HOME_PASSED
FROM "MSO"."V3_COMCAST_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='' GROUP BY 1,2,3,4,5) B 
ON A.DMA = B.SCIERA_DMA AND A.ZIP5 = B.SCIERA_ZIP5 AND A.ZIP4 = B.SCIERA_ZIP4 AND A.REGION = B.H2 AND A.H1 =B.H1;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2" AS
SELECT BUDGET_YEAR,BUDGET_MONTH,SERVICENAME,DMA,H1,ZIP5,REGION,SUM(BAU) BAU,SUM(NQ) NQ,SUM(WL) WL,
COUNT(DISTINCT IFF(IS_FIBER_ZIP9 = 'Y',CONCAT(ZIP5,ZIP4),NULL)) AS FIBER_ZIP9,
COUNT(DISTINCT IFF(IS_ZIP9_CHECKED = 'Y',CONCAT(ZIP5,ZIP4),NULL)) ZIP_CHECKED,
COUNT(DISTINCT IFF(IS_ZIP9_DELIVERED = 'Y',CONCAT(ZIP5,ZIP4),NULL)) ZIP_DELIVERED,
SUM(IFF(IS_FIBER_ZIP9 = 'Y',HOME_PASSED,0)) AS ACTUAL_HP FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_1"
GROUP BY 1,2,3,4,5,6,7;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_3" AS
SELECT A.*,COALESCE(BAU,0) BAU,COALESCE(NQ,0) NQ,COALESCE(WL,0) WL,COALESCE(FIBER_ZIP9,0) FIBER_ZIP9,COALESCE(ZIP_CHECKED,0) ZIP_CHECKED
,COALESCE(ZIP_DELIVERED,0) ZIP_DELIVERED,COALESCE(ACTUAL_HP,0) ACTUAL_HP FROM (SELECT * FROM 
 (SELECT 
        EXTRACT(YEAR FROM DATEADD(MONTH, seq4(), DATE_TRUNC('YEAR', DATEADD(YEAR, -2, CURRENT_DATE)))) AS BUDGET_YEAR,
        EXTRACT(MONTH FROM DATEADD(MONTH, seq4(), DATE_TRUNC('YEAR', DATEADD(YEAR, -2, CURRENT_DATE)))) AS BUDGET_MONTH
    FROM TABLE(GENERATOR(ROWCOUNT => 12 * 4))) YEAR_MONTH_GEN
CROSS JOIN (SELECT DISTINCT SERVICENAME,DMA,H1,ZIP5,REGION FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2" ) DIST_NAME
) A
LEFT JOIN "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2" B
ON A.BUDGET_YEAR = B.BUDGET_YEAR AND A.BUDGET_MONTH = B.BUDGET_MONTH AND A.SERVICENAME = B.SERVICENAME 
AND A.DMA = B.DMA AND A.H1 = B.H1 AND A.ZIP5 = B.ZIP5 AND A.REGION = B.REGION;

CREATE OR REPLACE TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED" AS
SELECT *,COALESCE(LAG(ACTUAL_HP,1) OVER( PARTITION BY SERVICENAME,DMA,H1,ZIP5,REGION ORDER BY BUDGET_YEAR,BUDGET_MONTH ),0) MOM_HP,
COALESCE(LAG(ACTUAL_HP,3) OVER( PARTITION BY SERVICENAME,DMA,H1,ZIP5 ORDER BY BUDGET_YEAR,BUDGET_MONTH ),0) MO3M_HP
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_3" ;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED"
ADD COLUMN INCLUDE VARCHAR(16777216) DEFAULT 'N';

UPDATE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED" A
SET A.INCLUDE = B.INCLUDE
FROM "SCIERA_SUBSYSTEM"."QUICKSIGHT"."COMCAST_DMA_REGION_VALIDATION" B
WHERE A.DMA = B.DMA AND A.H1 = B.DIVISION AND A.REGION = B.REGION;

ALTER TABLE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED" ADD COLUMN UPDATED_DATE VARCHAR(16777216);

UPDATE "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED" SET UPDATED_DATE=CURRENT_DATE();

DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING";
DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_1";
DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_2";
DROP TABLE  "SCIERA_SUBSYSTEM"."QUICKSIGHT"."QS_DASHBOARD_COMCAST_HOME_PASSED_STAGING_3";

GRANT ALL ON ALL TABLES IN SCHEMA SCIERA_SUBSYSTEM.QUICKSIGHT TO ROLE DBA;
	


