UPDATE V4_CTELL.PROC.WIP_CURRENT
SET CHECK_FL_DATE = DATE_TRUNC('MONTH', DATE(CHECK_DATE));

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIRST_CHECK_DATE_ZIP9 = B.FIRST_CHECK_DATE
FROM V4_CTELL.ROLLUPS.ZIP9_FIRST_CHECK_DATE B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.ZIP9 = B.ZIP9;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIRST_CHECK_DATE_CB = B.FIRST_CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_FIRST_CHECK_DATE B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.CB = B.SCIERA_CB;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIBER_FIRST_FOUND_ZIP9 = B.FIBER_FIRST_FOUND,
	A.FIBER_FIRST_FOUND_ZIP9_FL_DATE = DATE_TRUNC('MONTH', DATE(B.FIBER_FIRST_FOUND)),
	A.LAST_CHECK_DATE_ZIP9 = B.CHECK_DATE 
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME ;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIBER_FIRST_FOUND_CB = B.FIBER_FIRST_FOUND,
	A.FIBER_FIRST_FOUND_CB_FL_DATE = DATE_TRUNC('MONTH', DATE(B.FIBER_FIRST_FOUND)),
	A.LAST_CHECK_DATE_CB = B.CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_ROLLUP B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME ;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.DAYS_ALREADY_GIG_CB = (A.FIBER_FIRST_FOUND_CB - A.CHECK_DATE),
	A.DAYS_ALREADY_GIG_ZIP9 = (A.FIBER_FIRST_FOUND_ZIP9 - A.CHECK_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_3M = 'Y'
FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_3M = 'Y'
FROM V4_CTELL.ROLLUPS.CB_ALL_CHECKS B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_6M = 'Y'
FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND A.ZIP9_CHECKED_3M IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_6M = 'Y'
FROM V4_CTELL.ROLLUPS.CB_ALL_CHECKS B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND A.CB_CHECKED_3M IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A SET A.CB_KNOWN_AREA='Y' WHERE A.CHECK_DATE > A.FIRST_CHECK_DATE_CB;

UPDATE V4_CTELL.PROC.WIP_CURRENT A SET A.CB_NEW_AREA='Y' WHERE A.CHECK_DATE <= A.FIRST_CHECK_DATE_CB OR A.FIRST_CHECK_DATE_CB IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A SET A.ZIP9_KNOWN_AREA='Y' WHERE A.CHECK_DATE > A.FIRST_CHECK_DATE_ZIP9;

UPDATE V4_CTELL.PROC.WIP_CURRENT A SET A.ZIP9_NEW_AREA='Y' WHERE A.CHECK_DATE <= A.FIRST_CHECK_DATE_ZIP9 OR A.FIRST_CHECK_DATE_ZIP9 IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_12M = 'Y'
FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE < DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE AND A.ZIP9_CHECKED_3M IS NULL AND A.ZIP9_CHECKED_6M IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_12M = 'Y'
WHERE A.ZIP9_KNOWN_AREA='Y' AND A.DELIVERED_DATE IS NOT NULL AND (A.FIBER_FIRST_FOUND_ZIP9 IS NULL OR A.FIBER_FIRST_FOUND_ZIP9_FL_DATE >= A.CHECK_FL_DATE) 
AND A.ZIP9_CHECKED_12M IS NULL AND A.ZIP9_CHECKED_6M IS NULL AND A.ZIP9_CHECKED_3M IS NULL AND A.ZIP9_NEW_AREA IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_12M = 'Y'
FROM V4_CTELL.ROLLUPS.CB_ALL_CHECKS B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE < DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE AND A.CB_CHECKED_3M IS NULL AND A.CB_CHECKED_6M IS NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_12M = 'Y'
WHERE A.CB_KNOWN_AREA='Y' AND A.DELIVERED_DATE IS NOT NULL AND (A.FIBER_FIRST_FOUND_CB IS NULL OR A.FIBER_FIRST_FOUND_CB_FL_DATE >= A.CHECK_FL_DATE) 
AND A.CB_CHECKED_12M IS NULL AND A.CB_CHECKED_6M IS NULL AND A.CB_CHECKED_3M IS NULL AND A.CB_NEW_AREA IS NULL;
