UPDATE V4_CTELL.PROC.WIP_CURRENT
SET CHECK_FL_DATE = DATE_TRUNC('MONTH', DATE(CHECK_DATE));

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIRST_CHECK_DATE_ZIP9 = B.FIRST_CHECK_DATE
FROM V4_CTELL.ROLLUPS.ZIP9_CHECKED_ROLLUP B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.ZIP9 = B.ZIP9  AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIRST_CHECK_DATE_CB = B.FIRST_CHECK_DATE
FROM V4_CTELL.ROLLUPS.CB_CHECKED_ROLLUP B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.CB = B.SCIERA_CB AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIBER_FIRST_FOUND_ZIP9 = B.FIBER_FIRST_FOUND
FROM V4_CTELL.ROLLUPS.ZIP9_ROLLUP B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE) AND B.FIBER_FIRST_FOUND IS NOT NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.FIBER_FIRST_FOUND_CB = B.FIBER_FIRST_FOUND
FROM V4_CTELL.ROLLUPS.CB_ROLLUP B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE) AND B.FIBER_FIRST_FOUND IS NOT NULL;

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_3M = 'Y'
FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_3M = 'Y'
FROM V4_CTELL.ROLLUPS.CB_ALL_CHECKS B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -3, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_6M = 'Y'
FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_6M = 'Y'
FROM V4_CTELL.ROLLUPS.CB_ALL_CHECKS B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -6, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.ZIP9_CHECKED_12M = 'Y'
FROM V4_CTELL.ROLLUPS.ZIP9_ALL_CHECKS B
WHERE A.ZIP9 = B.ZIP9 AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -12, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE AND A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT A
SET A.CB_CHECKED_12M = 'Y'
FROM V4_CTELL.ROLLUPS.CB_ALL_CHECKS B
WHERE A.CB = B.SCIERA_CB AND A.MSO = B.MSO AND A.SERVICENAME = B.PROVIDER_NAME AND B.CHECK_FL_DATE >= DATEADD(MONTH, -12, A.CHECK_FL_DATE)::DATE AND B.CHECK_FL_DATE < A.CHECK_FL_DATE AND  A.BUDGET_MONTH = MONTH(CURRENT_DATE) AND A.BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT SET FIRST_CHECK_FL_DATE_CB = DATE_TRUNC('MONTH', DATE(FIRST_CHECK_DATE_CB));

UPDATE V4_CTELL.PROC.WIP_CURRENT SET FIRST_CHECK_FL_DATE_ZIP9 = DATE_TRUNC('MONTH', DATE(FIRST_CHECK_DATE_ZIP9));

UPDATE V4_CTELL.PROC.WIP_CURRENT SET CB_NEW_AREA = 'Y' WHERE (CHECK_FL_DATE <= FIRST_CHECK_FL_DATE_CB OR FIRST_CHECK_FL_DATE_CB IS NULL) AND BUDGET_MONTH = MONTH(CURRENT_DATE) AND BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT SET ZIP9_NEW_AREA = 'Y' WHERE (CHECK_FL_DATE <= FIRST_CHECK_FL_DATE_ZIP9 OR FIRST_CHECK_FL_DATE_ZIP9 IS NULL) AND BUDGET_MONTH = MONTH(CURRENT_DATE) AND BUDGET_YEAR = YEAR(CURRENT_DATE);

UPDATE V4_CTELL.PROC.WIP_CURRENT
SET FIBER_FIRST_FOUND_CB_FL_DATE = DATE_TRUNC('MONTH', DATE(FIBER_FIRST_FOUND_CB));

UPDATE V4_CTELL.PROC.WIP_CURRENT
SET FIBER_FIRST_FOUND_ZIP9_FL_DATE = DATE_TRUNC('MONTH', DATE(FIBER_FIRST_FOUND_ZIP9));
