INSERT INTO AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL 
SELECT 
TO_DATE(A.INJECTDATE) AS INJECTDAY,
B.IPADDRESS AS IPADDRESS,
SITEPLATFORMVALUE,
ENDUSERLATITUDEVALUE,
ENDUSERLONGITUDEVALUE,
UNIQUEUSERID,
A.FILENAME,
A.INJECTDATE,
A.VERSION,
A.REQUESTID,
A.EVENT,
A.STATUS,
A.SRCREQUESTID,
A.IMPRESSIONID,
A.ADID,
A.CAMPAIGNID,
A.SRCURLHASH,
A.SITEID,
A.COUNTRYID,
A.DEVICEID,
A.DEVICEMANUFACTURERID,
A.DEVICEMODELID,
A.DEVICEOSID,
A.USERAGENT,
A.IPADDRESS AS POSTIMPRESSION_IP,
A.XFORWARDEDFOR,
A.TIMEVALUE,
A.EVENTTIME,
A.AUCTION_PRICE,
A.AUCTION_CURRENCY,
A.AUCTION_BID_ID,
A.AUCTION_ID,
A.AUCTION_IMP_ID,
A.EXCHANGEID,
A.COUNTRYCARRIERID,
A.SELECTEDSITECATEGORYID,
A.URLVERSION,
A.INVENTORYSOURCE,
A.BIDPRICE_TO_EXCHANGE,
A.INTERNAL_MAX_BID,
A.ADVERTISER_BID,
A.BIDDERMODELID,
A.MARKETPLACE_ID,
A.SLOTID,
A.DEVICEBROWSERID,
A.CPA_GOAL,
A.SUPPLY_SOURCE_TYPE,
A.EXT_SUPPLY_ATTR_INTERNAL_ID,
A.CONNECTIONTYPEID,
A.ADV_INC_ID,
A.PUB_INC_ID,
A.DEVICETYPE,
A.BIDFLOOR,
A.EXCHANGEUSERID,
A.EXTERNALSITEAPPID,
A.STATEID,
A.CITYID,
A.ADPOSITIONID,
A.CHANNELID,
A.EXPERIMENTID,
A.REQUESTMODE,
A.TARGETABLEDOMAIN,
A.URLEXTRAPARAMETERS_P,
A.URLEXTRAPARAMETERS_ABID,
A.URLEXTRAPARAMETERS_IID,
A.URLEXTRAPARAMETERS_KDOM,
A.URLEXTRAPARAMETERS_AIMPID,
A.URLEXTRAPARAMETERS_AID,
A.URLEXTRAPARAMETERS_BP,
A.ID,
A.TEVENT,
A.URLEXTRAPARAMETERS,
A.RAW_LOG,
A.LINEITEMID,
A.PARENTIDADV,
A.PARENTIDPUB,
A.SLOTVIEWABILITY,
A.SSPID,
A.IS_CONVERSION_TRACKED,
A.GDPR,
A.CONSENT,
A.PRODID,
A.CB_CHRM,
A.BANNERID,
A.IS_NEW_USER,
A.AAID,
A.EXTMONETARY,
A.REQFORMATID,
A.AUCTION_LOSS_CODE,
A.DETECTEDCOUNTRYID,
A.INTERNALSITESLOTID,
A.EXTERNALSITESLOTID,
A.CREATIVEID,
A.ISPOSTBACKCONVERSION,
A.SEG,
A.ADSERVINGCONVREQIDS,
A.POSTDATA,
A.GETDATA,
A.ADTAXONOMYIDS,
A.PUBREFERER,
A.HTML5LANDINGPAGECLICKURL,
A.SEGS,
A.SURVEYRESPONSES,
A.GENERICEVENTTYPE,
A.CNVEVENTS,
A.KRITTERUSERID,
A.BUYERUID,
A.TERMINATIONREASON_NAME,
A.DETECTED_COUNTRY_ID,
A.DETECTED_STATE_ID,
A.DETECTED_CITY_ID,
A.DETECTED_DEVICETYPE_ID,
A.DETECTED_COUNTRY_CARRIER_ID,
A.DETECTED_CONNECTION_TYPE_ID,
A.DETECTED_OS_ID,
A.DETECTED_BROWSER_ID,
A.DETECTED_MANUFACTURER_ID,
A.PRODUCTID,
A.BRAND,
A.ASKONE_RESPONSE,
A.TEVENTTYPE,
A.ORGNAME,
'' AS AD_TYPE, 
'' , 
PARSE_IP(B.IPADDRESS,'INET',1):ipv4 AS INT_IP,
'',
'',
'',
'',
'',
'',
'',
B.ZIP,
NULL,
CASE WHEN B.ADVERTISERID = '010ab663-b671-1a01-8f58-74ca3b000217' THEN 'COX' 
	 WHEN B.ADVERTISERID = '010affd8-7a4e-2701-94cb-0d480400005f' THEN 'COMCAST' ELSE '' END,''
FROM SCIERA_DATASET.PUBLIC.AROSCOP_POSTIMPRESSION_LOG_CURRENT_DETAILS A LEFT JOIN SCIERA_DATASET.PUBLIC.AROSCOP_ADSERVING_LOG_CURRENT_DETAILS B ON A.SRCREQUESTID=B.REQUESTID 
WHERE B.ADVERTISERID IN ('010ab663-b671-1a01-8f58-74ca3b000217', '010affd8-7a4e-2701-94cb-0d480400005f') AND 
DATE(A.INJECTDATE) = CURRENT_DATE-1;

UPDATE AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL IP
SET
IP.CLIENT_NAME=MI.CLIENT_NAME,
IP.SCIERA_TYPE=MI.SCIERA_TYPE,
IP.STD_NAME=MI.STD_NAME,
IP.MAXMIND=MI.MAXMIND_NAME,
IP.IP2=MI.IP2_NAME,
IP.IP2_DOMAIN=MI.IP2_DOMAIN,
IP.MAXMIND_CT=MI.MAXMIND_CONNECTION_TYPE,
IP.IP2_CT=MI.IP2_CONNECTION_TYPE
FROM
LIFE_V3.RESOURCE.V2_MAXIP2_BLOCKS MI
WHERE LENGTH(IP_INT_FROM)<=10 AND LENGTH(IP_INT_TO)<=10 AND
 IP_INT_FROM<=INT_IP AND INT_IP<= IP_INT_TO AND (IP.STD_NAME IS NULL OR IP.STD_NAME='') AND 
INJECTDAY = CURRENT_DATE-1 ;

UPDATE AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL SET IP_INT_V6 = AROSCOP_DM_COX.ANALYSIS.IPV6_TO_LONG(IPADDRESS) WHERE 
(STD_NAME IS NULL OR STD_NAME='') AND IPADDRESS LIKE '%:%' AND IPADDRESS NOT LIKE '%::%' AND
LENGTH(SPLIT_PART(IPADDRESS, ':', -1))>0 AND PARSE_IP(IPADDRESS, 'INET'):family=6 AND 
INJECTDAY = CURRENT_DATE-1;

UPDATE AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL IP
SET
IP.CLIENT_NAME=MI.CLIENT_NAME,
IP.SCIERA_TYPE=MI.SCIERA_TYPE,
IP.STD_NAME=MI.STD_NAME,
IP.MAXMIND=MI.MAXMIND_NAME,
IP.IP2=MI.IP2_NAME,
IP.IP2_DOMAIN=MI.IP2_DOMAIN,
IP.MAXMIND_CT=MI.MAXMIND_CONNECTION_TYPE,
IP.IP2_CT=MI.IP2_CONNECTION_TYPE
FROM
LIFE_V3.RESOURCE.V2_MAXIP2_BLOCKS MI
WHERE
 IP_INT_FROM<=IP.IP_INT_V6 AND IP.IP_INT_V6<= IP_INT_TO AND (IP.STD_NAME IS NULL OR IP.STD_NAME='') AND 
INJECTDAY = CURRENT_DATE-1 ;

CREATE OR REPLACE TABLE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT AS 
SELECT DISTINCT INJECTDAY,ZIP5,DEVICETYPE,CAMPAIGNID,ADID,CREATIVEID,SLOTID,STD_NAME FROM AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL WHERE INJECTDAY >= '2025-02-03' ;

ALTER TABLE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT ADD COLUMN IMPRESSIONS INT, CLICKS INT;

UPDATE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT A SET IMPRESSIONS = (SELECT COUNT(DISTINCT IMPRESSIONID) FROM AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL B
 WHERE A.INJECTDAY=B.INJECTDAY AND 
 A.ZIP5=B.ZIP5 AND 
 A.DEVICETYPE=B.DEVICETYPE AND 
 A.CAMPAIGNID=B.CAMPAIGNID AND 
 A.ADID=B.ADID AND 
 A.CREATIVEID=B.CREATIVEID AND 
 A.SLOTID=B.SLOTID AND 
 IFNULL(A.STD_NAME,'')=IFNULL(B.STD_NAME,'') AND STATUS='19');
 
 UPDATE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT A SET CLICKS = (SELECT COUNT(DISTINCT IMPRESSIONID) FROM AROSCOP_DM_COX.REPORTING.POSTIMPRESSION_DETAIL B
 WHERE A.INJECTDAY=B.INJECTDAY 
 AND A.ZIP5=B.ZIP5 
 AND A.DEVICETYPE=B.DEVICETYPE 
 AND A.CAMPAIGNID=B.CAMPAIGNID 
 AND A.ADID=B.ADID 
 AND A.CREATIVEID=B.CREATIVEID 
 AND A.SLOTID=B.SLOTID
 AND IFNULL(A.STD_NAME,'')=IFNULL(B.STD_NAME,'') 
 AND EVENT=3  AND STATUS='19');

ALTER TABLE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT ADD COLUMN CREATIVE_NAME VARCHAR, CREATIVE_SIZE VARCHAR, FORMAT_ID INT, FORMAT_TYPE VARCHAR;

UPDATE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT A SET A.CREATIVE_NAME=B.NAME ,A.FORMAT_ID=B.FORMAT_ID 
FROM SCIERA_DATASET.PUBLIC.AROSCOP_CREATIVE_CONTAINER B WHERE A.CREATIVEID=B.ID;

UPDATE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT A SET FORMAT_TYPE=DESCRIPTION FROM SCIERA_DATASET.PUBLIC.AROSCOP_META_CREATIVE_FORMATS B WHERE A.FORMAT_ID=B.ID;
UPDATE AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT A SET CREATIVE_SIZE=DESCRIPTION FROM SCIERA_DATASET.PUBLIC.AROSCOP_META_ADSIZE  B WHERE A.SLOTID=B.ID;

CREATE OR REPLACE TABLE USCS.USER_DATA.COMCAST_DM AS 
SELECT INJECTDAY, ZIP5 AS ZIPCODE,FORMAT_TYPE, CREATIVE_SIZE, STD_NAME,C.DESCRIPTION AS DEVICE_TYPE, SUM(IMPRESSIONS) AS AROSCOP_IMPRESSIONS, SUM(CLICKS) AS AROSCOP_CLICKS 
FROM AROSCOP_PUBLISH.POC.POSTIMPRESSION_COMCAST_DISTINCT A, 
SCIERA_DATASET.PUBLIC.AROSCOP_META_DEVICETYPE C 
WHERE A.DEVICETYPE=C.ID  
GROUP BY ALL;

GRANT ALL ON USCS.USER_DATA.COMCAST_DM TO ROLE USCS;
