COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYANALYST"/V4_CTELL/WIP_STAGING/PUBLISH/WIP_CURRENT/WIP_CURRENT.bz2'
from (SELECT MSO,SERVICENAME,FP_KEY,PROJECTNAME,SCHEDULEDATE,STATUS,CHECK_DATE,MAX_SPEED,UPLOAD_MAX_SPEED,DELIVERED_DATE,BUDGET_YEAR,BUDGET_MONTH,BUDGET_TYPE,PROJECT_TYPE,ENGAGEMENT_TYPE,STD_NAME,DELIVERED_YEAR,DELIVERED_MONTH,CLIENT_FILENAME,CLIENT_SENT_DATE,CLIENT_PROVIDER_NAME
 FROM "V4_CTELL"."PROC"."WIP_CURRENT")
FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') 
             EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=FALSE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;
			 
COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYANALYST"/V4_CTELL/WIP_STAGING/PUBLISH/HKEY_CURRENT/HKEY_CURRENT.bz2'
from (SELECT MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,PROVIDER_TYPE,ZIP5,ZIP4,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,OPEN_DATE,CLOSE_DATE,LAST_CHECK_DATE,PREV_MAX_SPEED,PREV_FIBER_TV_PROVIDER,PREV_FIBER_PHONE_PROVIDER,PREV_OPEN_DATE,FP_RWID,FP_SRWID,MOST_RECENT_CHECK_DATE,MOST_RECENT_MAX_SPEED,UPLOAD_MAX_SPEED,
 FROM "V4_CTELL"."PROC"."HKEY_CURRENT" )
FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') 
             EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=FALSE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;

COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYANALYST"/V4_CTELL/WIP_STAGING/PUBLISH/HKEY_CURRENT_OPEN/HKEY_CURRENT_OPEN.bz2'
from (SELECT MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,UPPER(PROVIDER_TYPE),ZIP5,ZIP4,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,OPEN_DATE,CLOSE_DATE,LAST_CHECK_DATE,PREV_MAX_SPEED,PREV_FIBER_TV_PROVIDER,PREV_FIBER_PHONE_PROVIDER,PREV_OPEN_DATE,FP_RWID,FP_SRWID,MOST_RECENT_CHECK_DATE,MOST_RECENT_MAX_SPEED,UPLOAD_MAX_SPEED,
 FROM "V4_CTELL"."PROC"."HKEY_CURRENT" WHERE CLOSE_DATE IS NULL)
FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') 
             EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=FALSE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;

COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/WIP_STAGING/HKEY_MSO-WISE/cox/'
from (SELECT MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,PROVIDER_TYPE,ZIP5,ZIP4,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,OPEN_DATE,CLOSE_DATE,LAST_CHECK_DATE,PREV_MAX_SPEED,PREV_FIBER_TV_PROVIDER,PREV_FIBER_PHONE_PROVIDER,PREV_OPEN_DATE,FP_RWID,FP_SRWID,MOST_RECENT_CHECK_DATE,MOST_RECENT_MAX_SPEED,UPLOAD_MAX_SPEED,
 FROM "V4_CTELL"."PROC"."HKEY_CURRENT" WHERE UPPER(MSO) = 'COX')
FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') 
             EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=FALSE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;


COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/WIP_STAGING/HKEY_MSO-WISE/comcast/'
from (SELECT MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,PROVIDER_TYPE,ZIP5,ZIP4,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,OPEN_DATE,CLOSE_DATE,LAST_CHECK_DATE,PREV_MAX_SPEED,PREV_FIBER_TV_PROVIDER,PREV_FIBER_PHONE_PROVIDER,PREV_OPEN_DATE,FP_RWID,FP_SRWID,MOST_RECENT_CHECK_DATE,MOST_RECENT_MAX_SPEED,UPLOAD_MAX_SPEED,
 FROM "V4_CTELL"."PROC"."HKEY_CURRENT" WHERE UPPER(MSO) = 'COMCAST')
FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') 
             EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=FALSE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;


COPY INTO '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/WIP_STAGING/HKEY_MSO-WISE/charter/'
from (SELECT MSO,FP_KEY,PROJECT_NAME,PROVIDER_NAME,PROVIDER_TYPE,ZIP5,ZIP4,MAX_SPEED,FIBER_TV_PROVIDER,FIBER_PHONE_PROVIDER,OPEN_DATE,CLOSE_DATE,LAST_CHECK_DATE,PREV_MAX_SPEED,PREV_FIBER_TV_PROVIDER,PREV_FIBER_PHONE_PROVIDER,PREV_OPEN_DATE,FP_RWID,FP_SRWID,MOST_RECENT_CHECK_DATE,MOST_RECENT_MAX_SPEED,UPLOAD_MAX_SPEED,
 FROM "V4_CTELL"."PROC"."HKEY_CURRENT" WHERE UPPER(MSO) = 'CHARTER')
FILE_FORMAT=( TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' COMPRESSION ='BZ2' FIELD_DELIMITER = '|' SKIP_HEADER = 0 NULL_IF=('') 
             EMPTY_FIELD_AS_NULL = FALSE ) SINGLE=FALSE HEADER = FALSE OVERWRITE = TRUE MAX_FILE_SIZE =5000000000;