COPY INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_SCHEDULED_INPUT" (MSO,SERVICENAME,FP_KEY,PROJECTNAME,SCHEDULEDATE,INPUT_FILE_NAME,INPUT_FILE_DATE) FROM (SELECT t.$1,t.$2,t.$3,t.$4,t.$5,'<<file_name>>','<<current_date>>' FROM  '@"SCIERA_SUBSYSTEM"."REALWATCH"."SIS_SKYCTEL"/<<file_path>>' t) FILE_FORMAT = (COMPRESSION = 'AUTO' FIELD_DELIMITER = '|',RECORD_DELIMITER = '\n',SKIP_HEADER = 0,FIELD_OPTIONALLY_ENCLOSED_BY = '\"',TRIM_SPACE = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE, ESCAPE = 'NONE', ESCAPE_UNENCLOSED_FIELD = '\134', DATE_FORMAT = 'AUTO', TIMESTAMP_FORMAT = 'AUTO', NULL_IF = ('NULL'),encoding = 'iso-8859-1') ON_ERROR = 'CONTINUE' PURGE = FALSE;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_SCHEDULED_INPUT"
SET 
MSO = UPPER(MSO),
SERVICENAME = UPPER(SERVICENAME),
FP_KEY = UPPER(FP_KEY),
PROJECTNAME = UPPER(PROJECTNAME),
SCHEDULEDATE = UPPER(SCHEDULEDATE) WHERE INPUT_FILE_NAME = '<<file_name>>';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_SCHEDULED_INPUT" A
SET A.EXIST_IN_WIP = 'Y'
FROM "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" B
WHERE A.MSO = B.MSO AND A.SERVICENAME = B.SERVICENAME AND A.FP_KEY = B.FP_KEY
AND A.PROJECTNAME = B.PROJECTNAME  AND A.INPUT_FILE_NAME = '<<file_name>>'; 

INSERT INTO "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" (MSO,SERVICENAME,FP_KEY,PROJECTNAME,SCHEDULEDATE,INPUT_FILE_NAME,INPUT_FILE_DATE) SELECT MSO,SERVICENAME,FP_KEY,PROJECTNAME,SCHEDULEDATE,INPUT_FILE_NAME,INPUT_FILE_DATE FROM 
"<<DB_NAME>>"."<<SCHEMA_NAME>>"."CTEL_SCHEDULED_INPUT" WHERE INPUT_FILE_NAME = '<<file_name>>' AND EXIST_IN_WIP = 'N';

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = B.DWELL_TYPE,
	A.DMA = B.SCIERA_DMA	
    FROM (SELECT * FROM "MSO"."V3_CHARTER_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'CHARTER' AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = B.DWELL_TYPE,
	A.REGION = B.H2,
    A.DMA = B.SCIERA_DMA	
    FROM (SELECT * FROM "MSO"."V3_COMCAST_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'COMCAST' AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = B.DWELL_TYPE,
    A.DMA = B.SCIERA_DMA	
    FROM (SELECT * FROM "MSO"."V3_COX_RESOURCE"."FP" WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) = 'COX' AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  


UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.CENSUS_BLOCK,
    A.H1 = B.H1,
	A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.ZIP5,''),IFNULL(B.ZIP4,'')),''),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_CHARTER_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'CHARTER_SMB' AND A.FP_KEY =B.STD_BUILDINGID AND IFNULL(A.CB,'')='';  
  
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.CENSUS_BLOCK,
    A.H1 = B.H1,
	A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.ZIP5,''),IFNULL(B.ZIP4,'')),''),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_COMCAST_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'COMCAST_SMB' AND A.FP_KEY =B.STD_BUILDINGID AND IFNULL(A.CB,'')='';  
  
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.CENSUS_BLOCK,
    A.H1 = B.H1,
	A.ZIP5 = B.ZIP5,
    A.ZIP4 = B.ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.ZIP5,''),IFNULL(B.ZIP4,'')),''),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_COX_SMB"."CTELL_FP" WHERE CLOSE_DATE IS NULL) B
WHERE  REPLACE(UPPER(A.MSO),'BUSINESS','SMB') = 'COX_SMB' AND A.FP_KEY =B.STD_BUILDINGID AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CB = B.SCIERA_CB,
    A.H1 = B.H1,
	A.ZIP5 = B.SCIERA_ZIP5,
    A.ZIP4 = B.SCIERA_ZIP4,
    A.ZIP9 =  NULLIF(CONCAT(IFNULL(B.SCIERA_ZIP5,''),IFNULL(B.SCIERA_ZIP4,'')),''),
    A.DWELL_TYPE = UPPER(B.DWELL_TYPE),
    A.DMA = B.SCIERA_DMA		
    FROM (SELECT * FROM "MSO"."V3_COX_PRE_SERV_RESOURCE"."FP"  WHERE IFNULL(DELETE_DATE,'')='') B
WHERE  UPPER(A.MSO) IN('COX-PRE-SERV','COX') AND A.FP_KEY =B.FP_KEY AND IFNULL(A.CB,'')='';  

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET BUDGET_TYPE = CASE WHEN UPPER(SERVICENAME)='ATT' THEN 'ATT'
                       WHEN UPPER(SERVICENAME) IN ('TMOBILE5G-HOME','VERIZON1115G') THEN 'FWA'
                       ELSE 'NON ATT' END
WHERE BUDGET_TYPE IS NULL;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET PROJECT_TYPE = CASE WHEN UPPER(SUBSTR(PROJECTNAME,1,1))='B'  THEN 'BL'
                        WHEN UPPER(SUBSTR(PROJECTNAME,1,1))='D' OR 
                             UPPER(SUBSTR(PROJECTNAME,1,2))='NQ' THEN 'NQ'
                        WHEN UPPER(SUBSTR(PROJECTNAME,1,1))='W' THEN 'WL'
                        WHEN UPPER(SUBSTR(PROJECTNAME,1,2))='A_' THEN 'AH'
						WHEN UPPER(SUBSTR(PROJECTNAME,1,2))='LN' THEN 'LENS'
                        ELSE NULL END
WHERE PROJECT_TYPE IS NULL;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET ENGAGEMENT_TYPE = CASE WHEN UPPER(MSO) LIKE '%BUSINESS%' THEN 'SMB'
                        ELSE 'RESI' END
WHERE ENGAGEMENT_TYPE IS NULL;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET QUEUE_YEAR=YEAR(CAST(SCHEDULEDATE AS DATE)) WHERE QUEUE_YEAR IS NULL ;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"
SET QUEUE_MONTH= MONTH(CAST(SCHEDULEDATE AS DATE)) WHERE QUEUE_MONTH IS NULL ;

UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
 SET A.STD_NAME=B.STD_NAME FROM "LIFE_V3"."RESOURCE"."MASTER_STD_NAME_CTELL"  B
 WHERE UPPER(A.SERVICENAME)=UPPER(PUBLISH_NAME) AND ACTIVE='Y' AND A.STD_NAME IS NULL;
 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT"  A
SET A.STD_NAME= B.STD_NAME
FROM "V4_CTELL"."TEST"."MASTER_STD_NAME_CTELL_EXCEPTIONAL" B
WHERE UPPER(A.SERVICENAME)=B.PUBLISH_NAME AND A.STD_NAME IS NULL; 

 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CLIENT_FILENAME = B.CLIENT_FILENAME,
    A.CLIENT_SENT_DATE = B.CLIENT_SENT_DATE, 
    A.CLIENT_PROVIDER_NAME = B.CLIENT_PROVIDER_NAME
 FROM  "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"  B
 WHERE A.FP_KEY = B.FP_KEY AND A.PROJECTNAME =B.PROJECT_NAME AND A.SERVICENAME = B.SERVICE_PROVIDER
AND A.CLIENT_FILENAME IS NULL;
 
UPDATE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" A
SET A.CLIENT_FILENAME = B.CLIENT_FILENAME,
    A.CLIENT_SENT_DATE = B.CLIENT_SENT_DATE, 
    A.CLIENT_PROVIDER_NAME = B.CLIENT_PROVIDER_NAME
 FROM  "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"  B
 WHERE A.FP_KEY = B.UQID AND A.PROJECTNAME =B.PROJECT_NAME AND A.SERVICENAME = B.SERVICE_PROVIDER
AND A.CLIENT_FILENAME IS NULL;
 
 UPDATE "V4_CTELL"."PROC"."WIP_CURRENT" A
SET A.BUDGET_YEAR = B.BUDGET_YEAR,
    A.BUDGET_MONTH = B.BUDGET_MONTH 
 FROM  "SCIERA_SUBSYSTEM"."SKY_OP"."CTELL_PRE_QUEUE_MASTER"  B
 WHERE A.FP_KEY = B.FP_KEY AND A.PROJECTNAME =B.PROJECT_NAME AND A.SERVICENAME = B.SERVICE_PROVIDER
AND (A.BUDGET_YEAR IS NULL OR A.BUDGET_MONTH IS NULL);
 
UPDATE "V4_CTELL"."PROC"."WIP_CURRENT" A
SET A.BUDGET_MONTH = B.BUDGET_MONTH,
    A.BUDGET_YEAR = B.BUDGET_YEAR
FROM    
(SELECT BUDGET_YEAR,BUDGET_MONTH,PROJECTNAME,REPLACE(REPLACE(SERVICENAME,'ATT','ATT-AIR'),'VERIZON','VERIZON1115G') AS SERVICENAME,FP_KEY FROM "V4_CTELL"."PROC"."WIP_CURRENT"
WHERE SERVICENAME IN ('ATT','VERIZON') AND QUEUE_YEAR = 2024  ) B
WHERE A.FP_KEY = B.FP_KEY AND A.SERVICENAME = B.SERVICENAME AND  A.PROJECTNAME = B.PROJECTNAME
 AND (A.BUDGET_YEAR IS NULL OR A.BUDGET_MONTH IS NULL); 
 
CREATE OR REPLACE TABLE "<<DB_NAME>>"."PUBLISH"."WIP_CURRENT"  CLONE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."WIP_CURRENT" ;

CREATE OR REPLACE TABLE "<<DB_NAME>>"."PUBLISH"."HKEY_CURRENT"  CLONE "<<DB_NAME>>"."<<SCHEMA_NAME>>"."HKEY_CURRENT" ;
		
		
		